### ISSUE TITLE
DbUp and MonoTouch

### ISSUE THREAD

**Issue by dazinator** [DbUp/DbUp#100]
When adding DbUp to a monotouch project, the Linker cannot resolve the type `Microsoft.SqlServer.Server.SqlContext` type.

This type is used in one place:

``` csharp
internal class SqlContextUpgradeLog : IUpgradeLog
    {
        public void WriteInformation(string format, params object[] args)
        {
            SqlContext.Pipe.Send("INFO:  " + string.Format(format, args));
        }

        public void WriteError(string format, params object[] args)
        {
            SqlContext.Pipe.Send("ERROR: " + string.Format(format, args));
        }

        public void WriteWarning(string format, params object[] args)
        {
            SqlContext.Pipe.Send("WARN:  " + string.Format(format, args));
        }
    }
```

Perhaps we can compile for mono and use some compilation directives to exclude this class when compiling for mono / monotouch. The mono version of the System.Data doesn't appear to have this type.

**Comment by dazinator** [comment]
- I should say, this is only a linker issue, as when disabling the linker, and using the DbUp.SqlLite.Mono provider, everything works prefectly on monotouch.

**Comment by dazinator** [comment]
Also a problem on monotouch is the fact there is no `Console` so the linker has issues with for example:

 /// <summary>
    /// Logs to the console using pretty colours.
    /// </summary>
    /// <param name="builder">The builder.</param>
    /// <returns>
    /// The same builder
    /// </returns>
    public static UpgradeEngineBuilder LogToConsole(this UpgradeEngineBuilder builder)
    {
        return LogTo(builder, new ConsoleUpgradeLog());
    }

**Comment by droyad** [comment]
This should be fixed by the .NET Core port
