### ISSUE TITLE
Hability to provide rollback scripts

### ISSUE THREAD

**Issue by mmerayo** [DbUp/DbUp#103]
It would be nice if there was a feature that allows to revert scripts in the reverse order of execution down to an specific filename.
This would imply providing rollback scripts in an specific folder with the same names than the incremental scripts to allow an easy rollback for instance when a release is cancelled due to issues in the deployment.

**Comment by AdrianJSClark** [comment]
This feature has had some discussion over at Issue #42. @JakeGinnivan proposes the start of a solution in [his comment](https://github.com/DbUp/DbUp/issues/42#issuecomment-62548287).

**Comment by JakeGinnivan** [comment]
Yep, jump over to #42, will close this issue
