### ISSUE TITLE
Ability to return an IDbCommand rather than a sql string for code migration

### ISSUE THREAD

**Issue by robdmoore** [DbUp/DbUp#12]
If you need to add parameters to a migration that you are adding with code then you need to use the provided IDbConnection to create and populate a command, open the connection yourself and execute the command. Then you need to return a dummy string for it to execute for the migration itself, which seems a bit of a hack.

It would be cool if there was a way to instead provide DbUp a populated IDbCommand and get it to execute it for you instead. Maybe another interface to allow this to be opt-in, e.g. ICommandScript or something?

**Comment by rickculpepper** [comment]
@robdmoore, could you elaborate a bit? 

Perhaps the script returned by the IScript component could use a variable reference for each parameter, e.g., $CustomerId$, $OrderNo$, $ShipDate$, rather than a parameter? While variable substitution does not provide protection from SQL Injection attacks, it is more flexible. E.g., you can use a variable reference _anywhere_ in your script, including places that a parameter cannot be used.

**Comment by robdmoore** [comment]
If you provided the ability to have placeholders then you'd also need to provide the ability to provide variables.

I suspect providing an ability to simply provide the command is easier than that and then you don't have to worry about sql injection.

**Comment by rickculpepper** [comment]
Actually, DbUp already has the ability to provide both named placeholders (variables) and replacement values for them. 

In your script, you might say...
```
Insert into [dbo].[$TableName$] ([Description]) values ('Description Text');
```
Then youbtrll the Builder to use the variable and it's value like so.

```
DeployChanges.To
    .SqlDatabase(...)
    .WithVariable("TableName", "tblDescriptions")
    .Build();
```
During the upgrade process DbUp scans each script replacing variable references with the specified value. In this example, "$Table_Name$" would be replaced with "tblDescriptions".

In a future release, DbUp will also support SQLCMD-style variable references, e.g. "$(TableName)".

Is it possible that this functionality would meet your needs?

**Comment by robdmoore** [comment]
Possibly, I'll be completely honest and say that I can't remember the specific case that prompted me to raise this.

Off the top of my head, those variable declarations are global, whereas I was possibly thinking of migration-specific values.

Happy for this issue to be parked pending a concrete use case :)
