### ISSUE TITLE
Tighter Octopus Deploy intergration

### ISSUE THREAD

**Issue by jrote1** [DbUp/DbUp#132]
Not sure if this is the right place. But it would be good if DbUp was more tightly intergrated into Octopus Deploy so when a deployment is finished it shows on the task summary screen what scripts were run.

**Comment by droyad** [comment]
Quite an old suggestion, but I think it's a good idea. I've started add a feature to Octopus that allows this https://github.com/OctopusDeploy/Issues/issues/4264.

I'll probably add a method to the result object to write the right thing out to console.
