### ISSUE TITLE
NuGet package typo

### ISSUE THREAD

**Issue by rocklan** [DbUp/DbUp#133]
The nuget package for 3.3.0 has a typo in it - the id for the package is "dbup", and it needs to be "DbUp". This was an issue for me when I added DbUp to my own private nuget repo. (As a workaround I simply changed it to "DbUp" and created a "3.3.0.1" that I commited to my own repo).

![dbup](https://cloud.githubusercontent.com/assets/2829865/9954158/fdb676b6-5e29-11e5-8e1a-93f6918c789d.png)

**Comment by JakeGinnivan** [comment]
Could you elaborate?

The old NuSpec had `dbup` all lower case, see https://github.com/DbUp/DbUp/blob/3.2.1/build/dbup.nuspec

**Comment by clockwisemusic** [comment]
The issue happened when I added DbUp to a project, and then added the
package to my own nuget repository. If I then clear out my packages locally
(or have another developer check out the project) when looking for packages
as part of the compile it says that it can't find the package "DbUp", so I
needed to rename the id to DbUp.

**Comment by droyad** [comment]
The package names have all changed, so closing
