### ISSUE TITLE
Pull SqlServer out of the Core

### ISSUE THREAD

**Issue by dazinator** [DbUp/DbUp#134]
Each provider has it's own project, except ms sql server..
We should pull this out into its own provider

**Comment by dazinator** [comment]
Will send a PR

**Comment by JakeGinnivan** [comment]
I have started this already. There is a branch in my fork

Sent from my Windows Phone
________________________________

**Comment by dazinator** [comment]
Doh! I had allreayd got most of the way through and put in some other fixes so thought I would finish off and submit PR anyway!
