### ISSUE TITLE
Exception in the method SqlScriptExecutor.Log

### ISSUE THREAD

**Issue by WiRuc** [DbUp/DbUp#138]
Hi,
I got following exception after execution of some scripts on MSSQL:

System.InvalidOperationException: Sequence contains no elements
  StackTrace:
       at System.Linq.Enumerable.Max(IEnumerable`1 source)

I found error in the line 183 of the following code of method DbUp.Support.SqlServer.SqlScriptExecutor.Log(IDataReader reader) :

181                 for (int i = 0; i < reader.FieldCount; i++) 
182                 { 
183                     int maxLength = lines.Max(l => (l[i] ?? "").Length) + 2; 

The sequence "lines" may have no elements and it causes exception in this case.

**Comment by JakeGinnivan** [comment]
Thanks for the report. Did you want to try submitting a pull request? 

If you have not submitted one before I am happy to help walk you through the process.

**Comment by WiRuc** [comment]
I haven't done pull request before. I will try

**Comment by JakeGinnivan** [comment]
If you run into trouble, jump onto https://gitter.im/DbUp/DbUp and I can help you through it

**Comment by JakeGinnivan** [comment]
And optionally, if you can figure a test which causes the issue to happen that would be awesome

**Comment by WiRuc** [comment]
I have created pull request. Please check that I created it correctly. 
Regarding test I am not sure I will be able to provide test.

**Comment by JakeGinnivan** [comment]
The pull request has to target the main repository. at the moment it is targeting your fork.

**Comment by JakeGinnivan** [comment]
Will release fix over the next few days. Thanks for the contribution!
