### ISSUE TITLE
Naming of Journal Primary Key Constraint - Prevents more than one Migrator

### ISSUE THREAD

**Issue by GregoryJames** [DbUp/DbUp#146]
For each of the Journals (FireBirdTableJournal, PostgresqlTableJournal, SqLiteTableJournal and SqlTableJournal), the creation of the Journal Table is done something like below:

`
         protected virtual string CreateTableSql(string tableName)
        {
            return string.Format(@"create table {0} (
	[Id] int identity(1,1) not null constraint PK_SchemaVersions_Id primary key,
	[ScriptName] nvarchar(255) not null,
	[Applied] datetime not null
)", tableName);
        }
`

Note that the constraint is always called "PK_SchemaVersions_Id", no matter what the table name is. So if you try and create a second Journal Table, it will fail.

This means that if you (1) Have two migrators using two different table names, or (2) change the table name during development after running the migration once, all future migrations will fail.

I am unsure of the best solution for this long term is. Simply adding the table name to the constraint name will not work as it is the full escaped name (eg [dbo].[Journal Table Name]).

**Comment by chcoust** [comment]
This bug occured to me today also on MSSQL Server
We are adding a "DataMigration" project alongside our "DbMigration" project
and the PK already exsists

Upgrade failed due to an unexpected exception:
System.Data.SqlClient.SqlException (0x80131904): Il existe déjà un objet nommé '
PK_SchemaVersions_Id' dans la base de données.
Impossible de créer la contrainte. Voir les erreurs précédentes.


I pulled and modified the sources for now, waiting for an official fix

Thanks

**Comment by JakeGinnivan** [comment]
@chcoust could you submit a pull request with your fix?

**Comment by chcoust** [comment]
Hello, my fix is really ugly and specific to mssql (I didnt modify the other journal implentations)
I didn't pull the code via git, only downloaded the .zip, so I can not easily commit my (ugly) fix

Also in \DbUp\Support\SqlServer\SqlTableJournal.cs I didn't have the clean table name, it has the "[dbo].[table]" format and I didn't have time to make it proper for the pk name

The ugly fix : I added a guid in the pk name

        protected virtual string CreateTableSql(string tableName)
        {
            return string.Format(@"create table {0} (
	[Id] int identity(1,1) not null constraint PK_SchemaVersions_{1}_Id primary key,
	[ScriptName] nvarchar(255) not null,
	[Applied] datetime not null
)", tableName, Guid.NewGuid().ToString("N"));
        }

**Comment by GregoryJames** [comment]
In regards to the fix I did, I stored the table name from the construction and used that in a very similar manner to @chcoust ugly fix above.

But this did not take into account the following:

(1) The table name would need to be cleaned up (remove spaces, brackets etc), and
(2) Did not take into account same table name across different schemas.

My thoughts were to create the schema/table combination in the constructor for use in the constraint name.

I will try and get a PR up tomorrow night if you want as a discussion point. My main concern is that I do not know the rules for creating a clean constraint name from table names like "[Hello!% Kitty]" and have it work across all languages, and each of the database journals (do different DB technologies treat this differently).

**Comment by AdrianJSClark** [comment]
I'm working on a patch for this which I will make a PR for shortly.

The current ability to set the table name doesn't do anything to clean up the name beyond adding escape characters (i.e. surrounding in square brackets for SQL Server).

My plan is to simply include the configured table name in the name of the primary key constraint and surround the result with the same escape characters as for the table name.

**Comment by dazinator** [comment]
@AdrianJSClark sounds good to me!
