### ISSUE TITLE
Actively manage connections

### ISSUE THREAD

**Issue by trickbooter** [DbUp/DbUp#155]
Both TemporarySqlDatabase and UpgradeEngine do not offer direct control of the underlying SqlConnection object.

When needing to perform a multi-pass deploy with the TemporarySqlDatabase object, open connections prevent correct disposal of the TemporarySqlDatabase.

```
var uea = builder.build(); // first pass
var ueb = builder.build(); // same db, 2nd pass
using(var db = new TemporarySqlDatabase(cs))
{
  db.create();
  uea.PerformUpgrade();
  ueb.PerformUpgrade();
} // dispose fails as we have an open connection on ueb that we cannot close.
```

My specific scenario, I have a multi-db deploy with a circular reference (don't ask), so I have...

```
var uea = buildera.Build(); // on ConnStr a (csa)
var ueb = builderb.Build(); // on ConnStr b (csb)
var uec = builderc.Build(); // on ConnStr a (csa)
using(var dba = new TemporarySqlDatabase(csa))
{
  dba.Create();
  using(var dbb = new TemporarySqlDatabase(csb))
  {
    dbb.Create();
    uae.PerformUpgrade();
    uab.PerformUpgrade();
    uac.PerformUpgrade();
  } // dispose fails
} // dispose fails
```

Either reveal the connection directly (like the SqlLite TemporarySqlLiteDatabase implementation) or more aggressively manage connections. Actively closing connections immediately after upgrade would be preferable. Likewise opening and closing connections on the TemporarySqlDatabase only when needed.

**Comment by trickbooter** [comment]
After debugging, I have found that connection pooling is the source of my issue. Setting connection pooling = false on for the UpgradeEngine connection resolves the issue.

Pooling was maintaining the connection, preventing the TemporarySqlDb dispose. Not sure how obvious this is to people, and will only manifest itself in multi-pass situations (since connections become pooled).

**Comment by JakeGinnivan** [comment]
This could be something we detect and warn about?
