### ISSUE TITLE
A way to distinguish Seed Data from Sample Data

### ISSUE THREAD

**Issue by Leandro-Andrade** [DbUp/DbUp#156]
Hi there!

Is there a way to distinguish Seed Data from Test Data? If not could someone give me a example on how to implement this?

Usage scenario:

- Development Environment
    I want to have the ability to drop and recreate my database bringing Seed Data (Zip code, states, ect.) and some Test Data(Customers, orders).

- QA Environment
    I want to have the ability to do the same as Dev Environment

- Production Environment
    I want only updates and Seed Data (if needed)

I don't know how to differentiate it. Is there any convention out of the box? Something like folder Structure? 
SeedData/001 - xxx.sql
TestData/001 - xxx.sql
Scripts/0001 - Create Table xxx.sql

Thanks in advance!

**Comment by Leandro-Andrade** [comment]
Forgot to mention - That would happen in this order:

1 - Scripts (create, alter table, and so on)
2 - Seed Data
3 - Test Data

Thx!

**Comment by AdrianJSClark** [comment]
There aren't any built in conventions of this sort. When configuring your script provider you can use the optional `filter` argument to avoid executing scripts you don't wish to. Obviously this filter could take into account the environment and only return appropriate scripts.

Another alternative would be to build and execute three instances of the upgrade engine one after the other each including one type of script (likely by including an appropriate `filter` argument on the script provider). You can point all three at the same `SchemaVersions` table, provided your script names are unique. This would allow you to ensure the order that the groups of scripts are executed in and, with a simple `if` statement, avoid executing a whole group altogether.

**Comment by Leandro-Andrade** [comment]
Thought that could be something out of the box, but yeah, that helps a lot!

Thanks!

**Comment by Leandro-Andrade** [comment]
@AdrianJSClark Would there be a way of doing this by implementing IJournal?
I didn't quite get the idea of IJournal and didn't find any example of usage.
Could you give me a simple example on implementing IJournal?

Thanks in advance

**Comment by AdrianJSClark** [comment]
@Leandro-Andrade An `IJournal` is not the correct way to implement this. The `IJournal` implementation simply handles storing each script that has been executed and returning that list on future runs. The `IJournal` implementation has no idea about the scripts that are about to be executed so you couldn't filter them in any way. It simply returns the list of scripts already executed. The proper way is using the filter and, optionally, separate upgraders.

You would only implement your own `IJournal` if you wished to store the list of executed scripts in some sort of custom data store rather than the `SchemaVersions` table.

For more information on `IJournal` see the ["Journaling" page on the DbUp documentation](http://dbup.readthedocs.org/en/latest/more-info/journaling/)

**Comment by Leandro-Andrade** [comment]
Thanks a lot @AdrianJSClark 
I gave it a first try and got this. Seems to work good.
On `BuildFilter()` I have a convention to accept only few file names like `0001 - Create - Orders.sql` and if I passed `testdata` on arguments it will be included.

I guess the order will not make much difference, since it will respect the enumeration.

If I use a DateTime stamp instead of 001...999, will DbUp still execute it on the correct order?

```CSharp
public class Program
    {
        private static UpgradeEngineBuilder _upgrader;

        private static void Main(string[] args)
        {
            const string connString = "Server=.\\SQLEXPRESS; Database=DbUpTest; Trusted_connection=true;";

            if (ShouldDropAndRecreateDatabase(args))
                RecreateDatabase();

            _upgrader = DeployChanges.To
                .SqlDatabase(connString)
                .WithScriptsEmbeddedInAssembly(Assembly.GetExecutingAssembly(), BuildFilter(args));

            var result = _upgrader
                .LogToConsole()
                .Build()
                .PerformUpgrade();

            var scriptList = result.Scripts.Select(x => x.Name).ToList();

            if (!result.Successful)
            {
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine(result.Error);
                Console.ResetColor();
            }

            Console.ForegroundColor = ConsoleColor.Green;
            Console.WriteLine("Success!");
            Console.WriteLine("Total of Scripts Executed: {0}", scriptList.Count());
            Console.WriteLine("  - Seed Data: {0}", scriptList.Count(x => x.Contains(" - SeedData - ")));
            Console.WriteLine("  - Test Data: {0}", scriptList.Count(x => x.Contains(" - TestData - ")));
            Console.ResetColor();
            Console.ReadLine();
        }

        private static Func<string, bool> BuildFilter(IEnumerable<string> args)
        {
            Func<string, bool> onlySqlFilesFilter = x => x.EndsWith(".sql");
            Func<string, bool> createFilter = x => x.Contains(" - Create - ");
            Func<string, bool> dropFilter = x => x.Contains(" - Drop - ");
            Func<string, bool> insertFilter = x => x.Contains(" - Insert - ");
            Func<string, bool> updateFilter = x => x.Contains(" - Update - ");
            Func<string, bool> deleteFilter = x => x.Contains(" - Delete - ");
            Func<string, bool> seedDataFilter = x => x.Contains(" - SeedData - ");
            Func<string, bool> testDataFilter = x => !x.Contains(" - TestData - ");

            if (ShouldIncludeTestData(args))
                testDataFilter = x => x.Contains(" - TestData - ");

            Func<string, bool> resultFilter = join => onlySqlFilesFilter(join) && (
                                                       createFilter(join)
                                                      || dropFilter(join)
                                                      || insertFilter(join)
                                                      || updateFilter(join)
                                                      || deleteFilter(join)
                                                      || seedDataFilter(join))
                                                      || testDataFilter(join);

            return resultFilter;
        }

        private static bool ShouldDropAndRecreateDatabase(IEnumerable<string> args)
        {
            return args.Any(x => x == "recreate");
        }

        private static bool ShouldIncludeTestData(IEnumerable<string> args)
        {
            return args.Any(x => x == "testdata");
        }

        private static void RecreateDatabase()
        {
            Console.WriteLine("DROPING DATABASE DbUpTest");

            const string sqlConnectionString = "Data Source=.\\SQLEXPRESS;Integrated Security=True";
            var file = new FileInfo("..\\..\\RecreateDatabase");
            var script = file.OpenText().ReadToEnd();

            using (var conn = new SqlConnection(sqlConnectionString))
            {
                var cmd = new SqlCommand(script, conn);
                conn.Open();
                cmd.ExecuteNonQuery();
            }

            Console.WriteLine("CREATED DATABASE DbUpTest");
        }
    }
```

**Comment by AdrianJSClark** [comment]
Looks like a good solution there, @Leandro-Andrade.

Regarding your question about ordering, as long as you use `YYYYMMDD` format (or something similar) it should order fine. Under the covers it is simply using the default string sort order (as you can see in the [Embedded Script Provider source code](https://github.com/DbUp/DbUp/blob/master/src/DbUp/ScriptProviders/EmbeddedScriptsProvider.cs#L46))

**Comment by Leandro-Andrade** [comment]
Great! Thanks @AdrianJSClark

**Comment by ivanpointer** [comment]
Sorry to revive an old thread, but wanted to share another idea for those looking for solutions.

Something I'm considering is leveraging the replacement variables for this.  What we'd do is put the logic within the SQL script itself to decide to execute based on the variable value.

With this, we can write a simple hook to enumerate appSettings into the scripts as replacement variables, and therefore, leverage configuration transforms to enable/disable the test data.

Being able to stand up a fresh, disposable copy of a database for your integration tests, is an important part of a quality CI solution.

Ivan
