### ISSUE TITLE
Unable to see substituted variable in script content before upgrade

### ISSUE THREAD

**Issue by ivanovvitaly** [DbUp/DbUp#158]
Hey Guys,

I want to display content of the executing scripts before executing upgrade, but when I log the script content I see just raw script without substituted variables. Finally script is being executed correctly, but in console it displays incorrect.

Script file

``` sql
print 'hello, $name$';
```

Configuration code

``` csharp
var upgrader = DeployChanges.To
            .SqlDatabase(connectionString)
            .WithVariable("name", "Vitaly")
            ...
            .Build();

// here I see raw script content without substitution print 'hello, $name$';
upgrader.GetScriptsToExecute().ForEach(s =>  Console.WriteLine(s.Contents)); 
```

Please advice, thanks!

**Comment by AdrianJSClark** [comment]
Unfortunately it looks like the current architecture doesn't have an easily discoverable method for getting the script contents. The "script pre-processors" are applied in `SqlScriptExecutor` [(see line 96)](https://github.com/DbUp/DbUp/blob/master/src/DbUp/Support/SqlServer/SqlScriptExecutor.cs#L96) just before the scripts are run.

The good news is that you can implement a work-around by creating an `IScriptPreprocessor` implementation to perform your logging and adding it as a custom pre-processor. Custom pre-processors are executed _after_ the variables are substituted (see near line 96 above) so you'll be getting the content you are after.

Something like this should do the trick. Note this code is off the top of my head so might not be 100% right...

```C#
public class ScriptPrintingPreProcessor : IScriptPreprocessor
{
    public string Process(string contents)
    {
        Console.WriteLine(contents);
        return contents;
    }
}
```
Then include it in your configuration.
```C#
var upgrader = DeployChanges.To
            .SqlDatabase(connectionString)
            .WithVariable("name", "Vitaly")
            .WithPreProcessor(new ScriptPrintingPreProcessor())
            .Build();
```

Let us know how you go!

**Comment by ivanovvitaly** [comment]
Works for me, thanks!

**Comment by JakeGinnivan** [comment]
Might leave this one open. I think this is still something which would be good to solve.

**Comment by droyad** [comment]
Closing as #325 should fix this
