### ISSUE TITLE
SqlTableJournal could not find SchemaVersion table if the database collation is not set to Latin*

### ISSUE THREAD

**Issue by madrabaz** [DbUp/DbUp#170]
Hi,
SqlTableJournal could not find SchemaVersion table if the database collation is not set to Latin* because of that DbUp is always executing all scripts.

Solution; the table name( information_schema.tables) must be written upper-case  in the lookup query. https://github.com/DbUp/DbUp/blob/master/src/DbUp/Support/SqlServer/SqlTableJournal.cs#L195-L197
```cs
command.CommandText = string.IsNullOrEmpty(schema)
  ? string.Format("select 1 from information_schema.tables where TABLE_NAME = '{0}'", tableName)
  : string.Format("select 1 from information_schema.tables where TABLE_NAME = '{0}' and TABLE_SCHEMA = '{1}'", tableName, schemaName);
```

**Comment by omnibs** [comment]
Thanks for the report @madrabaz =]

What collation are you using? 

I'm setting up sqlserver to test this.

**Comment by omnibs** [comment]
Confirmed, testes with some random chinese collation

**Comment by madrabaz** [comment]
I am using TURKISH_CI_AS

Thanks,
