### ISSUE TITLE
CarriageReturn removal

### ISSUE THREAD

**Issue by lambo76** [DbUp/DbUp#172]
Hi,

I've been using DbUp with Octopus and it works great.  Have come across an issue as it explicitly ignores Carriage Returns.  When DbUp creates a stored procedure these are not included so modifying in SQL Server Management studio it reports "inconsistent line endings".  This in it's self is not an issue as SSMS handles this, however we use Nettiers and CodeSmith to generate our Data Layer which throws and error as it can't read the file correctly from SQL.

This change was made 10/09/2015, was there a specific reason you've come across to ignore them.

**Comment by esterad** [comment]
I submitted PR [#163](https://github.com/DbUp/DbUp/pull/163) that seems to fix this issue, but to this day there is no response :(
