### ISSUE TITLE
CoreCLR

### ISSUE THREAD

**Issue by sklose** [DbUp/DbUp#174]
Are there any plans for supporting CoreCLR / DNX projects?

**Comment by omnibs** [comment]
@JakeGinnivan is working on this if I remember correctly.

**Comment by JakeGinnivan** [comment]
I plan on releasing v4 for core clr and probably switch over to the DNX tooling. At this point I will probably wait for RC2 to drop before making the switch.

What I need help with is testing the v4 branch. I am going to create an issue to get some feedback on v4 to move forward with this.

**Comment by LVladymyr** [comment]
Hi @JakeGinnivan . I am really waiting for you library.  Please tell how could we help you in testing it ?
Could you publish the last version of v4 with -beta postfix? In would be easy to test it in this way.

**Comment by JakeGinnivan** [comment]
I will get a beta out this weekend

**Comment by sklose** [comment]
I uploaded the 4.0 nuget packages of the last green build on AppVeyor to a myget feed https://www.myget.org/F/coreclr-betas/api/v3/index.json. If somebody wants to start using the .NET Core version, feel free to add it your nuget.config. I will keep updating it until there is an official release on nuget.org

**Comment by TheRubble** [comment]
@sklose I'm using the .NET core version, so far so good performed around 20 migrations.

**Comment by droyad** [comment]
@JakeGinnivan Anything I can do to help get this out?

**Comment by JakeGinnivan** [comment]
@droyad added you as contributor. Email/skype me if you need anything. Am not likely to get back to this for another month or so due to new job, being busy and also not using DbUp right now.

**Comment by adback03** [comment]
Hey guys, any timeline on when this will get out of Beta? My team has a .NET Core project that could be completely switched to the .NET Core framework (instead of 4.6) once this package is published to NuGet. Thanks!

**Comment by vadimi** [comment]
I've also used this package multiple times with .NET Core, no issues so far. It would be great to release an official one to NuGet.

**Comment by JakeGinnivan** [comment]
Will try get something happening, I am not using .net at the moment at all which makes spending time on DbUp a bit harder. Happy to help anyone get involved and become a maintainer

**Comment by TheRubble** [comment]
I don't mind giving it a go if you'd like to get me onboard.

**Comment by hossambarakat** [comment]
@JakeGinnivan I could help with getting this out of the door, Would you provide us with what is remaining ?

**Comment by gingters** [comment]
I tried to install the `4.0.0-beta0002` from the myget feed, but it does not work.

I created a new .NET Core console application from VS 2017 (release), (target netcoreapp 1.1) and tried to install the dbup-mysql package, but I get the following error:

```
Installing dbup-mysql 4.0.0-beta0002.
Package dbup-mysql 4.0.0-beta0002 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package dbup-mysql 4.0.0-beta0002 supports: net35 (.NETFramework,Version=v3.5)
One or more packages are incompatible with .NETCoreApp,Version=v1.1.
```

So my question is, what is the current status of the project for .NET Core? What is open? Can we jump in somewhere to get that working and at least a new beta build out that's working in a netcoreapp ?

**Comment by vadimi** [comment]
@JakeGinnivan I'd be happy to help too. How can I get involved?

**Comment by NoelAdy** [comment]
I'd be happy to help out here too.

**Comment by aggieben** [comment]
I've forked this and taken a first stab at a migrated solution using the latest released CLI tooling (1.0.3 at the time of writing).  Apparently there is some issue preventing core msbuild from building the migrated solution due to targeting `net35` (see https://github.com/Microsoft/msbuild/issues/1333), but it can be built using desktop msbuild (ships with visual studio 2017).

The Cake script doesn't work anymore.  I only started looking into Cake because of this project, but it appears that supporting the latest .NET Core tooling is kind of bleeding edge for Cake (see https://github.com/cake-contrib/Cake.Incubator/issues/10).

I'm not sure what next steps to take here.  Killing `net35` support would allow us to sidestep the tooling issues; does anyone really need .NET 3.5 support?

**Comment by droyad** [comment]
@aggieben We've managed to build a csproj .NET Core project using build: https://github.com/OctopusDeploy/Halibut/blob/master/build.cake. The main challenge was getting the paths right. If they are wrong, you get some weird unrelated error.

On the upside, the project files don't need to be updated with the versions anymore.

**Comment by aggieben** [comment]
@droyad 
> On the upside, the project files don't need to be updated with the versions anymore.

Oh?  What changed?

**Comment by droyad** [comment]
@aggieben  You can now do it via the `/p:Version` parameter: https://github.com/OctopusDeploy/Halibut/blob/master/build.cake#L74

**Comment by aggieben** [comment]
I've updated my branch, and I have everything building under the new project system.  Unfortunately, I couldn't get the build system to work against `net35`, so I bumped everything that was `net35` to `net40`.  I have 18 failing tests that I am trying to run down.

**Comment by briman0094** [comment]
@droyad may I ask how you run your build script? I'm trying to migrate a FOSS project from `project.json`/`.xproj` files to the new VS2017 `.csproj` file, and when I run the build script, it complains with `Error CS2001: Source file C:\<whatever> could not be found`, where `<whatever>` is the source file's relative path from the `.csproj` file. It seems the cakefile is running in `C:\` instead of in the project directory.

I tried to clone Halibut and build it, and got the same issue, so it makes me thing I may have a local configuration issue.

**Comment by droyad** [comment]
@briman0094 just from `cmd` or powershell prompt. Check to make sure your powershell profile doesn't change the directory. (ie run `PowerShell` and make sure the dir is the same)

**Comment by aggieben** [comment]
Update: I'm probably not going to come back to this.  I no longer have any projects that use DbUp, so anyone who wants this is welcome to take my fork and run with it.

**Comment by kspearrin** [comment]
Any movement on this as of late? DbUp is an awesome tool that I have used in the past and now that we use .NET Core on more and more things we're left with no good options. :(

**Comment by kspearrin** [comment]
Hey guys,
Some good news! I just tried DbUp in a .NET Core 2.0 project and it works just fine. This is due to the library shimming that .NET Core 2.0 does to make old libraries compatible.

In addition to adding `DbUp` library to your project, you just need to add `System.Data.SqlClient` (4.4.0) from nuget as well.

I haven't tested everything, but here's the code/features I am using successfully:

```
var upgrader = DeployChanges.To
    .SqlDatabase(MY_CONNECTION_STRING)
    .JournalToSqlTable("dbo", "Migrations")
    .WithScriptsAndCodeEmbeddedInAssembly(
        Assembly.GetExecutingAssembly(),
        (string s) => s.Contains($".Scripts."))
    .WithTransactionPerScript()
    .LogToConsole()
    .WithExecutionTimeout(new TimeSpan(0, 0, 90))
    .Build();

var result = upgrader.PerformUpgrade();
```

👍

**Comment by droyad** [comment]
Unless I am mistaken you need to have the .NET Framework installed to take advantage of the shimming. So it will not work on Linux. I'm planning on moving this forward this week.

**Comment by kspearrin** [comment]
@droyad you are mistaken. I am using it on Linux.

**Comment by droyad** [comment]
@kspearrin I had to cast my mind back to what went wrong.. It was an API that was not supported under netstandard2.0 (preview) but was part of NetFX. It'd probably be fine with DbUp

**Comment by empitegayan** [comment]
why this issue?

> Install-Package : Package dbup-mysql 4.0.0-beta0002 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package dbup-mysql 4.0.0-beta0002 supports: net35 (.NETFramework,Version=v3.5)
> At line:1 char:1
> + Install-Package dbup-mysql -Version 4.0.0-beta0002
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by droyad** [comment]
Since `4.0.0-beta0003` the `dbup-mysql` package targets `netstandard1.3` and `netstandard2.0`

**Comment by JonPSmith** [comment]
Can I ask - what is the likely timescale for a full release of DbUp 4.0?

**Comment by droyad** [comment]
@JonPSmith A few weeks is my best guess. There are still a handfull of issues (https://github.com/DbUp/DbUp/issues?q=is%3Aopen+is%3Aissue+milestone%3A4.0.0) that need to be addressed
