### ISSUE TITLE
Help test v4 branch

### ISSUE THREAD

**Issue by JakeGinnivan** [DbUp/DbUp#176]
Hey all

The v4 branch pulls sql server out of core and moves a bunch of things around, there will be some breaking API's and a few more features coming but I want to make sure nothing is broken now before making further changes. If something is broken I will try to figure out how we can make the tests better to catch it.

If you are using DbUp please give v4 a spin and post how it went with your database. We need confirmation that the following databases still work:
- [ ] Firebird
- [ ] MySql
- [ ] Postgresql
- [ ] SQLite.Mono
- [ ] SQLite
- [ ] Sql Server
- [ ] Sqlite

**Comment by sklose** [comment]
Can you publish a v4 pre-release package on NuGet? That should make it much easier for people to play around with it. I can do some testing for Sql Server on Windows/Linux with full CLR, CoreCLR and mono.

**Comment by JakeGinnivan** [comment]
I would prefer to not publish until I have a bit more confidence. You can download the packages at https://ci.appveyor.com/project/DbUp/dbup/build/4.0.0-beta.1+17.build.131/artifacts - you can create a local folder as a nuget feed.

CoreCLR work has not been started. I just want to know the refactorings which have happened so far in the v4 branch have not broken things.

**Comment by chriswithpants** [comment]
I'll do some testing for MySQL since I find myself with the dubious pleasure of living in that land at the moment.

**Comment by tekavec** [comment]
I'm evaluating dbup4-sqlserver 4.0.0-beta0003 with .NETCoreApp 1.1 / MS SQL Server 2016 based app and it looks very promising so far:
- EnsureDatabase.For.SqlDatabase - OK
- creating new schema - OK
- creating tables - OK
- creating stored procedures - OK
- inserting data into tables -OK

If there's anything I can give you a hand to accelerate v4 launch, pls let me know. Thumbs up for an excellent migration library!

**Comment by clausjensen** [comment]
How far along is the support for using dbup-postgresql in .NET Core?

Unlike dbup-sqlserver/dbup-sqlite, the current build of postgresql and the rest of them on coreclr-betas myget is not built for .NET Standard - only .NET Framework.

Great work on the MSSQL provider though - it works great for me so far :)

**Comment by empitegayan** [comment]
what about mysql provider?

**Comment by droyad** [comment]
@empitegayan @clausjensen MySql now supports .NET Core
