### ISSUE TITLE
Script ordering not using natural sorting

### ISSUE THREAD

**Issue by i-love-to-code** [DbUp/DbUp#180]
After integrating DbUp into our deployment process, we just noticed a case where scripts have been run out of order. E.g. our SchemaVersions table shows:
- Our.Namespace.Scripts.100. Some interesting script name here.sql
- Our.Namespace.Scripts.89. This script should appear after 100.sql

Looking at the source, the [EmbeddedScriptsProvider](https://github.com/DbUp/DbUp/blob/master/src/DbUp/ScriptProviders/EmbeddedScriptsProvider.cs) is using `OrderBy(sqlScript => sqlScript.Name)` which won't apply natural sorting.

The other providers don't appear to do any sorting, so probably rely on the ordering provided by the file system. Is there going to be a conflict of licensing if I add support for natural sorting using Dave Koelle's implementation, [AlphanumComparator.cs](http://www.davekoelle.com/files/AlphanumComparator.cs)?

**Comment by omnibs** [comment]
AlphanumComparator has [LGPL licensing](https://tldrlegal.com/license/gnu-lesser-general-public-license-v3-(lgpl-3)). 

The only conflict I spot is sublicensing, which is permitted in the [license.txt](https://github.com/DbUp/DbUp/blob/master/license.txt), and denied by LGPL.

**Comment by i-love-to-code** [comment]
Hot damn. Thanks for that. Looks like I need to do some work this weekend!

I can understand allowing the sorting order to be provided by the file
system. Do you see any need for this to be overridden, or we should always
apply natural sorting to the script names?

**Comment by omnibs** [comment]
Wait, maybe @JakeGinnivan is okay with adopting LGPL, let's get his input on this. I'm not sure what doom this could bring and if it would prevent us from borrowing code form less restrictive licenses (my guess is if foreign code's license allows sublicensing we'd be OK with being LGPL).

The sorting order on the `EmbeddedScriptsProvider` is a problem though. I've looked at Visual Studio and it does follow the same broken order that caused your .100 script to run before .89. 

![](http://julianobs.co/screencloud/16-03-11_08-43-36.png)

So it could be argued that for embedded scripts it's the predictable sorting order, at least if you're coding in Visual Studio, which is not bound to be the rule from now on (I hope) with DNX and everything.

So we could say "meh let's follow the filesystem ordering", but what's the filesystem's sort order? Is it Windows Explorer's sort order?

![](http://julianobs.co/screencloud/16-03-11_08-49-20.png)

Or is it `dir` or `ls`'s sort order?

![](http://julianobs.co/screencloud/16-03-11_08-47-28.png)

The thing is not consistent at all haha.

I guess we should adopt a consistent and explicit sort order across all providers, I'm not sure which though.

**Comment by dazinator** [comment]
We have always assumed this problem from the get go, and so we padded our
script names with additional digits accordingly.

```
Script.0001
Script.0002
Script.0003
...
Script.0010

```

Etc. Seems to work fine for us.

Probaby doesn't help you to know this late in the game, if you are mid way
through releases and have populated schema versions tables you can't really
change script names without some sort of fix up script.

**Comment by dazinator** [comment]
Also, pretty sure you can wrap the embedded provider with your own that sorts the results however you like prior to returning them. Doing it that way means you could use the LGPL licenced code in your custom provider, and Dbup can remain ignorant.

**Comment by i-love-to-code** [comment]
@dazinator That's very true, I had completely overlooked the 'WithScripts' overload that takes an IScriptProvider. I'll give that a whirl. Thanks!

Going forwards, there's definitely some room for improvement here. Either adding a SortedScriptsProvider, or adding an argument that allows files to be sorted. Given that we're dealing with ordered scripts here, I can't really think of a situation where you don't want it in the right order...
