### ISSUE TITLE
Add schema support for Postgresql

### ISSUE THREAD

**Issue by phillip-haydon** [DbUp/DbUp#197]
I'm trying to run DbUp from powershell, with SQL Server it works fine using the example, but with PostgreSQL it's messy.

```
Add-Type -Path (Join-Path -Path $currentPath -ChildPath '.\DbUp\DbUp.dll')
Add-Type -Path (Join-Path -Path $currentPath -ChildPath '.\DbUp\Npgsql.dll')
Add-Type -Path (Join-Path -Path $currentPath -ChildPath '.\DbUp\DbUp.Postgresql.dll')

$dbUp = [DbUp.DeployChanges]::To
$dbUp = [PostgresqlExtensions]::PostgresqlDatabase($dbUp, "....")
```

When running with this, it throws out:

```
Upgrade failed due to an unexpected exception:
System.IO.FileNotFoundException: Could not load file or assembly 'Npgsql, Version=2.2.1.0, Culture=neutral, PublicKeyTok
en=5d8b90d52f46fda7' or one of its dependencies. The system cannot find the file specified.
File name: 'Npgsql, Version=2.2.1.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7'
   at DbUp.Postgresql.PostgresqlConnectionManager.<>c__DisplayClass0_0.<.ctor>b__0(IUpgradeLog l)
   at DbUp.Engine.Transactions.DelegateConnectionFactory.<>c__DisplayClass1_0.<.ctor>b__0(IUpgradeLog l, DatabaseConnect
ionManager _)
   at DbUp.Engine.Transactions.DelegateConnectionFactory.CreateConnection(IUpgradeLog upgradeLog, DatabaseConnectionMana
```

(not sure its possible to setup a redirect in powershell without a config file?!?

Also:

```
$dbUp = [SqlServerExtensions]::JournalToSqlTable($dbUp, 'maintenance', 'deployed_scripts')
```

There's no equiv to Journal to SQL Table?

**Comment by phillip-haydon** [comment]
Ah it looks like the support for specifying a schema/table is not supported with postgresql. 

Can I send a PR for that?

**Comment by JakeGinnivan** [comment]
Yeah that would be great, it will likely be released as 4.0.0 beta though, that ok?

**Comment by phillip-haydon** [comment]
No problem at all, got DbUp running into the public schema for now, but I'll send the PR so I can move that in the future. 

:heart:

**Comment by ArinaKorshunova** [comment]
Hi, I have the same problem with PostgresqlExtensions. Could you tell how did you solve the problem, please? If you solved it

**Comment by droyad** [comment]
Workaround: https://github.com/DbUp/DbUp/issues/225#issuecomment-351069464

**Comment by droyad** [comment]
It's probably a matter of passing a schema in at the two lines https://github.com/DbUp/DbUp/blob/2c4203d9ada17081d234bb1fecbf3663883db329/src/dbup-postgresql/PostgresqlExtensions.cs#L41
