### ISSUE TITLE
Replace IUpgradeLog with LibLog

### ISSUE THREAD

**Issue by dennisroche** [DbUp/DbUp#203]
Using Liblog for a library is preferred for a library and it would allow you to remove far amount of code, e.g. IUpgradeLog and the various extension methods.

Would this be a breaking change?

**Comment by JakeGinnivan** [comment]
Yeah it would be a breaking change. But we have a v4 in the works so could roll it into that

**Comment by dennisroche** [comment]
I'm happy to create a PR for v4. Also intending on writing a blog post on DbUp with #dotnetcore.

**Comment by JakeGinnivan** [comment]
The work in progress for dotnetcore is at https://github.com/DbUp/DbUp/tree/netcore

**Comment by dennisroche** [comment]
Hmm. LibLog does not support .NET 3.5. :-1:

**Comment by JakeGinnivan** [comment]
I don't see any real reason to drop .net 3.5 support. Why can't liblog work on .net 3.5?

**Comment by dennisroche** [comment]
It might work if we include LibLog as a source file and not as a dependency.

**Comment by dennisroche** [comment]
`LibLog` uses `dynamic` keyword, which isn't supported in .NET 3.5.
