### ISSUE TITLE
Ability to always execute certain scripts?

### ISSUE THREAD

**Issue by Dahdread** [DbUp/DbUp#206]
Hi guys,

I have been using DbUp from close to two years now and firstly, I would like to thank you for sharing it. It is a great simple tool that just gets the job done. Works perfectly with Octo as well.

I have the following question - can I currently get DbUp to execute a script but "not remember" that i has done so - in other words, always execute it when performing a migration? 

What I am trying to achieve is to keep all the SP/Functions in a single (individual) file so that it is easier to track history/changes and also make merging a little easier. My main motivation is the ability to track changes - SPs can get big and complex especially if they have undergone several cycles of performance improvements. Even small changes are not as easy to spot/track down. 
I read [this blog post](http://www.codeofhonor.com/blog/a-better-way-to-update-sql-stored-procedures ) and if it is to be trusted, performance during upgrades will not suffer too much if you recreate just a hundred or so SPs upon migration.

There are probably other uses as well - I noticed somebody asked in another issue about ability to include the application version as metadata. This would allow them to do that easily.

And before somebody suggests - why not simply run the scripts? I want to be able to use all the goodies that come with DbUp - variables, transactions and so on.

If this functionality is not available, would you mind if I add it myself? Or if you have any feedback or a better idea - it is always welcome.

Best Regards,
Stefan

**Comment by dazinator** [comment]
From memory, think you can use the `NullJournal` you can use. Basically run dbup twice, however there should be a fluent api method for using a particular journal, call that and use the null journal when executing the scripts you always want to run.

**Comment by dazinator** [comment]
From memory, think you can run dbup twice, and use the `NullJournal` when you dont want it to "remember" executing any scripts. Failing that you can implement your own IJournal that has your logic for not returning the script name you always want to execute and then you should be able yo keep a single run of dbup.

**Comment by AdrianJSClark** [comment]
@dazinator is correct. The Null Journal (using `.JournalTo(new NullJournal())` in your configuration) is the simplest way to run scripts every time.

Here's a quick example:

```csharp
var schemaUpgrader =
    DeployChanges.To
        .SqlDatabase(connectionString)
        .WithScriptsEmbeddedInAssembly(typeof (Program).Assembly, s => IsSchemaScriptName(s))
        .WithTransaction()
        .LogToConsole()
        .Build()

var schemaResult = schemaUpgrader.PerformUpgrade();

var storedProcUpgrader =
    DeployChanges.To
        .SqlDatabase(connectionString)
        .WithScriptsEmbeddedInAssembly(typeof (Program).Assembly, s => IsStoredProcScriptName(s))
        .JournalTo(new NullJournal())
        .WithTransaction()
        .LogToConsole()
        .Build()

var storedProcResult = storedProcUpgrader.PerformUpgrade();
```

**Comment by Dahdread** [comment]
Great! Thanks a lot for the help, guys!

PS : It seems that I have actually used the null journal to run DB re-creation scripts when needed (using console param so that tests start with a clean DB). Looks like I was smart enough to figure out how to do it two years ago...
