### ISSUE TITLE
System.Data using .NET Core

### ISSUE THREAD

**Issue by skjohansen** [DbUp/DbUp#208]
I try to add DBUp v. 4 to a .NET Core project.
When running `dotnet restore` do I get the following error: 

> Unable to resolve 'System.Data (>= 2.0.0)' for '.NETCoreApp,Version=v1.0'.

My project.json looks like this:
```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable",
    "emitEntryPoint": true
  },
  "dependencies": {
    "dbup": "4.0.0-beta0001",
    "dbup-sqlserver": "4.0.0-beta0001"
  },
  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.0"
        }
      },
      "imports": "dnxcore50"
    }
  }
}
```
Any hints to how I get around this problem?

**Comment by dazinator** [comment]
Would probably have to check with someone in the know but my first guess would be that the v4 release may not be compatible with asp net core. There is a branch for asp net core support but im not sure if packages from that branch have been released.

**Comment by skjohansen** [comment]
@dazinator  It seems that you are right about v4 not being compatible with .net core. Thanks!

I have now instead cloned the branch "netcore" and included that into my project, and it seems to work without any further problems.

**Comment by vihorlat** [comment]
Hi @skjohansen, where did you find this "netcore" branch that you cloned, please? There are just 6 branches in this repo currently without the "netcore".
Thank you
