### ISSUE TITLE
Why does WithScriptsAndCodeEmbeddedInAssembly not filter IScript files?

### ISSUE THREAD

**Issue by robvanuden** [DbUp/DbUp#213]
I am using the following extension method:
public static UpgradeEngineBuilder WithScriptsAndCodeEmbeddedInAssembly(this UpgradeEngineBuilder builder, Assembly assembly, Func<string, bool> filter);

But there is a comment:
filter:
    //     The Sql Script filter (only affects embdeeded scripts, does not filter IScript
    //     files). Don't forget to ignore any non- .SQL files.

Why is that? I can't think up a reason for it, but maybe I forget something. I would be happy to filter the IScript files. Is there a supposed way to do this, or is this simply not implemented yet?

**Comment by robvanuden** [comment]
I fixed my issue for now with a custom ScriptProvider, based on EmbeddedScriptAndCodeProvider.

Differences:
- In the constructor it saves the filter
- In the GetScripts method it applies the filter

**Comment by JakeGinnivan** [comment]
We are putting together v4 right now. If you wanted to submit a PR updating the `EmbeddedScriptAndCodeProvider` that would be great!

**Comment by robvanuden** [comment]
Is it a problem if it's a breaking change relative to v3?
In other words, should I make a different class or can I just change the behavior of the current one?

**Comment by JakeGinnivan** [comment]
It can be a breaking change, it just needs to be documented. We have a few other small breaking changes in there (mainly API though)

**Comment by JakeGinnivan** [comment]
This seems like it is fixing a bug though

**Comment by robvanuden** [comment]
Yeah I consider it a bug too, but maybe some people trust on this bug nowadays ;-)
I will create a PR tonight, with the breaking change (/bugfix) documented in Breaking changes.md

**Comment by robvanuden** [comment]
I created a pull request for this. Please let me know what you think about it.
