### ISSUE TITLE
3.3.5 Release Notes

### ISSUE THREAD

**Issue by MattRyan** [DbUp/DbUp#216]
I cannot find any [release notes](https://github.com/DbUp/DbUp/releases) for version 3.3.5 uploaded to NuGet on August 5th. Can someone point me to them or are they forthcoming?

**Comment by JakeGinnivan** [comment]
Thanks, have fixed this

https://github.com/DbUp/DbUp/releases/tag/3.3.5

Am now automating the process so this won't happen again
