### ISSUE TITLE
Add support for dropping a database

### ISSUE THREAD

**Issue by dennisroche** [DbUp/DbUp#220]
In our local and development environment, we want to be able to drop the database before running the migration scripts as, for various reasons, we cannot simply roll forward. 

DbUp already has support for ensure database exists. I suggest that we have an equivalent for drop.

I think this has been raised in the past as part of another discussion (can't find the issue atm).

**Comment by hossambarakat** [comment]
I think this could be useful for integration tests as well where you want to drop and recreate the database before the tests
