### ISSUE TITLE
Support for Oracle Database

### ISSUE THREAD

**Issue by vengi83644** [DbUp/DbUp#224]

**Comment by pizycki** [comment]
there is this PR https://github.com/DbUp/DbUp/pull/228

**Comment by thebrianlopez** [comment]
Any updates on this? Would be awesome to get this feature into this wonderful tool ! 

Thanks for all of your efforts on this!

**Comment by droyad** [comment]
Closed via #326 (thanks @treesrc)

**Comment by droyad** [comment]
I've pushed up the oracle package as a preview: https://www.nuget.org/packages/dbup-oracle

Please let me know if you have success with it

**Comment by wazbekker** [comment]
I tried testing the oracle package connecting to an Oracle 11g database and I am getting the following error:

Declaration referenced in a method implementation cannot be a final method.  Type: 'DbUp.Oracle.OracleTableJournal'.  Assembly: 'dbup-oracle, Version=4.0.1.0, Culture=neutral, PublicKeyToken=null'.

StackTrace:
   at DbUp.Oracle.OracleExtensions.<>c__DisplayClass4_0.<OracleDatabase>b__2(UpgradeConfiguration c)
   at DbUp.Builder.UpgradeEngineBuilder.Build()

**Comment by droyad** [comment]
@wazbekker, did you reference the same version of the dbup-core package? It might be picking up the 4.0.1 release which doesnt have the right changes

**Comment by wazbekker** [comment]
@droyad, sorry my bad.  I changed my dbup-core version to 4.0.1-oraclesupport0001 and my tests were successful.

**Comment by treesrc** [comment]
@droyad, I have tested the nuget package using visual studio 2015, framework 4.5 app and using visual studio 2017 core app. So far no issues.

**Comment by droyad** [comment]
Awsome, thanks @wazbekker @treesrc , I've merged and it should be out as 4.1.0 shortly

**Comment by steflege** [comment]
Great solution thanks.

A simple query in an sql script file run well.

Just have some problems with my create or replace package scripts(utf8 with bom). 

It always returns :
----
Spec	1	71	PLS-00103: Symbole "end-of-file" rencontré à la place d'un des symboles suivants :
   . @ % ; is authid as cluster order using external character
   deterministic parallel_enable pipelined aggregate
   result_cache accessible
---
 There is the script:
CREATE OR REPLACE PACKAGE PCK1 AS

FUNCTION Test(p_param IN VARCHAR2) RETURN VARCHAR2;

END;
/

When I look at the generated Package (with errors) the source looks like :
CREATE OR REPLACE PACKAGE PCK1 AS  FUNCTION Test(p_param IN VARCHAR2) RETURN VARCHAR2
/
 
It seems to stop where the first ';' character was found in the original script.

Is it normal?

**Comment by treesrc** [comment]
; (semicolon) is used as a delimiter so I think it is not possible.

**Comment by steflege** [comment]
Thank you for your fast answer.

Unfortunatly, it would be hardly feasible to transform our oracle packages (from 100 to 800 lines) in c# class. Almost all of our scripts are packages replacement(+/- 200 packages per year) or Oracle objects upgrading scripts containing many semicolons. 

There most be an other solution.

**Comment by AdrianJSClark** [comment]
Moved the additional discussion here to it's own issue at #334. While Oracle related, it is a separate problem to overall Oracle Database support.

**Comment by dFarkhod** [comment]
Hi, am I missing something?
I've the DbUp Oracle nuget package installed
```
<PackageReference Include="dbup-core" Version="5.0.87" />
<PackageReference Include="dbup-mysql" Version="5.0.44" />
<PackageReference Include="dbup-oracle" Version="5.0.40" />
<PackageReference Include="dbup-postgresql" Version="5.0.40" />
<PackageReference Include="dbup-sqlserver" Version="5.0.41" />
```
but there is no Ensure.For.OracleDatabase option.

![image](https://github.com/user-attachments/assets/2a8f9d50-9e17-495e-962e-55f5d85de0b1)
I want to make sure that DbUp created the given database in Oracle too.
How to proceed?

**Comment by droyad** [comment]
@dFarkhod It looks like those functions were never created. 

If you are able, a PR to the `dbup-oracle` project to add them would be appreciated.

Here are two examples of it being added for other providers :
- https://github.com/DbUp/dbup-firebird/pull/9/files
- https://github.com/DbUp/DbUp/pull/454/files

**Comment by shanerogers** [comment]
Is there any update on this? I also need this. @droyad did you end up creating a PR?
