### ISSUE TITLE
Question: How does it know what scripts were already run?

### ISSUE THREAD

**Issue by DotNetRockStar** [DbUp/DbUp#226]
Hi there -
I have been going through your documentation and I have to say that I am a fan of the project.  I was trying to find out how DbUp keeps track of which scripts were run so that it knows to not run them again.  I'm in need of an easy and elegant way to manage SQL changes across multiple teams across multiple databases so I need to understand where the state of "what has already been run" is being persisted.

If I missed this answer on some documentation out there please feel free to just point me to it.

Thanks in advance.
- Jerrod

**Comment by billydavis** [comment]
It creates a table to log the scripts that have been executed. The default table name for SqlServer is SchemaVersions.  You can look for SqlServerExtensions.cs and see where that is set. Other supported database may use a different name for the table, but those are typically set in their extensions as well.

**Comment by DotNetRockStar** [comment]
Perfect. Thanks for the quick and very clear response.
