### ISSUE TITLE
Upgrade Failed: Input string was not in a correct format.

### ISSUE THREAD

**Issue by DotNetRockStar** [DbUp/DbUp#227]
I keep getting this error but I am having trouble tracking down exactly where/what this is pointing at exactly.  Any ideas why this would be thrown and how I might be able to identify the script that is causing the issue?

Upgrade failed due to an unexpected exception: System.FormatException: Input string was not in a correct format.    at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)    at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)    at System.String.Format(IFormatProvider provider, String format, Object[] args)    at System.IO.TextWriter.WriteLine(String format, Object[] arg)    at System.IO.TextWriter.SyncTextWriter.WriteLine(String format, Object[] arg)    at System.Console.WriteLine(String format, Object[] arg)    at DbUp.Engine.Output.ConsoleUpgradeLog.Write(ConsoleColor color, String format, Object[] args) in C:\projects\dbup\src\DbUp\Engine\Output\ConsoleUpgradeLog.cs:line 43    at DbUp.Engine.Output.ConsoleUpgradeLog.WriteError(String format, Object[] args) in C:\projects\dbup\src\DbUp\Engine\Output\ConsoleUpgradeLog.cs:line 27    at DbUp.Support.SqlServer.SqlScriptExecutor.Execute(SqlScript script, IDictionary`2 variables) in C:\projects\dbup\src\DbUp\Support\SqlServer\SqlScriptExecutor.cs:line 135    at DbUp.Engine.UpgradeEngine.PerformUpgrade() in C:\projects\dbup\src\DbUp\Engine\UpgradeEngine.cs:line 71

**Comment by droyad** [comment]
Fixed with the above PR, thanks for submitting.
