### ISSUE TITLE
Consolidated ExecutedScripts table/database

### ISSUE THREAD

**Issue by juanonsoftware** [DbUp/DbUp#236]
Hi,

I'd like to setup a new database something called DeploymentHistoric which will store all executed scripts instead of having a table in each database.

I know that a new implementation of IJournal should be done but it is failing - must initialise transaction factory (how?); and is it possible to have benefit from transaction mode ?

Tks.

**Comment by droyad** [comment]
Have a look at [this implementation](https://github.com/DbUp/DbUp/blob/master/src/DbUp/Support/SqlServer/SqlTableJournal.cs#L16) of `IJournal`.

From your description it is unclear what problem you encountered.
