### ISSUE TITLE
SchemaVersions table shouldn't use Identity column

### ISSUE THREAD

**Issue by davidarcher** [DbUp/DbUp#237]
The schema versions table shouldn't use an int identity column as this introduces additional complexities in replication scenarios. Since the table is generally relatively small, I suggest using a GUID generated by DbUp for the primary key as the default behavior.

**Comment by gavincampbell** [comment]
Look at https://github.com/DbUp/DbUp/blob/master/src/DbUp/Support/SqlServer/SqlTableJournal.cs. The identity column is written to, but as far as I can tell is never read; the code just reads a list of script names from the journal table.

**Comment by emersonmellado** [comment]
Hey @davidarcher are you having issues with replication?
