### ISSUE TITLE
Firebird constantly trying to create SchemaVersions table

### ISSUE THREAD

**Issue by Brett-Gladman** [DbUp/DbUp#248]
When using DeployChanges with the Firebird database, I've found that the engine attempts to create the SchemaVersions table after each script.
It appears that it always fails to find SchemaVersions as an existing table.

I tracked down the issue to the FirebirdTableJournal within the VerifyTableExistsCommand method.

It is currently using :

"select 1 from RDB$RELATIONS where RDB$SYSTEM_FLAG = 0 and RDB$RELATION_NAME = '{0}'" 

to determine the existence of a table.

Firebird 3 (and I suspect 2.5) force RDB$RELATIONS.RDB$RELATION_NAME to uppercase, so a lower case tableName passed through always fails.

I found this change to work:

"SELECT DISTINCT 1 FROM RDB$RELATIONS WHERE RDB$SYSTEM_FLAG = 0 AND UPPER(RDB$RELATION_NAME) = UPPER('{0}')"

**Comment by Timothyoverton** [comment]
I found the same fix, has a pull request been made/merged for this change?

**Comment by Timothyoverton** [comment]
Here is my pull request for the fix: https://github.com/DbUp/DbUp/pull/250

**Comment by Brett-Gladman** [comment]
Tim,
  I was evaluating DbUp as a possible addition to an existing project, so wasn't really looking to fix anything, just reporting an encountered issue. Rather than change the code above, I found it easier just to call JournalToFirebirdTable("SCHEMAVERSION") off DeployChanges, which passed through the required uppercase version every time.

**Comment by Timothyoverton** [comment]
Hey Brett, thanks for the alternate solution - I'll try the same, cheers!
