### ISSUE TITLE
init.ps1 tries to remove unexisting module 'VSExtensions' (probably due to copy-paste)

### ISSUE THREAD

**Issue by SashaPshenychniy** [DbUp/DbUp#251]
It's very strange that nobody has fixed it or noticed yet, but I coudn't reinstall DbUp package due to an error:
```
Remove-Module : No modules were removed. Verify that the specification of modules to remove is correct and those modules exist i
n the runspace.
At C:\Projects\Coop\wallet2\src\packages\dbup.3.3.5\tools\init.ps1:5 char:5
+     Remove-Module 'VSExtensionsModule'
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Remove-Module], InvalidOperationException
    + FullyQualifiedErrorId : Modules_NoModulesRemoved,Microsoft.PowerShell.Commands.RemoveModuleCommand
```
I looked inside init.ps1 and found the following loop which causes a problem:
```
foreach ($_ in Get-Module | ?{$_.Name -eq 'DbUp'})
{
    Remove-Module 'VsExtensionsModule'
}
```

The logic of removing "VsExtensionsModule" when we found module "DbUp" is strange and must be a bug. I tried to google "VsExtensionsModule" and [only 1 link appear on the web](http://blog.thomaslebrun.net/2014/03/nuget-powershell-how-to-add-custom-commands-to-the-powershell-console/#.WRB1KV-GNpg) where VsExtensionsModule is the one which should have been removed as example. Code is identical to what you have in the init.ps1 with obvious bug in your code.

I tried to just replace "VsExtensionsModule" with "DbUp" in your script - and everything worked fine. It would be nice if it is fixed for everyone.

**Comment by AdrianJSClark** [comment]
Thanks for the report @SashaPshenychniy.

**Comment by sungam3r** [comment]
I don't see `init.ps1` in the repo, closing.
