### ISSUE TITLE
SQL Server - Executing against multiple databases in a single script...

### ISSUE THREAD

**Issue by natiki** [DbUp/DbUp#254]
Hi,

- DbUp 3.3.5

We have been using the library for some time now against SQL Server and it is working well. However we have come up against an issue where we can only execute TSQL against the database specified in the connection string supplied to 

```
DeployChanges.To.SqlDatabase(".....Catalog=DatabaseOne")
```

So in the case of the following T-SQL the call to EXEC [DatabaseTwo].[usp_SomeProc] @SomeParam
 fails. Is there a work around as this is rather a big show stopper?

```sql
USE [DatabaseOne]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[MyProc]
( 
    @SomeParam VARCHAR(30)
)
AS
BEGIN
   -- Do some stuff

   -- Do some stuff in a different DB
   EXEC [DatabaseTwo].[usp_SomeProc] @SomeParam
END
```

**Comment by AdrianJSClark** [comment]
Hi there,

There shouldn't be anything within DbUp that is preventing this as under the covers it just uses a standard `SqlCommand` to speak to SQL Server.

Without the exact error message that you are encountering there isn't much help I can give you either way.

Just from looking at your code I think you're missing the schema in your cross-database call. Your line should be `EXEC [DatabaseTwo]..[usp_SomeProc] @SomeParam` (note the two dots) or `EXEC [DatabaseTwo].[dbo].[usp_SomeProc] @SomeParam` (assuming "usp_SomeProc" in DatabaseTwo is within the "dbo" schema).

**Comment by natiki** [comment]
Hey Adrian,

Thanks for getting back to me.

Seems we have an issue on our end. I did some independent testing (instead of taking the word of one of my colleagues :-|) and I cannot replicate any issue either. Apologies for the noise.

**Comment by AdrianJSClark** [comment]
No worries, @natiki. Hope you get the situation sorted.
