### ISSUE TITLE
.net core support

### ISSUE THREAD

**Issue by zuologio** [DbUp/DbUp#256]
During nuget package installation I've got these errors: 

- Package dbup-sqlserver-scripting 1.3.0 is not compatible with netcoreapp1.1 
- Package dbup 3.2.1 is not compatible with netcoreapp1.1
- Package Unofficial.Microsoft.SQLServer.SMO.2014 12.0.2000.8 is not compatible with netcoreapp1.1

DbUp is amazing! Is there any plan to support .net core in the near future?

**Comment by AdrianJSClark** [comment]
There is some support in the 4.0 release. There's some discussion of the .Net Core support specifically in #174 and if you have comments on the 4.0 release itself add some comments to #176.

**Comment by kspearrin** [comment]
Hey guys,
Some good news! I just tried DbUp in a .NET Core 2.0 project and it works just fine. This is due to the library shimming that .NET Core 2.0 does to make old libraries compatible.

In addition to adding `DbUp` library to your project, you just need to add `System.Data.SqlClient` (4.4.0) from nuget as well.

I haven't tested everything, but here's the code/features I am using successfully:

```
var upgrader = DeployChanges.To
    .SqlDatabase(MY_CONNECTION_STRING)
    .JournalToSqlTable("dbo", "Migrations")
    .WithScriptsAndCodeEmbeddedInAssembly(
        Assembly.GetExecutingAssembly(),
        (string s) => s.Contains($".Scripts."))
    .WithTransactionPerScript()
    .LogToConsole()
    .WithExecutionTimeout(new TimeSpan(0, 0, 90))
    .Build();

var result = upgrader.PerformUpgrade();
```

👍

**Comment by MarcelChirtes** [comment]
dbup4-core 4.0.0-beta0003 on .net core 2.0 working, hooray!!!

**Comment by droyad** [comment]
We have published `4.0.0-beta0002` which supports `netstandard1.3` (and `netcoreapp1.0`). The `Dbup` package is obsolete, use `dbup-sqlserver` (MS SQL Server) or the package relevant to your database.

**Comment by jackjwilliams** [comment]
I noticed that the dbup-postgresql package only has a dependency on .NET Framework 3.5 (at least on the nuget page). Am I missing something?

**Comment by htxryan** [comment]
@jackjwilliams I am seeing this as well -- I'm getting build errors when using the dbup-postgresql package in a .NET core 2 project. Did you ever figure it out?

**Comment by droyad** [comment]
@htxryan I added an issue for that (#305)

**Comment by jackjwilliams** [comment]
No :(. It looks like this repo is dead or the author is not paying attention to PR's / PR comments. 

I pulled https://github.com/DbUp/DbUp/pull/280 down and tried to get it working to no avail. After no comment from an owner / member I gave up.

**Comment by htxryan** [comment]
@droyad great, thanks!

**Comment by droyad** [comment]
@jackjwilliams That's my intention, just got to get my head around the code base
