### ISSUE TITLE
Need to allow an undeclared variable in stored procedure without a value 

### ISSUE THREAD

**Issue by dlwade04** [DbUp/DbUp#259]
I am working with MariaDb, creating a stored procedure that has a dynamic query in it.  I need to have a user variable that is assigned a value at run time (when called from web app).  I have tried everything I can to figure out how to have the create stored procedure script run from DBUp but no go - it wants the variable defined and given a value.

Example:  https://mariadb.com/kb/en/mariadb/prepare-statement/

**Comment by AdrianJSClark** [comment]
DbUp executes scripts in a similar manner to the way you would execute scripts in a query tool. If the script works from the appropriate query tool for your database then it should work from DbUp.

It sounds from your issue text that you don't yet have a working script to create the stored procedure you are after. If this is the case, you'll probably find more specific advice on the [MariaDB Knowledgebase](https://mariadb.com/kb/en/+questions/) or the [StackOverflow 'mariadb' tag](https://stackoverflow.com/questions/tagged/mariadb).

Once you do have a script that works when executed manually if it is still failing with DbUp come back and let us know the error you are getting so we can examine why DbUp cannot execute it.

**Comment by dlwade04** [comment]
The script I have to do this runs fine from Toad against the MariaDb.  The problem is when I try to include the script in my project that uses DbUp to create the database.  The error message is that the undefined variable does not have a value.  Try the example code I included in my original write up - it doesn't work from DbUp.  It does not like the @SQL variable because it is not declared and does not have a value.  My guess is this would do the same thing no matter what database you run the below against but I can't say that for sure since I haven't tried it against other databases.

CREATE PROCEDURE `test_stmt`(IN sql_text TEXT)
BEGIN
        DECLARE EXIT HANDLER FOR SQLEXCEPTION
        BEGIN
                SELECT CONCAT(sql_text, ' is not valid');
        END;
        SET @SQL := sql_text;
        PREPARE stmt FROM @SQL;
        DEALLOCATE PREPARE stmt;
END;

**Comment by droyad** [comment]
Apologies for the really long delay. The `WithVariable` method is for the [variable substitution](https://dbup.readthedocs.io/en/latest/more-info/variable-substitution/) feature, not specifying SQL variables. 

You should add the line:
```
SET @Sql := '$MyVar$'
```
and
```
.WithVariable("MyVar", "Value")
