### ISSUE TITLE
How to handle data conversion when modifying a column?

### ISSUE THREAD

**Issue by hankl** [DbUp/DbUp#260]

**Comment by AdrianJSClark** [comment]
Hi @hankl,

DbUp is simply a tool to assist with executing scripts. You handle conversion of data in the normal way you would with any other change script for your database. Of course the details of how that is done depend both on the type of change being made and the features available to you from your chosen DB technology.

DbUp doesn't have features which perform individual column modifications directly.

I hope this clears things up for you.

**Comment by hankl** [comment]
Thanks for your comment. I got it now.

**Comment by AdrianJSClark** [comment]
@hankl No worries! Good luck with your project.
