### ISSUE TITLE
WithVariable not available

### ISSUE THREAD

**Issue by perp1exed** [DbUp/DbUp#264]
Hi,

The WithVariable is not a property of DeployChanges.To

It says the best extension method is WithVariable(UpgradeEngineBuilder, ... , ...).

This is not in the documentation - any advice?

thanks,

KS

**Comment by AdrianJSClark** [comment]
You need to first specify which database you are deploying to. This will be an extension method which represents one of the [supported databases](https://github.com/DbUp/DbUp/blob/master/docs/supported-databases.md). For example, SQL Server is covered by the `.SqlDatabase(...)` extension method.

After specifying your database you will be building your upgrade engine and the `WithVariable` extension method will be available. 

For example, if you are deploying to SQL Server you might build your upgrader like this:
```csharp
    var upgradeEngine = DeployChanges.To
        .SqlDatabase(connectionString)
        .WithScriptsEmbeddedInAssembly(Assembly.GetExecutingAssembly())
        .LogToConsole()
        .WithVariable("MyVar", "SomeValue")
        .Build();
```
