### ISSUE TITLE
DbUp SqlScript class not working if the name parameter starts with the word "Main"

### ISSUE THREAD

**Issue by GoldenArulRaj** [DbUp/DbUp#265]
Hi Team,
I am passing parameter values for DbUp.Engine.SqlScript(string name, string content) to run a script. If I pass value for name parameter which starts with the word "**main**" then the script is not executing. 
For example **DbUp.Engine.SqlScript("Main_Name", SqlText)**.
Please clarify and let me know as soon as possible.

Thanks,
Golden

**Comment by dazinator** [comment]
Are you able to produce a failing test for this? Just mentioning because then it would be quicker to pickup. We also welcome contributions if you find bugs, as DbUp is very much community maintained!

This test might be a good basis: https://github.com/DbUp/DbUp/blob/master/src/DbUp.Tests/Engine/UpgradeEngineTests.cs#L17

**Comment by GoldenArulRaj** [comment]
Hi, 
Thanks for the quick response. I identified that the name is maintained in the SchemaVersions table. So the same name is not allowed next time execution. Is there any way to avoid maintaining the  SchemaVersions table.

Thanks,
Golden

**Comment by AdrianJSClark** [comment]
Only executing each script once is one of the major features of DbUp. There is a way around the behaviour, though. You'll need to create your upgrader with a "[NullJournal](http://dbup.readthedocs.io/en/latest/more-info/journaling/#nulljournal)". That type of journal will not write to or read from anywhere so all scripts you execute will run every single time.

Obviously it is then up to you to ensure that the scripts are either idempotent or that you avoid running them multiple times. DbUp won't be able to tell.
