### ISSUE TITLE
[Feature] Including IScript instances

### ISSUE THREAD

**Issue by SaphuA** [DbUp/DbUp#266]
The only way to include an IScript instance I was able to find is by using the extension method `WithScriptsAndCodeEmbeddedInAssembly`. I needed a little more control and did not want to include the *CodeEmbedded* part, so I made my own provider. Perhaps this can be included in DbUp in some way?

```cs
internal class ScriptInstanceProvider : IScriptProvider
{
    private readonly IScript _script;

    /// <summary>
    /// Provider used to directly include an IScript instance during migrations
    /// </summary>
    /// <param name="script">The IScript instance to include</param>
    public ScriptInstanceProvider(IScript script)
    {
        _script = script ?? throw new ArgumentNullException(nameof(script));
    }

    public IEnumerable<SqlScript> GetScripts(IConnectionManager connectionManager)
    {
        return connectionManager.ExecuteCommandsWithManagedConnection(dbCommandFactory =>
            new SqlScript[] {
                new LazySqlScript(_script.GetType().FullName + ".cs", () => _script.ProvideScript(dbCommandFactory))
            }
        );
    }
}
```

It's really easy to use:

```cs
DeployChanges.To.SqlDatabase(connectionString)
    .WithScripts(new ScriptInstanceProvider(new MyScript()))
    .Build()
    .PerformUpgrade();
```

**Comment by droyad** [comment]
Good idea, I'll include it. It should also accept a list of items and allow customisation of the naming.

**Comment by SaphuA** [comment]
Hey I just tried migrating our code to 4.x and wanted to let you know that you made the class `internal` so we're unable to use it. 

https://github.com/DbUp/DbUp/commit/ebde28c911364bb35de3975481f35fadd8ba113f#diff-5059621b6e871cc29022f8a2e8f693cbR9

Or am I missing something?
