### ISSUE TITLE
Unable to execute script with comments in CREATE TRIGGER/PROCEDURE statement

### ISSUE THREAD

**Issue by wouterroos** [DbUp/DbUp#285]
I'm working to make the database of the project I'm currently working on manageable using a combination of SQL Server Database Projects and DbUp in Visual Studio and I'm running into the issue that DbUp is somehow unable to execute the script which should set up my database. Whenever DbUp executes a `CREATE TRIGGER`/`PROCEDURE` statement which has comments inside it I get the following `SqlException`: 

```
SqlException: Must declare the scalar variable "@lLogin".
Must declare the scalar variable "@lObject".
Must declare the scalar variable "@lDB".
Must declare the scalar variable "@lTrail".
Must declare the scalar variable "@lBypass".
Must declare the scalar variable "@lObject".
```

If I run this script in SSMS it works fine, but when it's run by DbUp it causes the `SqlException` mentioned earlier. The snippet below reproduces the issue in a simple manner.

```sql
CREATE TABLE [dbo].[Announcement]
([Id]       INT IDENTITY(1, 1) NOT NULL,
 [Page]     NVARCHAR(20) NOT NULL,
 [Message]  NVARCHAR(1000) NULL,
 [Modified] DATETIME NOT NULL,
 [Tms]      ROWVERSION NOT NULL,
 CONSTRAINT [PK_Announcement] PRIMARY KEY CLUSTERED([Id] ASC)
 WITH(FILLFACTOR = 90)
);
GO

CREATE TRIGGER dbo.[tgAnnouncement_I] ON dbo.[Announcement]
FOR INSERT
AS
     BEGIN
--  --------------------------------------------------------------------------------------
--  Section 1   Parameters
--  --------------------------------------------------------------------------------------
--  Part 1.1    Declare standard parameters
         DECLARE @lError INTEGER;
         DECLARE @lRow INTEGER;
         DECLARE @lLogin VARCHAR(128);
         DECLARE @lDB VARCHAR(128);
         DECLARE @lObject VARCHAR(128);
         DECLARE @lDesc VARCHAR(255);
         DECLARE @lTrail CHAR(1);
         DECLARE @lBypass CHAR(1);

--  Part 1.2    Assign value to standard parameters
         SELECT @lLogin = system_user;
         SELECT @lObject = 'tgAnnouncement_I';
         SELECT @lDB = DB_NAME();
         SELECT @lTrail = 'N';
         SELECT @lBypass = 'N';
         SELECT @lDesc = @lObject;
     END;
GO
```

**Comment by dazinator** [comment]
So does removing the comments then work? Does using */ style comment block work? Just wondering if it is -- style comments causing the problem?

**Comment by wouterroos** [comment]
@dazinator Removing the comments or replacing them with `*/` works, but ideally I don't want to do that since they contains a lot of (old) information and are structured according company standards.

**Comment by dazinator** [comment]
@wouterroos - Sure, just trying to narrow down where the problem might be.

We do have a test case for splitting scripts on `GO` and where the scripts contain comments (both dash dash and slash star)

Is there any chance you could add a test to replicate your problem to the test cses here: https://github.com/DbUp/DbUp/blob/master/src/DbUp.Tests/Support/SqlServer/SqlCommandSplitterTests.cs 

The existing test `should_split_statements_on_go_and_handle_comments` is probably the closest one to covering your issue.

Or if you don't have time to add a test to replicate this, perhaps attach a problematic t-sql script file to a gist and link to it from this issue. I know you have pasted in the T-SQL above, but it might be that he actual script file that DbUp is reading may have characters in that are not preserved when you have copied the contents into this github issue editor. So best to have an actual file if we want to replicate.

One last suggestion - can you check that there is definately a `/n` char at the end of the line for your dash dash comments? The SqlParser will read a  dash dash comment up until it encounters a `/n` character denoting the end of the line or up until the end of the file if it doesn't encounter a `/n` char.

**Comment by wouterroos** [comment]
@dazinator https://gist.github.com/wouterroos/f6d54651b04322a6e8de8032fb63388e see this gist for the exact script that causes the issue.

**Comment by wouterroos** [comment]
@dazinator Any update on this yet? Thanks.

**Comment by dazinator** [comment]
@wouterroos - nope sorry, I don't have time to work on DbUp anymore, so I won't be looking at this for you anytime soon. Perhaps someone else will be able to help.
