### ISSUE TITLE
DbUp ignores sql script with inserts

### ISSUE THREAD

**Issue by shony83** [DbUp/DbUp#287]
Hi, 
I tried to find answer on forum and stackoverflow also but I was not successfull. I started use DbUp for automated deploy db changes. I have 4 scripts in folder, each of them as EmbeddedResource
- 001-create-tables.sql
- 002-insert-initial-data.sql
- 003-stored-procedures.sql
- 004-functions.sql

Console app looks like this:

            var upgrader =
                DeployChanges.To
                    .SqlDatabase(connectionString)
                    .WithScriptsEmbeddedInAssembly(Assembly.GetExecutingAssembly())
                    .WithTransactionPerScript()
                    .LogToConsole()
                    .Build();

            var result = upgrader.PerformUpgrade();

all sql scripts have 
USE [DB-name]
GO
on start

In schema versions table I see that only files 1, 3 and 4 were executed, but script nr. 2 was skipped. And every next run tell me that "No new scripts need to be executed - completing".

Does any one knows what is wrong?
Thank you for answer

**Comment by dazinator** [comment]
Initial thoughts..

Perhaps script 2 is erroring? Areyou checking the upgrade result?

Are you sure its embedded in the assembly?

**Comment by droyad** [comment]
It is also not a good idea to have `USE [DB-name]` in your scripts

**Comment by shony83** [comment]
Hi, well, there is some progress. Script two is OK if I run it via MSSQL Management studio. I already removed USE [DB-name] from all scripts. No change, script two was still ignored. Script two was generated by our tool, but even if I set it as a embedded resource, it was ignored. 
Then I remove the file, create another one, set it as a embeded resource and put generated sql inserts  into it. Now DbUP tries to run this script, but it fails with message "variable 2y has no value defined" . Any advise?

**Comment by shony83** [comment]
Well now I know on what row it failes. I want to run in sql following insert
INSERT INTO dbo.[User] (Username,[Password],Name,Phone,Email,IsAdmin) VALUES ('xy','$2y$13$DdajIvD8An9/V7Om/NLMMeF88/2966nJ4p1.HjjijPkuahXc7Of4K','xy','','x@y.com',0)
but don't know why. In MSSQL it is ok. I also tried it with N'xxxx' for password but same result

**Comment by shony83** [comment]
Dazinator and Droyad, thanks for your answers. I close this issue, and for problem with my last comment I create separate one, becuase it is another issue. My problem with skipping file was that Embedded Resource was ignored on sql file what was automatically generated. When I created file manually, put sql inserts there, and set up as embedded resource, then it was ok.
