### ISSUE TITLE
Variable 2y has no value defined

### ISSUE THREAD

**Issue by shony83** [DbUp/DbUp#288]
Hi, 
I want to run in sql following insert

INSERT INTO dbo.[User] (Username,[Password],Name,Phone,Email,IsAdmin) VALUES ('xy','$2y$13$DdajIvD8An9/V7Om/NLMMeF88/2966nJ4p1.HjjijPkuahXc7Of4K','xy','','x@y.com',0)

but it fails. DbUP says that Upgrade failed due to an unexpected exception: System.InvalidOperationException: Variable 2y has no value defined.

When I run this insert in MSSQL management studio it is ok. I also tried it with N'xxxx' for password but same result.
Any advice?
Thank you

**Comment by AdrianJSClark** [comment]
This will be due to the dollar signs, which os the delimiter for the inbuilt variable substitution feature. If you are not using it you can disable it via configuration.

--
Adrian Clark

adrian@ayds.com.au<mailto:adrian@ayds.com.au> | @AdrianJSClark
________________________________

**Comment by dazinator** [comment]
Seems like there is an edge case here where some work might need to be done on the dbup side..

Scenario is where you are using variable substitution but you also happen to have some genuine data with '$foo$` syntax in the script.

Couple of options might be:

1. Allow the variable capture that dbup uses to be configurable i.e so you could use **foo** for variables or something else. Perhaps via providing a custom regex.
2. Provide an "IgnoreUnsubstitutedVariables" method in the configuration. This would just allow variables that dont have a value to remain as is. 

Not really sure about 2, think perhaps its too dangerous and also unnecessary if you have 1.

**Comment by AdrianJSClark** [comment]
Variable substitution can be disabled by calling `.WithVariablesDisabled()` when you build your configuration.

Please let us know if this solves your problem or not. I suggest it may not because the variable substitution process parses the SQL so it can ignore dollar signs within strings (as you have here) and SQL comments. Unless there is a bug in that parsing, my initial gut reaction above is likely wrong.

**Comment by shony83** [comment]
Hi guys, thanks for your help. I needed to store concrete string '$2y$13$DdajIvD8An9/V7Om/NLMMeF88/2966nJ4p1.HjjijPkuahXc7Of4K' into table column, so .WithVariablesDisabled() worked for me perfectly. 
Thank you, I close the issue.
