### ISSUE TITLE
SQL Server create user script variable substitution failing when pointing to dbup-sqlserver 4.0.0-beta0002

### ISSUE THREAD

**Issue by andwie** [DbUp/DbUp#293]
When we migrated our projects to use dbup-sqlserver 4.0.0-beta0002 variable substitution stopped working in our create user scripts.  Our scripts look like this:

```
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE USER [bob] WITH PASSWORD=N'$Password$', DEFAULT_SCHEMA=[dbo]
GO
SET ANSI_PADDING OFF
GO
```

The user bob gets created with a password of $Password$ instead of the password we specified when calling DeployChanges.  This same script runs OK using dbup version 3.3.5.0.  I think it has something to do with the single quotes surrounding $Password$.

**Comment by ksumrall** [comment]
It looks like there was a change to the way variables get substituted in commit 4328be44e3ba275e0c709948a1c1ec35a27a1930.
I've had to make a change the Support/SqlServer/SqlParser.cs file to get around this.
I've updated the ReadQuotedString and ReadBracketedText to check if the current character marks a custom statement...


        private void ReadQuotedString()
        {
            ReadCharacter(CharacterType.QuotedString, CurrentChar);
            while (Read() != FailedRead)
            {
                // this is new code
                if (IsCustomStatement)
                {
                    ReadCustomStatement();
                }
                ReadCharacter(CharacterType.QuotedString, CurrentChar);
                if (IsQuote)
                {
                    return;
                }
            }
        }



        private void ReadBracketedText()
        {
            ReadCharacter(CharacterType.BracketedText, CurrentChar);
            while (Read() != FailedRead)
            {
                // this is new code
                if (IsCustomStatement)
                {
                    ReadCustomStatement();
                }
                ReadCharacter(CharacterType.BracketedText, CurrentChar);
                if (IsEndOfBracketedText)
                {
                    var peekChar = PeekChar();
                    // Close brackets within brackets are escaped with another
                    // Close bracket. e.g. [a[b]]c] => a[b]c
                    if (peekChar == CloseBracketChar)
                    {
                        Read();
                        ReadCharacter(CharacterType.BracketedText, CurrentChar);
                    }
                    else
                    {
                        return;
                    }
                }
            }
        }

**Comment by thomas-parrish** [comment]
@tamaspataky55 I wouldn't count on any. Project is basically abandoned.

**Comment by alexriedl** [comment]
I ran with @ksumrall's changes locally and it works as expected. I noticed those changes did not make it into the beta4 release though. The changes are not in master and I did not see a merge request with these changes in it.

**Comment by droyad** [comment]
@alexriedl This and the other two bugs are next on my list to action. Just been trying to get on top of the issues :)
