### ISSUE TITLE
Specify credentials in TemporarySqlDatabase

### ISSUE THREAD

**Issue by veccsolutions** [DbUp/DbUp#294]
Now that SQL is usable in containers for testing, it would be great if we could specify the credentials to use to connect to SQL when using the TemporarySqlDatabase.

I think this could be easily accomplished by adding another constructor that would take in a connection string builder.

If this is something you would be willing to take a pull request for, I'd be more than happy.

**Comment by jRoesgaard** [comment]
I have just ran into the same issue, so I totally agree with you, that it would be nice with a extension.

**Comment by droyad** [comment]
@veccsolutions Yes it is, please build it on top of the `release/4.0.0` branch

**Comment by veccsolutions** [comment]
Not sure what happened, but it looks like the release/4.0.0 branch just barely got deleted when I did my pull request. Should I re-do it against master?

**Comment by droyad** [comment]
@veccsolutions I've merge that branch into `master`, so build on top of `master` :). It should merge cleanly, so no need to re-do

**Comment by droyad** [comment]
Ah I saw that it closed the PR. I've fixed up the PR and will look at it

**Comment by veccsolutions** [comment]
Awesome thanks.
