### ISSUE TITLE
Variable substitution in .NET core SqlServer not working

### ISSUE THREAD

**Issue by laurencee** [DbUp/DbUp#297]
Using `dbup-sqlserver 4.0.0-beta0002`

Given the following code the `$DbName$` variable should be replaced but this does not happen.
Instead a database named `$DbName$` is created.

```c#
var upgradeEngine = DeployChanges.To
	.SqlDatabase("Server=(localdb)\\mssqllocaldb;Trusted_Connection=True;")
	.WithScript("test.sql", "CREATE DATABASE [$DbName$]")
	.WithVariable("DbName", "MyTestDb")
	.Build();

upgradeEngine.PerformUpgrade();
````

This is being run from a .NET Core 2.0 project on Win10 in VS2017.

**Comment by dazinator** [comment]
Looks like dupe of #293

**Comment by laurencee** [comment]
Ah thanks, I didn't see that one 👍
