### ISSUE TITLE
using dbup for postgresql uses bad  sintaxis

### ISSUE THREAD

**Issue by carvajalluis** [DbUp/DbUp#300]
while trying to use this tool I need a journaling  table per schema,

`UpgraderEngine = DeployChanges.To.PostgresqlDatabase(ConnectionString)
                .WithScriptsEmbeddedInAssembly(Assembly.GetExecutingAssembly(), BuildFilter())
                .WithVariables(AppSetings)
                .JournalToSqlTable(ConfigurationManager.AppSettings["PostgresSchema"], "schemaversions")
                .LogToConsole()
                .Build();`
but I found that :

`The [sandbox].[schemaversions] table could not be found. The database is assumed to be at version 0.
Executing SQL Server script 'DbUpgradeManager.Scripts.postgreSQL.00001 - Alter something.sql'
Creating the [sandbox].[schemaversions] table
Upgrade failed due to an unexpected exception:
Npgsql.PostgresException (0x80004005): 42601: syntax error at or near "["`

which to my understanding means that it is trying to create the table like :
`CREATE TABLE [sandbox].[schemaversions]
(` 

on postgres, that will always throw an exception

**Comment by droyad** [comment]
@carvajalluis are you using 3.0 or the 4.0 beta? If the former, does 4.0 also have the bug?

**Comment by carvajalluis** [comment]
my client project is using 3.3.5, in production. they got several schemas in a single postgres db and treat them as different dbs ( which for me is a bad practice, but not my choice), that is why I needed this to work.

**Comment by georgepaoli** [comment]
Same error in 4.0.0-beta0003.

**Comment by droyad** [comment]
The `JournalToSqlTable` is for SQL server. I've added a `JournalToPostgresTable` method, as well as the ability to specify the schema in the `PostgresqlDatabase` call.
