### ISSUE TITLE
Enable support for VerticaDB

### ISSUE THREAD

**Issue by carvajalluis** [DbUp/DbUp#301]
Hi, 

I don't know if this is viable or already thought of but I think it will be great to expand to most of all DBMS , including in particular to me Vertica.  is there a way I can contribute to this achievement? 

This will finally render DBUP as the ultimate db deploy tool

**Comment by droyad** [comment]
@carvajalluis yes, you can write a provider for it. Check out the `release/4.0.0` branch, and build on that. You could either own that project and we will link it, or add it to this repo.

**Comment by droyad** [comment]
You should not use the `master` branch
