### ISSUE TITLE
Script executes without error but does not get added to SchemaVersions

### ISSUE THREAD

**Issue by jgalentine007** [DbUp/DbUp#303]
Hi! I'm new to DbUp. When I execute a script that had the following TSQL at the end, no error is thrown.  Unfortunately the script is not added to the SchemaVersions table - so the script is executed again if DbUp is run again. I'm not sure if this is a bug, or if there is additional checking that I need to perform when running the upgrade code. Everything works if I remove the offending TSQL. The script is set as embedded resource.

```sql
GO
USE [master]
GO
ALTER DATABASE [database] SET  READ_WRITE 
GO
```

Code (from DbUp site):

```csharp
static int Main(string[] args)
        {
            var connectionString =
                args.FirstOrDefault()
                ?? "Server=(local)\\SqlExpress; Database=database; Trusted_connection=true";

            EnsureDatabase.For.SqlDatabase(connectionString);

            var upgrader =
                DeployChanges.To
                    .SqlDatabase(connectionString)
                    .WithScriptsEmbeddedInAssembly(System.Reflection.Assembly.GetExecutingAssembly())
                    .LogToConsole()
                    .Build();

            var result = upgrader.PerformUpgrade();

            if (!result.Successful)
            {
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine(result.Error);
                Console.ResetColor();
#if DEBUG
                Console.ReadLine();
#endif
                return -1;
            }

            Console.ForegroundColor = ConsoleColor.Green;
            Console.WriteLine("Success!");
            Console.ResetColor();
            return 0;
        }
```

**Comment by droyad** [comment]
I think the problem is that you switch to `master` but don't switch back. Why do you need to do this in a upgrade script? Usually you don't have `use` statements in your scripts.

If you really need to do it, save the current DB name to a variable, then switch back at the end

**Comment by jgalentine007** [comment]
I was testing with a script that came out of a generate database scripts process. I don't actually need to use the offending TSQL or switch to master. I just wanted to bring attention that in doing so DbUp seems to fail silently in this case (no exceptions thrown or other errors.) I also wanted to make sure that there wasn't some additional error handling that I should be doing.

**Comment by droyad** [comment]
I assume `result.Successful` was `true`?

**Comment by jgalentine007** [comment]
Correct - `result.Successful` was `true`. DbUp version 3.3.5 from NuGet.

**Comment by droyad** [comment]
Ok, I can reproduce this in 3.3.5 and 4.0. The SchemaVersions table gets created in the `master` database and the journal record written there. 

Subsequent scripts would then run against the `master` database.

Not sure how to handle this, each database server handles switching databases differently, which makes it hard to switch back to the right DB.

**Comment by dazinator** [comment]
Sounds like the problem is in the scripts themselves and perhaps not an issue for dbup to try solving?

Although if we always wanted to ensure that the journal was created in a specific database (i.e the database conn string) - each journal table provider could prefix its commands (create statements, inserts etc) with whatever the equiavlent of USE DB is, and they perhaps could get the database name from the conn string. This might ensure that even of a user script switches away, the journal switches back..

But that might then cause a problem if the user switches to db B the script is execute, the journal switches back to db A, then the next user script now runs on db A again and not db B as the user may expect given their last USE db statement..

So yeah.. we could do something and make it clear what the new convention is, or we could just leave this a user script issue..

**Comment by dazinator** [comment]
Another idea might be to do the journalling using a seperate connection to the one that scripts are applied with. However would have to think through transactions in that scenario..

**Comment by droyad** [comment]
I agree, it's a user script issue. I might just look at adding a warning/error if we write to the wrong DB. Another connection would complicate the transactions. Besides, it breaks the atomicity/predicatability of the scripts.

Thanks for the sanity check @dazinator

**Comment by sllewellyn13** [comment]
The answer to this problem is that the developer forgot to make his scripts an **embedded resource** in the Console App project.

**Comment by jgalentine007** [comment]
Of course the scripts were embedded, they were being executed after all - read the thread. The problem is switching databases in a script is not supported and DbUp was not producing any output as such.

**Comment by sllewellyn13** [comment]
@jgalentine007 Thanks - sorry for the mistake!

**Comment by jgalentine007** [comment]
No worries, sorry for the cranky response, woke up on the wrong side again!
