### ISSUE TITLE
Escaped quote in quoted string not handled correctly in SqlParser.ReadQuotedString

### ISSUE THREAD

**Issue by ludocornut** [DbUp/DbUp#304]
To check  end of quoted string, it may be safe to check if is not escaped quote ex :
`'bla bla \'fdfs\' bla bla'`

Before :
               if (IsQuote)
                {
                    return;
                }

After :
               if (IsQuote && LastChar != '\\')
                {
                    return;
                }

**Comment by dazinator** [comment]
Looks sensible to me. Would you be able to submit a PR for this?

**Comment by droyad** [comment]
@ludocornut Could you give us an example of a script where this causes a problem?

**Comment by droyad** [comment]
@ludocornut I tried reproducing this on SQL Server, but it's the wrong quote style. Which DB was this for?
