### ISSUE TITLE
Schema Versions table is created when checking whether an upgrade is required.

### ISSUE THREAD

**Issue by droyad** [DbUp/DbUp#316]
`upgrader.IsUpgradeRequired();` creates the schema versions table. We probably don't need to do this.

**Comment by orjan** [comment]
I'm not sure if this is related to this issue but I've returned to an old project were our initial migration script looks like:
```
CREATE SCHEMA Migrations
```
The we're calling dbup with `.JournalToSqlTable("Migrations", "SchemaVersions")` but this one fails after upgrade to version 4.
```
Executing migrations
Running migrations for "Type: Attachments, Name: AttachmentsTest"
Path /Users/orjan/Code/ve/brikks/upgrades/migrations
Beginning database upgrade
Checking whether journal table exists..
Creating the [Migrations].[SchemaVersions] table
Upgrade failed due to an unexpected exception:
"System.Data.SqlClient.SqlException (0x80131904): The specified schema name \"Migrations\" either does not exist 
```

**Comment by droyad** [comment]
@orjan Yeh, it is.
