### ISSUE TITLE
MySql migration with Transaction should rollback all scripts when failed

### ISSUE THREAD

**Issue by sebastieno** [DbUp/DbUp#317]
Hello everyone,

I tried to use DbUp for my MySql database migration process and I meet a weird behavior.

I created two migrations (each migration creates the exact same table). I want to be able to execute those migrations in a single transaction (to ensure that if an upgrade process failed, the database will not be in an invalid state). Here my code (nothing special) :

```
 UpgradeEngine upgrader = DeployChanges.To.MySqlDatabase(connectionString)
                .WithScriptsEmbeddedInAssembly(Assembly.Load(xxx))
                .LogToConsole()
                .LogScriptOutput()
                .WithTransaction()
                .Build();

DatabaseUpgradeResult result = upgrader.PerformUpgrade();
```
The second migration fails because the table already exists (as the first migration creates it).

After the execution, I see in the version table that the second migration has not been marked as done, but my table (created by the first migration) is not rollbacked.

I am missing something ?

Thx for you help.

**Comment by droyad** [comment]
@sebastieno According to https://dev.mysql.com/doc/refman/5.7/en/implicit-commit.html It is not possible to rollback `CREATE TABLE` in MySQL. I'll add a pointer to that in the docs.

**Comment by sebastieno** [comment]
Thx for your quick reply and your help :)

**Comment by bounav** [comment]
Hello, it looks like mysql 8.0 support [DDL wrapped in a transaction](https://dev.mysql.com/doc/refman/8.0/en/atomic-ddl.html).

Would it be worth re-opening this ticket?

**Comment by droyad** [comment]
@bounav What needs to be done? My understanding is that this should just work now.

**Comment by bounav** [comment]
@droyad I haven't tested it with mysql 8.0 but yes, it should _just_ work.

I just wanted to clarify in case someone landed on this closed issue (i.e. like I did) that migrating to mysql 8.0 should help.
