### ISSUE TITLE
WithTransactionPerScript causes parallel transaction error

### ISSUE THREAD

**Issue by droyad** [DbUp/DbUp#319]
Via @InvincibleDRT and #124 

Commit https://github.com/DbUp/DbUp/commit/1fd851e4127c29ffd9ca5e064a4b3c66fecd4b03 (fix for #316) causes `WithTransactionPerScript` upgrades to stop working:

```
DeployChanges.To
    .SqlDatabase(IntegrationTestDatabase.ConnectionString)
    .WithScript($"Script 1", "Select 1")
    .WithScript($"Script 2", "Select 1")
    .LogToNowhere()
    .WithTransactionPerScript()
    .Build();
```
`SqlConnection does not support parallel transactions`

**Comment by InvincibleDRT** [comment]
Just a note that Withtransactionperscript() also causes deadlock error, when running in parallel. though it's less frequent.

**Comment by droyad** [comment]
@InvincibleDRT Is that DBUp schema updates creating the deadlock, or your own scripts? Do you have a deadlock graph from SQL Profiler?
