### ISSUE TITLE
Create the journal before running scripts

### ISSUE THREAD

**Issue by droyad** [DbUp/DbUp#320]
Before #316, the schema versions table was created when figuring out which scripts are to be executed. Since then however it is only created after the first script is run. The journal should be created first to increase the likelihood that we can actually write to the journal once the script is run.

This introduces a breaking change to `IJournal`, an additional method `EnsureTableExistsAndIsLatestVersion` needs to be implemented. Also the signatures of protected methods of `TableJournal` have changed.

**Comment by YauhenPyl** [comment]
It looks like it is breaking one case:
1. The first script is a script which creates database;
2. The second script is a script which creates SP in created database;
Currently dbUp will create SchemaVersions in `master` before executing first script and will fail at the second script with error: `Invalid object name 'SchemaVersions'.` as it is trying to find SchemaVersions table in created database.
