### ISSUE TITLE
Logs are Redundant when dbup is run for multiple dbs

### ISSUE THREAD

**Issue by sonu-ajay** [DbUp/DbUp#321]
I am trying to run DBUp in multiple Databases by using foreach.
For example I am running 4 scripts to 4 DBs.
So Every Database's SchemaVersions Table will have the log 4 time, i.e it will have 16 rows added to all Databases as Journals

**Comment by droyad** [comment]
Are you saying that each table will have 16 rows? If so, could you post the DBUp builder/execution code, and an example of one of the SchemaVersions table please.
