### ISSUE TITLE
WithoutScripts or Migration possibilities. 

### ISSUE THREAD

**Issue by SimonRupar** [DbUp/DbUp#322]
Hello everyone,
With great anticipation, I am waiting for a day to be able to switch our internal tool to DbUp. Our internal tool also used journaling table in the database which has given me the motivation to move some tool more "publicly" used. Currently, my implementation is a little "funky" because I basically do "two-step upgrade". In the first step, I only execute migration script which creates DbUp journaling table and migrates from our internal journaling table. This works but as I mentioned it is kinda "funky" keeping me on my toes which compatibility between my "migration" script and DbUp journaling table. Is there any plan or intent to be able to create DbUp journaling table for the start before even checking for which scripts to execute?  (e.g.: WithoutScripts() parameter). 
Maybe related to #320 

Cheers, 
Simon Rupar

**Comment by droyad** [comment]
I don't see any reason we can't expose the `EnsureTableExistsAndIsLatestVersion` method. 

I'm not sure of the use case though. Why do you want the table to be created before checking whether scripts need to be run?

**Comment by SimonRupar** [comment]
Hello @droyad , thank you for the response.
My problem is actually related to migration from our internal tool with different journaling table. For example, using our internal tool I apply the scripts 1.sql and 2.sql (which are not repeatable). This is also already applied to production. I do the switch to start using DbUp. And already I have prepared script 3.sql. So when I start using DbUp in production I have a problem, because DbUp will not be informed that scripts 1.sql and 2.sql were already applied to this database and will create fresh journaling table and start executing 1.sql script which will in best case fail.  (Migration required)
Why does this happen? Because check and creation of journaling table are done on the first execution of the script and the first script is already in "pool for execution". 

So I have to tackle this problem:
- Eather I prepare migration script and inform dba to manually apply this from some point in time on. High risk, because of manually intervention on customer side.
- Prepare my own procedure in my modification of DbUp which will execute this migration and create journailng table. Problem which is higly depended that my custom part is compatible with DbUp all the time. _I'm going with this one, and hope for best _
- Delete already executed scripts from my repository before preparing deployment package. Problem is that I don't really have full access to all customers environments, so I don't really know the state of database. Also this point that I would need prepare for every customer specialized deployment package.

**Comment by droyad** [comment]
You should be able to do the following:
- Create a script that checks for the SchemaVersions table and creates it and populates it if it doesn't exist.
- Run this script using DBUp using the NullJournal
- Run DBUp again as you normally would

If the structure of SchemaVersions ever changes, we would transparently migrate that for you (for backwards compatibility), so you should be fine on that front.

You could also implement your own `IJournal` and continue to use your own table.

**Comment by divyapai56** [comment]
> You should be able to do the following:
> 
> * Create a script that checks for the SchemaVersions table and creates it and populates it if it doesn't exist.
> * Run this script using DBUp using the NullJournal
> * Run DBUp again as you normally would
> 
> If the structure of SchemaVersions ever changes, we would transparently migrate that for you (for backwards compatibility), so you should be fine on that front.
> 
> You could also implement your own `IJournal` and continue to use your own table.

"populates it if it doesn't exist." - I have around 117 tables, and multiple filestreams in my DB, so do you have any easy way as of how to populate the schema version table?

**Comment by droyad** [comment]
The SchemaVersions table contains the scripts that have run. You would just put the scripts you want to skip over into that. e.g. if you can have a single script called `000 - Initial Schema.sql` that contained the creation of those 117 tables and filestreams. On existing databases your would put the right record into the SchemaVersions table so that DBUp skips over them.
