### ISSUE TITLE
Question: Support for databases with DDL implicit commits

### ISSUE THREAD

**Issue by SimonRupar** [DbUp/DbUp#323]
Hello everyone,

As far as I noticed DbUp only supports databases which do not have DDL implicit commit. I am most interested in implementation for Oracle #19 #23 #53 #77 #224 #228. As you can see there has been a lot of interest. Also, there are other tools which provide a similar implementation: 
- https://github.com/chucknorris/roundhouse
- https://github.com/flyway/flyway

Is there any basic plan or idea how to support those databases? Or is it maybe intent of DbUp to stick to databases which provide support for transactions also over DDL statements?

One idea on which I created my implementation is that I mark last successful statement in SQL script. That way at least I know to which point I have successfully executed migration and have also a repeatable failure

Cheers, and thank you for your answer, 
Simon Rupar

**Comment by droyad** [comment]
We already support MySQL which does not support DDL modification in a transaction (see https://dbup.readthedocs.io/en/latest/more-info/transactions/). So I see no problem supporting Oracle as well. 

[This](https://wiki.postgresql.org/wiki/Transactional_DDL_in_PostgreSQL:_A_Competitive_Analysis) article implies Oracle can have transacted DDL modifications.

I am not familiar enough with Oracle to write a good implementation, but am certainly willing to accept a PR that has the support. There is #228, so it might just require updating/forking that PR to move to the 4.0.0 structure.
