### ISSUE TITLE
Output SQL that is being run

### ISSUE THREAD

**Issue by phillijw** [DbUp/DbUp#325]
Is there a way to output the finalized SQL that gets run? I did not see any way to log this. Debugging issues is impossible because it seems the executors are rewriting sql for various reasons but I can't determine what the result of that rewrite is without outputting it somehow.

**Comment by JustinPealing** [comment]
You can use the `Scripts` property on `DatabaseUpgradeResult`, like so:

    foreach (var script in result.Scripts)
    {
        Console.WriteLine("==============================");
        Console.WriteLine($"{script.Name}");
        Console.WriteLine("==============================");
        Console.WriteLine(script.Contents);
        Console.WriteLine();
    }

There is also an extension method `WriteExecutedScriptsToOctopusTaskSummary` that does something similar specifically for use in Octopus deploy:

    result.WriteExecutedScriptsToOctopusTaskSummary();

Note however that if a script encounters an error, it won't be included in that collection. To work out what script will have caused the error you can use `GetScriptsToExecute` on the engine, and then compare to the scripts in the result:

    var scriptsToExecute = engine.GetScriptsToExecute();
    var result = engine.PerformUpgrade();
    
    // If an error happens, then the script that errors does not appear in result.Scripts. Check the list of scripts
    // that we know should have been executed to identify and log the first script that didn't run.
    var notRun = scriptsToExecute.FirstOrDefault(s => result.Scripts.All(x => x.Name != s.Name));
    if (notRun != null)
    {
        Console.WriteLine("==============================");
        Console.WriteLine($"FAILED - {notRun.Name}");
        Console.WriteLine("==============================");
        Console.WriteLine(notRun.Contents);
        Console.WriteLine();
    }

**Comment by JustinPealing** [comment]
It would be handy to have some sort of property on the result that made it easier to get the script that was running when an exception was thrown. I could submit a PR?

**Comment by mjauernig** [comment]
Seems to be done already. If still needed, please reopen.
