### ISSUE TITLE
Feature/syntax to call or reference a script from a migration

### ISSUE THREAD

**Issue by phillijw** [DbUp/DbUp#327]
One thing that would be beneficial for several reasons would be to make a separate folder for objects like stored procs. The initial CREATE would be done via migration but future changes could be done with an ALTER script. This script could be kept in a side-folder that is always there holding these "objects" as alter scripts. When you want to make a change, you simply modify the alter script and then reference it from a migration script so it executes.

This really cleans up one use case in particular, such as when two people work on the same object and then merge their code together. The first gets run successfully and then the 2nd gets run successfully and overwrites the first one. This is a pain point that seems easy enough to fix if we could simply reference and inject another script from within a migration script. Is this possible, if not, does anyone have ideas on how to make it possible?

SSDT uses some special syntax that it parses and injects the script into the migration script during the build/deploy process. Something like this would probably be ideal.

**Comment by droyad** [comment]
You can run DBUp again after your main schema migration, just pointing it at that folder with the Views/etc. Use `.JournalTo(new NullJournal())` to make sure that these scripts get run everytime. 

The downside is that they get run everytime. If that is a problem, you could come up with some sort of check to see whether they have changed (or perhaps use the application version number to control this). 

You could write your own namer that prefixes the repeatable scripts with the application version number and just keep the default journal. That way they only get run if the name changes (ie on every application version bump).

**Comment by sungam3r** [comment]
Closed due to inactivity.
