### ISSUE TITLE
Transaction Timedout error

### ISSUE THREAD

**Issue by InvincibleDRT** [DbUp/DbUp#328]
When multiple instances of dbup are being run, against the same database, I am seeing the Transaction Timeout error with following error message

System.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.

This is my upgradeBuilder code

```
var upgradeBuilder = DeployChanges.To
                                    .SqlDatabase(branchDBInfo)
                                    .WithScriptsFromFileSystem(path, fsso)
                                    .WithVariablesDisabled().LogTo(this).WithTransaction().WithExecutionTimeout(TimeSpan.FromSeconds(360));


   upgradeBuilder.Configure(x => x.ScriptExecutor.ExecutionTimeoutSeconds = 60 * 60);
```

Here are some numbers:
64 Threads at peak, 62 of them will finish in less than 4min each. 2 threads will run about 15min
the 62 threads run total of 3000 sql files. 2 threads will run total of 1700 files (bigger files).

**Comment by InvincibleDRT** [comment]
Is there any way to figure out what files are there in the failed transaction. And to limit the transaction batch size?

**Comment by droyad** [comment]
`WithTransaction` will take out a transaction for all scripts in that run. Consider whether `TransactionPerScript` is better suited for your use case.

`Upgrader.GetScriptsToExecute()` will get you the scripts DBUp will run.

You could limit the number of threads you spin up.

**Comment by InvincibleDRT** [comment]
WithTransactionPerScript used to cause deadlocks, so I switched to just withTransaction.

If I use WithTransactionPerScript, Does upgrader.GetScritstoexecute will give all the files that are supposed to execute in that run or just the one that got failed due to deadlock?

Limiting the threads is the last option we want to consider, as we will be doing this routine frequently.

If I use withoutTransaction  execution is very very slow. Do you have any insight on why that is happening?
