### ISSUE TITLE
Build steps? Getting build errors with VS2017

### ISSUE THREAD

**Issue by phillijw** [DbUp/DbUp#329]
I opened the sln in VS2017. I'm unable to build the solution. I receive 13 errors that resemble these messages for several frameworks:

|Severity	|Code	|Description	|Project	|File	|Line	Suppression |State|
-----------|----------|----------------|----------|-----|-------------------|------|
|Error	|MSB3645	|.NET Framework v3.5 Service Pack 1 was not found. In order to target ".NETFramework,Version=v3.5", .NET Framework v3.5 Service Pack 1 or later must be installed.	|dbup-core	|C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	|1126	
|Error	|MSB3644	|The reference assemblies for framework ".NETFramework,Version=v3.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.	|dbup-core	|C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	|1126	

Do I have to have each individual SDK installed or something?

**Comment by icnocop** [comment]
Did you try installing .NET Framework v3.5 Service Pack 1 or later?

**Comment by phillijw** [comment]
I don't remember, but it is the core package I was trying to build. It somehow just started working and I'm not sure what the fix was. We can probably close this but having build instructions would be nice.

**Comment by oooolivierrrr** [comment]
I have the same problem. I've just cloned the repo, fired up vs2017 and have all the issues described above.

I don't have 3.5 installed : how can i remove those dependencies on 3.5 ?

**Comment by oooolivierrrr** [comment]
I too want to build without 3.5 dependencies. What assemblies need that framework ? Is possible to get ride of them ?

**Comment by sungam3r** [comment]
fixed by #655
