### ISSUE TITLE
Oracle DB Error Attempting to Create or Replace Package

### ISSUE THREAD

**Issue by AdrianJSClark** [DbUp/DbUp#334]
_Note: Originally posted by @steflege here: https://github.com/DbUp/DbUp/issues/224#issuecomment-388166209_

> Great solution thanks.
> 
> A simple query in an sql script file run well.
> 
> Just have some problems with my create or replace package scripts(utf8 with bom). 
> 
> It always returns :
> ----
> Spec	1	71	PLS-00103: Symbole "end-of-file" rencontré à la place d'un des symboles suivants :
>    . @ % ; is authid as cluster order using external character
>    deterministic parallel_enable pipelined aggregate
>    result_cache accessible
> ---
>  There is the script:
> CREATE OR REPLACE PACKAGE PCK1 AS
> 
> FUNCTION Test(p_param IN VARCHAR2) RETURN VARCHAR2;
> 
> END;
> /
> 
> When I look at the generated Package (with errors) the source looks like :
> CREATE OR REPLACE PACKAGE PCK1 AS  FUNCTION Test(p_param IN VARCHAR2) RETURN VARCHAR2
> /
>  
> It seems to stop where the first ';' character was found in the original script.
> 
> Is it normal? 
> 

@treesrc replied: https://github.com/DbUp/DbUp/issues/224#issuecomment-388279459

> ; (semicolon) is used as a delimiter so I think it is not possible. You can use also c# code for migration. In SampleApplication project there is Script0005 - ComplexUpdate.cs file. In your c# class, you can execute whatever you want.

@steflege responded to this: https://github.com/DbUp/DbUp/issues/224#issuecomment-388347425

> Thank you for your fast answer.
> 
> Unfortunatly, it would be hardly feasible to transform our oracle packages (from 100 to 800 lines) in c# class. Almost all of our scripts are packages replacement(+/- 200 packages per year) or Oracle objects upgrading scripts containing many semicolons.
> 
> There most be an other solution.

**Comment by ttufekci** [comment]
I will change the delimiter for oracle to slash character **/** , if it does not break any test and make a pull request. So we can create trigger, procedure, package etc.

**Comment by ttufekci** [comment]
@AdrianJSClark, @steflege I have made a pull request #335 to use slash character as default delimiter.

**Comment by sungam3r** [comment]
Covered by #509.
