### ISSUE TITLE
Looking for way of enforcing a different order of execution

### ISSUE THREAD

**Issue by nvarscar** [DbUp/DbUp#336]
When using `.WithScripts` method, I submit the array with the scripts in a certain order, which, however, is being overridden by `GetScriptsToExecuteInsideOperation()` method:
`var sorted = allScripts.OrderBy(s => s.Name, configuration.ScriptNameComparer);`
I don't see how this behavior can be changed using available interfaces, as it is a part of the `PerformUpgrade()` method, which dictates its own rules. 
Is there something I'm missing here? I know I can change the names of the scripts provided, but I would rather submit them in a desired order instead of changing names dynamically, because it may lead to a different execution order during next migration.

**Comment by droyad** [comment]
You can write your own ScriptNameComparer that returns the scripts in the order you want

**Comment by nvarscar** [comment]
Thank you for the idea, I toyed with it for a while and it seems that if I provide the custom sorting (and comparing) logic, it will also be applied to the filtering part (where script list gets compared against the list of already deployed scripts), which impacts the overall deployment in a negative way.

Basically, the way to **disable** ordering is to force the comparer into thinking that all items are equal to each other (at least I didn't find any other way of keeping the deployment order intact by changing the comparison logic), that however, also impacted the script filtering - now once a single script is deployed it thinks that all other scripts are deployed too because the comparer returns 0 all the time.

Right now I have no ideas how to make it work without impacting other parts. I'm probably doing something wrong, but right now I don't see any other solution, except when I'm forced to treat each script as a standalone deployment, which is of course doable but not at all efficient. Also, the output will contain tons of initialization text, which I would have to filter out somehow.

**Comment by droyad** [comment]
You are most likely passing an array/list of scripts to `WithScripts`, why not base the comparer on that list and return the relative index of each script within the original array/list. Still a work around, I know :)

**Comment by nvarscar** [comment]
Thanks for the idea! Managed to get it working on my end by comparing relative indexes of array members inside the comparer instead of comparing strings. You guys are awesome!
