### ISSUE TITLE
Version 4.1.0 bug ?

### ISSUE THREAD

**Issue by ppXD** [DbUp/DbUp#337]
use `WithScriptsAndCodeEmbeddedInAssembly` cann't run IScript implement code.

**Comment by droyad** [comment]
Could you expand on what you mean by "can't run IScript implementation code"?

**Comment by tejagsp** [comment]
I have the similar problem. The scripts inheriting IScript doesn't work.

Example:
I have created a script like this:

` public class Script0002InsertExample : IScript {
     public string ProvideScript(Func<IDbCommand> commandFactory) {
         // Code goes here
     }
}`

When I run the application, the script file doesn't execute.
This happens with the latest version 4.1.0. With the version 3.3.5, it works perfect.

Snapshots here:
Version 4.1.0
![image](https://user-images.githubusercontent.com/5563405/42218718-287613d6-7ed2-11e8-904e-95e4fa9e1a63.png)

Version 3.3.5
![image](https://user-images.githubusercontent.com/5563405/42218726-31137b1e-7ed2-11e8-9529-f58bc3a28042.png)

Version 4.1.0 doesn't contain the queries from IScript

**Comment by droyad** [comment]
Duplicate of #347
