### ISSUE TITLE
PerformUpgrade failed on a medium/large MySQL database

### ISSUE THREAD

**Issue by martindeslongchamps** [DbUp/DbUp#340]
Hi,

I am trying to add a column into a database with quite lot of information. The query is in a script and the query works on a small database. When I execute PerformUpgrade on this larger database, I get this error:

> [2018-06-12 11:40:51 PM - DbUp - ERROR]:Script block number: 2; Error code -2147467259; Message: Fatal error encountered during command execution.
> [2018-06-12 11:40:51 PM - DbUp - ERROR]:MySql.Data.MySqlClient.MySqlException (0x80004005): Fatal error encountered during command execution. ---> MySql.Data.My
> SqlClient.MySqlException (0x80004005): Fatal error encountered attempting to read the resultset. ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Readin
> g from the stream has failed. ---> System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected p
> arty did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ---> System.Net.Sockets.Soc
> ketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because
> connected host has failed to respond
>    at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
>    at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
>    --- End of inner exception stack trace ---
>    at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
>    at MySql.Data.MySqlClient.TimedStream.Read(Byte[] buffer, Int32 offset, Int32 count)
>    at MySql.Data.MySqlClient.MySqlStream.ReadFully(Stream stream, Byte[] buffer, Int32 offset, Int32 count)
>    at MySql.Data.MySqlClient.MySqlStream.LoadPacket()
>    at MySql.Data.MySqlClient.MySqlStream.LoadPacket()
>    at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
>    at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
>    at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
>    at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
>    at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
>    at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
>    at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
>    at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
>    at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
>    at DbUp.Support.SqlServer.SqlScriptExecutor.<>c__DisplayClass15_0.<Execute>b__1(Func`1 dbCommandFactory)
>    at DbUp.Engine.Transactions.NoTransactionStrategy.Execute(Action`1 action)
>    at DbUp.Engine.Transactions.DatabaseConnectionManager.ExecuteCommandsWithManagedConnection(Action`1 action)
>    at DbUp.Support.SqlServer.SqlScriptExecutor.Execute(SqlScript script, IDictionary`2 variables)
> [2018-06-12 11:40:51 PM - DbUp - ERROR]:Upgrade failed due to an unexpected exception:
> MySql.Data.MySqlClient.MySqlException (0x80004005): Fatal error encountered during command execution. ---> MySql.Data.MySqlClient.MySqlException (0x80004005): F
> atal error encountered attempting to read the resultset. ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Reading from the stream has failed. ---> Syste
> m.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a pe
> riod of time, or established connection failed because connected host has failed to respond. ---> System.Net.Sockets.SocketException: A connection attempt faile
> d because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
>    at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
>    at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
>    --- End of inner exception stack trace ---
>    at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
>    at MySql.Data.MySqlClient.TimedStream.Read(Byte[] buffer, Int32 offset, Int32 count)
>    at MySql.Data.MySqlClient.MySqlStream.ReadFully(Stream stream, Byte[] buffer, Int32 offset, Int32 count)
>    at MySql.Data.MySqlClient.MySqlStream.LoadPacket()
>    at MySql.Data.MySqlClient.MySqlStream.LoadPacket()
>    at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
>    at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
>    at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
>    at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
>    at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
>    at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
>    at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
>    at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
>    at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
>    at DbUp.Support.SqlServer.SqlScriptExecutor.<>c__DisplayClass15_0.<Execute>b__1(Func`1 dbCommandFactory)
>    at DbUp.Engine.Transactions.NoTransactionStrategy.Execute(Action`1 action)
>    at DbUp.Engine.Transactions.DatabaseConnectionManager.ExecuteCommandsWithManagedConnection(Action`1 action)
>    at DbUp.Support.SqlServer.SqlScriptExecutor.Execute(SqlScript script, IDictionary`2 variables)
>    at DbUp.Engine.UpgradeEngine.PerformUpgrade()

The builder I use is like this:

```
UpgradeEngine upgradeEngine = DeployChanges.To.MySqlDatabase(connectionStringBuilder.ToString()).WithScriptsFromFileSystem(temporaryDirectory, (string s) => (match.IsMatch(s))).LogTo(_writer).Build();

// The next line seems to do nothing, but we use it later on in the code. I put it here in case, it could be of any utility.
List<SqlScript> scriptsToExecute = upgradeEngine.GetScriptsToExecute();

bool isUpgradeRequired = upgradeEngine.IsUpgradeRequired();

if (isUpgradeRequired) { upgradeEngine.PerformUpgrade(); }

```

[In another forum](https://bugs.mysql.com/bug.php?id=61807), I have read that I should increase the net_read_timeout/net_write_timeout values on the sqlcommand before executing the query. Unfortunately, this part seems to be out of my control.... am I right?  

I also remarked that the exception is always happening 30 seconds after the start of the command. If I run this script in workbench for this large database, the script runs for 500 seconds approximately. The default value of net_read_timeout is 30 seconds. All other timeout values are set to something different than 30 seconds. I have try to put the global value of net_read_timeout to 9999, restart my service, but nothing works.

Any ideas how to fix that?
Thanks.

**Comment by droyad** [comment]
You want to add `.WithExecutionTimeout(TimeSpan.FromMinutes(15)` to your `DeployChanges` statement

**Comment by martindeslongchamps** [comment]
Ok thanks I will try it again and let you know.

**Comment by martindeslongchamps** [comment]
It's working!
