### ISSUE TITLE
Bracket treated as variable encloser

### ISSUE THREAD

**Issue by wiseeker** [DbUp/DbUp#345]
Part of my 2nd script file has the following:

`PRINT N'Creating [dbo].[Table1]...';`
`GO`
`CREATE TABLE [dbo].[Table1] (`

And I get an error saying `System.InvalidOperationException: Variable Table1 has no value defined`.

I've only one variable defined (`InstallDir`) and that replacement happens fine in the scripts (`$InstallDir$`).

What I don't understand is, why [Table1] is being treated as variable substitution when variables are supposed to be enclosed in $$. When I defined `.WithVariable('Table1', 'Table1')`, dbup moves on and breaks at the next [] occurrence.

Above snippet is from 2nd script that gets executed. Interestingly, first script has a bunch table names enclosed in []; and, those are running fine. Does variable substitution gets "confused" after sometime?

This is driving me crazy. Please help!

**Comment by sungam3r** [comment]
Please, reopen if this issue is still actual.
