### ISSUE TITLE
WithScriptsAndCodeEmbeddedInAssembly filters embedded code scripts

### ISSUE THREAD

**Issue by tejagsp** [DbUp/DbUp#347]
The scripts inheriting IScript doesn't work.

Example:
I have created a script like this:

public class Script0002InsertExample : IScript { public string ProvideScript(Func<IDbCommand> commandFactory) { // Code goes here } }

When I run the application, the script file doesn't execute.
This happens with the latest version 4.1.0. With the version 3.3.5, it works perfect.

Snapshots here:
Version 4.1.0
![4 1 0](https://user-images.githubusercontent.com/5563405/42571161-ea9750d6-851e-11e8-9443-bcff9f8e8036.png)

Version 3.3.5
![3 3 5](https://user-images.githubusercontent.com/5563405/42571167-ef9aaca4-851e-11e8-833f-db17cff7582f.png)

In version 4.1.0, the script files are not executed

**Comment by jhumphries83** [comment]
I'm having this issue also.

I'm using .WithScriptsAndCodeEmbeddedInAssembly(Assembly.GetExecutingAssembly())

In v4.0.0 and upwards scripts that are implemented with the IScript interface are not executed.

I've had to roll back to v3.3.5 to get this to work.

**Comment by tejagsp** [comment]
Yes, I did the same with roll-backing to v3.3.5

**Comment by jhumphries83** [comment]
There is a pull request to fix this #339

**Comment by tejagsp** [comment]
Tested with the latest version, and everything works fine. Thanks
