### ISSUE TITLE
WithScriptsEmbeddedInAssembly(Assembly) breaks on Windows 10

### ISSUE THREAD

**Issue by creature7** [DbUp/DbUp#357]
I ran my application on a Windows 7 system (no scripts applied) and it executed both of my 2 embedded scripts, as expected (against a SQL CE 4 database). I tried it on a Windows 10 system with the first script already applied but the second one not, and it ended successfully, telling me that there were no scripts to be applied. I checked the SchemaVersion table, and only the first script was listed therein. Seems broken.

**Comment by sungam3r** [comment]
Is this still an actual problem? Can you give an example?

**Comment by sungam3r** [comment]
Closed due lack of feedback.
