### ISSUE TITLE
Any way to run certain scripts only if DbUp had to create the database?

### ISSUE THREAD

**Issue by marcscheuner** [DbUp/DbUp#364]
Using the "EnsureDatabase.For" feature, I can make sure my SQL Server database exists (or gets created, if it didn't exist yet). That works very nicely.

What I'm wondering is if there's a way to include a bunch of scripts that will get executed *ONLY* if the "EnsureDatabase" actually *did* create a new database. Specifically: when a new database is created, I need to (possibly) create a "Login" on the SQL Server, and I definitely need to create a "User* in the newly created database and assign it some database roles. These steps however, are *not* needed, if the database had already been prepared manually - so these scripts really only should be executed if DbUp itself creates the database.

Any way to do this? Or if not (yet): any plans to add such a feature?

**Comment by dazinator** [comment]
Couple of things come to mind. I think there is an overload that takes a logger. You might be able to pass in your own logger then inspect the log output to determine if a db was created? Then conditionally run dbup with your create user scripts based on that...

But the other thing is that i also create users and roles, but I make the sql script check for the login and user and role and create them only if they dont already exist. By doing things that way it also covers a case where someone created a blank db on a new server and didnt create any login or role.

**Comment by sungam3r** [comment]
Good practice is to make scripts idempotent. This solves the above problem and closes a bunch of potential errors.
