### ISSUE TITLE
Model, Seeding and Integration Tests

### ISSUE THREAD

**Issue by michalporeba** [DbUp/DbUp#373]
Over the last few months, I have been experimenting with expanding the migrations functionality of the DbUp project to include Model updates for stored procedures, named seeding scripts and classes that allow creating the database in an exactly same way either from a command line or by calling a method on a DbCreator class which has been very helpful in integration testing. 

I'm just wondering if any of those things are potentially in the scope of the DbUp project? Dear maintainers, would you be interested in discussing those concepts, or is it clearly outside of what DbUp is supposed to focus on? I have this functionality working in a couple of projects already but I'm thinking of tidying it up and contributing back. If you think this project has scope for it I'd be happy to discuss those ideas. If not I probably will start a fork and do my own thing. 

Please let me know.

**Comment by dazinator** [comment]
Hi. Some thoughts that occur to me on this are: did you have to make changes to the dbup core code to enable these new features or were you able to implement existing extension points? I'm thinking the things you mention are valuable but perhaps could be a seperate project built upon dbup as a dependency, rather than in with dbup project itself.

**Comment by michalporeba** [comment]
A very good point. So far I was able to build everything on top of DbUp using the existing extension points. There were a few moments when I was tempted to make core changes but in the end, I was able to avoid it so far. 

I'll look at packaging what I have and preparing some demos, perhaps that will be useful next step, but I do like the idea of an extension package. Thanks.

**Comment by droyad** [comment]
I agree we should keep the core lean and focused and provide extension points where possible. Happy to add any libs that build on to to the docs page
