### ISSUE TITLE
how to prevent passed script to execute

### ISSUE THREAD

**Issue by AliAfsharii** [DbUp/DbUp#376]
hi
imagine this situation. there are two branch of project. in both developers add script by full datetime name. one of branches merges to master and deploys to production server. after that another branch merges to master but sql scripts in this branch created before another branch and causes conflict.
How can we ignore scripts with smaller name than latest executed script name in version table?

**Comment by sungam3r** [comment]
You always can write your own `IScriptProvider`. In addition, it is recommended to design scripts with idempotent ones.
