### ISSUE TITLE
Support specific collation on db creation (sql server / azure)

### ISSUE THREAD

**Issue by tiptobi** [DbUp/DbUp#381]
Hi all,
according to the [microsoft docs](https://docs.microsoft.com/en-us/sql/relational-databases/collations/set-or-change-the-database-collation?view=sql-server-2017) it is not possible to set the DB collation after DB creation. So if we need a DB with a specific collation, we have to set the collation on DB creation.
I'm currently using EnsureDatabase.For.SqlDatabase for DB creation and it would be awesome if this method can take an optional string parameter for a specific collation. This collation should then be added to the create database statement in the SqlServerExtensions class.
As a work around for now, I cloned the SqlDatabase method from SqlServerExtensions to my own helper class and extended the create database statement with my collation. If there's already another way to create a DB with a specific collation let me know.

**Comment by dazinator** [comment]
Sounds good. Would you consider submitting a PR for to allow optional collation to be provided?

**Comment by tiptobi** [comment]
Yes sure, I'll do that :)

**Comment by tiptobi** [comment]
Pull request created: #382

**Comment by tiptobi** [comment]
#382 Merged

**Comment by bonesoul** [comment]
is this also possible for postgresql databases?
