### ISSUE TITLE
Don't obsolete SqlDatabase(SupportedDatabases, Func<IDbConnection>), we need it!

### ISSUE THREAD

**Issue by michaelaird** [DbUp/DbUp#39]
SqlServerExtensions.SqlDatabase(SupportedDatabases, Func< IDbConnection >) has been marked as obsolete.

We are using DbUp to migrate SQL Azure databases with federations. Before we execute any scripts (but after the connection is open), we need to issue as USE FEDERATION command to re-connect to the federation where the script should execute.

Currently, we're doing it likes this:

```
DeployChanges.To
              .SqlDatabase(() =>
              {
                  SqlConnection connection = new SqlConnection(ConfigurationManager.ConnectionStrings["Reporting"].ConnectionString);

                  connection.StateChange += new System.Data.StateChangeEventHandler(SetFederation);

                  return connection;
              })
```

Is there a new way to do this? or can we have this marked un-obsoleted?

Michael.

**Comment by JakeGinnivan** [comment]
Good news, when I am splitting out Sql Server this looks like I will be reverting this decision.

**Comment by droyad** [comment]
@JakeGinnivan Do you remember the outcome of this? The method is still `Obsolete`.

**Comment by droyad** [comment]
The `IConnectionManager` manager overloads to the builder should support this scenario.
