### ISSUE TITLE
AdHocSqlRunner.ExecuteReader fails when output columns have no names

### ISSUE THREAD

**Issue by nvarscar** [DbUp/DbUp#390]
Any attempt to run an adhoc query with an output that has 2 or more columns without defined names fails with the following exception:
```
Exception calling "ExecuteReader" with "1" argument(s): "An item with the same key has already been added. Key: "
```
Since it returns dictionaries, it kind of makes sense, yet I cannot workaround that by assigning column names manually since they are defined in the DbUp code. Any chance those names could be generated automatically if missing? Like, Column1, Column2, etc. Other option would probably be to build `[System.Data.DataTable]` object instead of a set of dictionaries.

Test code (I totally realize this might not be an intended way to run AdHoc code, but that's all I have right now):
```powershell
$connectionString = 'Data Source=SQL1;User=sqldeploy;Password=sqldeploy;'
$dbUpConnection = [DbUp.SqlServer.SqlConnectionManager]::new($connectionString)
$dbUpSqlParser = [DbUp.SqlServer.SqlServerObjectParser]::new()
$managedConnection = $dbUpConnection.OperationStarting($null, $null)
$dbUpConnection.ExecuteCommandsWithManagedConnection( [Func[Func[Data.IDbCommand], System.Object]] {
    Param (
        $dbCommandFactory
    )
    $sqlRunner = [DbUp.Helpers.AdHocSqlRunner]::new($dbCommandFactory, $dbUpSqlParser, $null)
    $sqlRunner.ExecuteReader('SELECT 1, 2')
})
$managedConnection.Dispose()
```

Tested on v4.2.0.

**Comment by sungam3r** [comment]
Yes, I also noticed this behavior. In general, it is strange that they chose `List<Dictionary<string, string>>` on the return type.

**Comment by sungam3r** [comment]
Just run
```sql
select 1 as mycolumn, 2 as mycolumn 
```
and there will be an error.

**Comment by droyad** [comment]
Can I ask why you are using DBUp for this instead of ADO.NET directly?

**Comment by droyad** [comment]
I'm closing this because you can work around this by naming the columns uniquely and this is not core to the DBUp mission

**Comment by sungam3r** [comment]
> this is not core to the DBUp mission

In principle, I agree. There is no particular problem, just when reading the code I came across the possibility of this error. Since this is public API, it is probably worth reflecting this in the documentation for the method?

**Comment by droyad** [comment]
Good point
