### ISSUE TITLE
EnsureDatabase for Azure SQL fails

### ISSUE THREAD

**Issue by jkukan** [DbUp/DbUp#393]
Running `EnsureDatabase.For.SqlDatabase()` against Azure SQL database fails because of invalid command constructed by `SqlServerExtensions.SqlDatabase(this SupportedDatabasesForEnsureDatabase supported, string connectionString, IUpgradeLog logger, int timeout = -1, AzureDatabaseEdition azureDatabaseEdition = AzureDatabaseEdition.None, string collation = null)`. The problem seems to be:

`sqlCommandText = string.Format
(
  @"create database [{0}]{1};",
  databaseName,
  collationString
);`

where I can see semicolon being added in command text. However, it is followed by switch for Azure DB edition. So, the result command text I can see is:

`create database [DATABASE_NAME]; ( EDITION = ''basic'' );`

And it fails with:

`Incorrect syntax near 'EDITION'.'`

Thanks.

**Comment by dewalds** [comment]
Also getting this...

There should be no **semi-colon** after the ``CREATE DATABASE`` command as the breaks the subsequent Azure edition specification.

Command **should** look like this:
```sql
CREATE DATABASE dbname
COLLATE your_collation_name
( EDITION = 'GeneralPurpose' ) ;
```

The current code outputs this:
```sql
CREATE DATABASE dbname
COLLATE your_collation_name; --this semi-colon should not exist but is added by the preceding create database creation code
( EDITION = 'GeneralPurpose' ) ;
```

**Comment by sungam3r** [comment]
Waiting for merge...

**Comment by mrbit10** [comment]
I am getting something similar, Incorrect syntax near 'basic'.

`EnsureDatabase.For.SqlDatabase(connectionString, 300, AzureDatabaseEdition.Basic);`

```
System.Data.SqlClient.SqlException
  HResult=0x80131904
  Message=Incorrect syntax near 'basic'.
  Source=Core .Net SqlClient Data Provider
```

**Comment by sungam3r** [comment]
Could you provide executed script?

**Comment by mrbit10** [comment]
I would be happy to, what specific script, I am a bit green to this?
On 4/26/2022 12:09:28 AM, Ivan Maximov ***@***.***> wrote:
Could you provide executed script?

**Comment by mrbit10** [comment]
```
           var connectionString = config.GetConnectionString(dynamicDbConStr);

            EnsureDatabase.For.SqlDatabase(connectionString, 300, AzureDatabaseEdition.Basic);

            var upgrader =
                DeployChanges.To
                    .SqlDatabase(connectionString)
                    //.WithScriptsEmbeddedInAssembly(Assembly.GetExecutingAssembly())
                    .WithScriptsFromFileSystem(@dynamicPathConStr, new FileSystemScriptOptions
                    {
                        IncludeSubDirectories = true
                    })
                    //.WithTransactionPerScript()
                    .WithExecutionTimeout(TimeSpan.FromSeconds(300))
                    .LogToConsole()
                    //.JournalTo(new NullJournal())
                    .Build();
```
`Server=tcp: my .database.windows.net,1433;Initial Catalog=dbUpTest;User ID= my user ;Password= my password`

as far as the script that gets executed by dbup, it creates a stored procedure but i have tried different scripts, from creating tables with one column, it works if i leave off AzureDatabaseEdition.Basic 

so this errors
` EnsureDatabase.For.SqlDatabase(connectionString, 300, AzureDatabaseEdition.Basic);`  with Incorrect syntax near 'basic'. or if i change the edition it will say Incorrect syntax near 'standard'

however this works but in Azure it creates the wrong tier:
`EnsureDatabase.For.SqlDatabase(connectionString, 300);`

**Comment by sungam3r** [comment]
I mean SQL script like one provided here https://github.com/DbUp/DbUp/issues/393#issuecomment-474039926

**Comment by mrbit10** [comment]
Forgive my ignorance, I am not familiar in where i can get the executed SQL script output? Maybe i am missing something after the EnsureDatabase line?  I assumed as with my first tests dbUp successfully created the database from the connection string when it did not exist and then proceeded to execute the scripts in my path.   Again forgive my ignorance, point me in the right direction and I would be happy to get the SQL output.

**Comment by mrbit10** [comment]
please see my above comments
On 4/26/2022 1:13:00 AM, Ivan Maximov ***@***.***> wrote:
I mean SQL script like one provided here #393 (comment) [https://github.com/DbUp/DbUp/issues/393#issuecomment-474039926]

**Comment by sungam3r** [comment]
See this file https://github.com/DbUp/DbUp/pull/400/files

You may inspect `sqlCommandText` variable being under the debugging session. `ExecuteNonQuery` should throw exception you provided above. Turn off `enable just my code` switch and you'll be able to drill into DbUp.

**Comment by mrbit10** [comment]
Seems the SqlServerExtensions.cs i have is different
```
 public static void SqlDatabase(
    this SupportedDatabasesForEnsureDatabase supported,
    string connectionString,
    IUpgradeLog logger,
    int timeout = -1,
    AzureDatabaseEdition azureDatabaseEdition = AzureDatabaseEdition.None,
    string collation = null)
  {
    string masterConnectionString;
    string databaseName;
    SqlServerExtensions.GetMasterConnectionStringBuilder(connectionString, logger, out masterConnectionString, out databaseName);
    using (SqlConnection connection = new SqlConnection(masterConnectionString))
    {
      try
      {
        ((DbConnection) connection).Open();
      }
      catch (SqlException ex)
      {
        if (SqlServerExtensions.DatabaseExistsIfConnectedToDirectly(logger, connectionString, databaseName))
          return;
        throw;
      }
      if (SqlServerExtensions.DatabaseExists(connection, databaseName))
        return;
      string str = string.IsNullOrEmpty(collation) ? "" : " COLLATE " + collation;
      string cmdText = "create database [" + databaseName + "]" + str;
      switch (azureDatabaseEdition)
      {
        case AzureDatabaseEdition.None:
          cmdText += ";";
          break;
        case AzureDatabaseEdition.Basic:
          cmdText += " ( EDITION = ''basic'' );";
          break;
        case AzureDatabaseEdition.Standard:
          cmdText += " ( EDITION = ''standard'' );";
          break;
        case AzureDatabaseEdition.Premium:
          cmdText += " ( EDITION = ''premium'' );";
          break;
      }
      SqlCommand sqlCommand1 = new SqlCommand(cmdText, connection);
      ((DbCommand) sqlCommand1).CommandType = CommandType.Text;
      using (SqlCommand sqlCommand2 = sqlCommand1)
      {
        if (timeout >= 0)
          ((DbCommand) sqlCommand2).CommandTimeout = timeout;
        ((DbCommand) sqlCommand2).ExecuteNonQuery();
      }
      logger.WriteInformation("Created database {0}", (object) databaseName);
    }
  }
```
i apologize for being so green here, could you please provide me with an example in using ExecuteNonQuery with the EnsureDatabase statement?  Moreover, i did indeed disable` just my code` however in trying to inspect what i assume will be `cmdText `  which debug window would show the output in Visual Studio?  I do appreciate your time in helping.

**Comment by sungam3r** [comment]
If you have problems with debugging then you may just copy entire `SqlDatabase` method into you app and call it. It is easy.

**Comment by mrbit10** [comment]
here is the output:

CommandText "create database [dbUpTest] ( EDITION = ''basic'' );"


On 4/27/2022 12:40:21 PM, Ivan Maximov ***@***.***> wrote:
If you have problems with debugging then you may just copy entire SqlDatabase method into you app and call it. It is easy.

**Comment by sungam3r** [comment]
Do you get the same error if you execute `create database [dbUpTest] ( EDITION = ''basic'' );` command directly?

**Comment by mrbit10** [comment]
Yes, if i execute directly in SQL i get this message:

```
Msg 102, Level 15, State 1, Line 2
Incorrect syntax near 'basic'.

Completion time: 2022-05-02T16:08:35.3054115-05:00
```

**Comment by sungam3r** [comment]
Then apparently the bug has always been here. This raises questions for testing, of course. You may post a PR to fix this issue (for all editions cases I think). I do not know how quickly PR will be accepted and whether it will be accepted at all. Now this project is poorly supported.

**Comment by mrbit10** [comment]
okay, thank you very much for your help through this,  I will try a PR and see what happens.

**Comment by mrbit10** [comment]
Yes, if i execute directly in SQL i get this message:

Msg 102, Level 15, State 1, Line 2
Incorrect syntax near 'basic'.

Completion time: 2022-05-02T16:08:35.3054115-05:00
On 5/2/2022 4:06:27 PM, Ivan Maximov ***@***.***> wrote:
Do you get the same error if you execute create database [dbUpTest] ( EDITION = ''basic'' ); command directly?

**Comment by mrbit10** [comment]
Thank you very much for your help, please see my above post.
On 4/26/2022 2:04:51 AM, Ivan Maximov ***@***.***> wrote:
See this file https://github.com/DbUp/DbUp/pull/400/files [https://github.com/DbUp/DbUp/pull/400/files]
You may inspect sqlCommandText variable being under the debugging session. ExecuteNonQuery should throw exception you provided above. Turn off enable just my code switch and you'll be able to drill into DbUp.
