### ISSUE TITLE
DbUp.Postgresql bumping up the Npgsql-reference

### ISSUE THREAD

**Issue by unipeg** [DbUp/DbUp#394]
I would like to be able to use a more recent version of the Npgsql (current version as of writing is 4.0.4 (for net461)), but version 4.2.0 of dbup-postgresql wants version 3.2.6. So I get a assembly conflict as I reference other projects in my solution which requires a newer version than 3.2.6.
Fixable?

**Comment by sungam3r** [comment]
You can explicitly refer from your projects to a higher version of Npgsql . Then your application will use your version, not the version used by DbUp. Everything will work if version 4.0.4 does not break backward compatibility with 3.2.6.
