### ISSUE TITLE
Inconsistent SchemaVersions across db flavors

### ISSUE THREAD

**Issue by unipeg** [DbUp/DbUp#395]
There's an inconsistency in the schemas of the SchemaVersions table created between e.g. postgres and sqlserver variations:
In the postgres version it's name "schemaversionsid" whereas the sqlserver name is called plain "id".

I'm using DbUp in a project targetting multiple platforms, and I inspect the schemaversions table in some integration testing. This is causing me some troubles due to the inconsitency.

It seems sql server is the only variant that uses the short "id" as primary key column.

**Comment by AdrianJSClark** [comment]
I would guess that `schemaversionsid` was chosen to match a particular Postgres common format.

If you want to change for yourself, you can create your own class that implements `IJournal` based on the one that ships with DbUp and pass it to the `.JournalTo(…)` configuration method. The Postgres journal implementation is here: https://github.com/DbUp/DbUp/blob/master/src/dbup-postgresql/PostgresqlTableJournal.cs but most databases have their own version.

Obviously changing this in DbUp is going to be quite difficult. We'd need to decide how we support compatibility for existing users when they upgrade. I'm open to discussing options though.

**Comment by unipeg** [comment]
Thanks for the quick reply and the idea for a workaround.
I understand the concerns for pushing the change to the dbup-sqlserver package. It would imply performing a column name check and additional DDL statement to rename [id] to [schemaversionsid]. Not a very big risk, unless, obviously, someone access the data in SchemaVersions for inspection, as was the case for myself :).

**Comment by AdrianJSClark** [comment]
Glad I could be of help.

You are correct. I can think if a few other scenarios where changing the column name could trip people up as well. As I said, I would be happy to discuss if you wanted to push through the change. If the workaround is OK and you don't want to pursue larger changes, please close the issue.
