### ISSUE TITLE
Postgres schema trouble

### ISSUE THREAD

**Issue by unipeg** [DbUp/DbUp#396]
In my postgres db which I want to access through OrmLite, I have a schema, let's say "SchemaA". My entities have the Schema annotation of this same value.
My table, MyTable has a few columns:
ColumnA (varchar)
ColumnB (bool)

When I try to insert into a table under the schema, this SQL is created:

`INSERT INTO "SchemaA"."my_table" ("column_a","column_b") VALUES (:ColumnA, :ColumnB)`

and postgres complains that: 

> Relation "SchemaA.my_table" does not exist.

What might my problem be?

**Comment by maulik-modi** [comment]
This issue is unrelated to DbUp

Refer this link on how to write Insert query in Postgres
https://www.tutorialspoint.com/postgresql/postgresql_insert_query.htm
