### ISSUE TITLE
Statement of Oracle database support in docs

### ISSUE THREAD

**Issue by sungam3r** [DbUp/DbUp#397]
[There is no](https://github.com/DbUp/DbUp/blob/master/docs/supported-databases.md) Oracle

**Comment by peterdku** [comment]
To clarify the issue, the front page shows DbUp-Oracle but it is not mentioned in the ["supported databases"-documentation](https://dbup.readthedocs.io/en/latest/supported-databases/). What is the current state of oracle in dbup ?
