### ISSUE TITLE
Illogic condition inside WithExecutionTimeout extension method

### ISSUE THREAD

**Issue by sungam3r** [DbUp/DbUp#399]
This [line](https://github.com/DbUp/DbUp/blob/master/src/dbup-core/Builder/StandardExtensions.cs#L730) checks `0 > totalSeconds` (totalSeconds is double, not int) but message says `string.Format("The timeout value must be a value between 1 and {0} seconds", int.MaxValue)`. So should it be greater than 0 or 1?

This method accepts `Timespan`, converts it to double total seconds and then converts through `Convert.ToInt32` back to seconds. Consider call like this:
```c#
   DeployChanges.To.WithExecutionTimeout(TimeSpan.FromMilliseconds(300))
```
As a result, the test will be passed, and 0 will be set in the `ScriptExecutor.ExecutionTimeoutSeconds`. `IDbCommand.CommandTimeout` does not specify special meaning for zero timeout, but `SqlCommand.CommandTimeout` [do so](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlcommand.commandtimeout?view=netcore-2.0).

I guess that setting a timeout equal to zero has the same semantics in other database providers, but I will not say for sure. It seems to me that it is perfectly normal to let it be set to 0. Another thing is that then the aforementioned check should be corrected taking into account the rounding behaviour of `Convert.ToInt32`.

**Comment by droyad** [comment]
I think setting the timeout to 0 is valid. `(0 > totalSeconds)` would evaluated to false if `totalSeconds` was `0.0` or larger

**Comment by sungam3r** [comment]
> I think setting the timeout to 0 is valid.

I agree. There are no complaints about 0 timeout **value**. Another thing is that the error **message** is confusing. It should be
*The timeout value must be a value between 0 and {0} seconds*
instead of 
*The timeout value must be a value between 1 and {0} seconds*

**Comment by droyad** [comment]
Fixed
