### ISSUE TITLE
Suggestion: offer a possibility to rename the scripts before execution

### ISSUE THREAD

**Issue by marcscheuner-bfh** [DbUp/DbUp#401]
I would love to see a hook in DbUp that would allow me to plug in custom logic to rename the SQL script before it's being executed (and before its execution is being stored in the history table).

My use case is this: I have one DbUp project for the initial creation/setup of the database ("DbInitial"), and a second one that handles the incremental DB changes during ongoing development ("DbDev"). With embedded scripts, the names of the scripts being executed and recorded in the history table are defined primarily by the **actual project name** ("DbInitial" vs. "DbDev"). 

I wish I could "hook into" DbUp and ensure all the script names being recorded only have the official project name ("MyProject") as the basis - and I wouldn't mind also being able to "massage" the version number being stored.

Any hope such a feature might have been requested already, and is possibly in the works already?

**Comment by AdrianJSClark** [comment]
The way I'd achieve this would be a custom `IScriptProvider` which does the rename before creating and returning the `SqlScript` instance to the upgrade engine. Indeed, you could have your custom provider wrap the provider you currently use and create new `SqlScript` instances with the same content and modified names on the way through.

The existing script provider implementations are here: https://github.com/DbUp/DbUp/blob/master/src/dbup-core/Engine/SqlScript.cs

You would add your script provider by calling the `.WithScripts(...)` extension method on your configuration.

**Comment by brettveenstra** [comment]
@marcscheuner-bfh: Been using the `IScriptProvider` answer just like @AdrianJSClark mentioned ... note the `RunGroupOrder` for `SqlScriptOptions` in addition to whatever other sorting you need to do.
