### ISSUE TITLE
Question - Project Support Status

### ISSUE THREAD

**Issue by sungam3r** [DbUp/DbUp#404]
Hi! We have been using DbUp for quite a while. It so happened that our project required a deeper understanding of the library. Along the way, I had to look at the current status of the project, open issues/pull requests, etc.

Judging by the GitHub Insights graphs, there is an obvious stagnation in the development of the project since November last year. There are many open issues and pull requests even without comments from maintainers.

We are currently exploring the feasibility of continuing to use DbUp, fork it or migrate to other tools. Also there are some things that we would like to add / fix.

So I would like to understand the future development plans. Is this project abandoned or is it just a temporary break? I understand that everyone has his own business and everyone makes his own contribution.

Thanks!

**Comment by droyad** [comment]
@sungam3r Thank you for the interest and gentle inquiry.

I have sounded out my colleges at Octopus Deploy and we are happy to adopt and maintain this project as part of our normal work routine. I and another maintainer @jburger work there and this project originated with the Octopus CEO, Paul. We use this product internally and recommend it to our customers.

I have discussed this with some of the current maintainers, but I still need to get in touch with others. Pending a consensus, we'll make it official.

What will this mean for the project? Other than a gradual increase in momentum on the issues and PRs and the appearance of new faces, nothing else will change much. This org and repo will stay as is, and decisions will still be made in the open in this repo.

I'm happy to answer any questions.

**Comment by droyad** [comment]
Just realized this is issue 404. Fitting.

**Comment by sungam3r** [comment]
Thanks for the answer.

That is, do I understand correctly that in the near future it makes sense to continue to contribute to this repository? I have locally some set of changes related to the correction of errors and typos, and with the new functionality. As I said before, we use DbUp on an ongoing basis and would like to continue using it in our daily work, supporting the development and correction of errors.

**Comment by droyad** [comment]
Go for it, put up some PRs. If it's new functionality and it would require work to put into a PR, perhaps do up an Issue to discuss it before investing time in it.

**Comment by peterdku** [comment]
Any news regarding "making it offical" ?

**Comment by sungam3r** [comment]
> Go for it, put up some PRs.

Unfortunately PRs wait for months without a comment. It is very annoying and demotivates to develop the project further.

**Comment by Nik-Kudrin** [comment]
Any news, guys ?

**Comment by rain84** [comment]
> > Go for it, put up some PRs.
> 
> Unfortunately PRs wait for months without a comment. It is very annoying and demotivates to develop the project further.

It's annoing..
@AdrianJSClark , could your team to pay attention to this question, please?

**Comment by droyad** [comment]
@sungam3r @Nik-Kudrin @rain84 @p3t3rix Apologies for the delay. We (Octopus) have decided to invest our time in this project as we feel it's valuable. Unfortunately priorities have pulled us in a different direction for the last few months, but I expect to get some traction on PRs and Issues next week or the week after.

**Comment by sungam3r** [comment]
> Unfortunately priorities have pulled us in a different direction for the last few months

So maybe you should think about looking for new maintainers?

**Comment by jez9999** [comment]
Yeah I'd like to add my support to @sungam3r - the project should have a few maintainers added if OctopusDeploy are too busy to merge in the PRs.  I'm sure there are some people who are ready and willing.

**Comment by Justin-Aurizon** [comment]
Same here, I used DBUp years ago for a project and it was great.  Wanted to recommend it for a new one, but this doesn't bode well if the project is unsupported.

**Comment by felipeschneider88** [comment]
I will try to write a folk I know from OctopusDeploy to see what's going on and how we can help. I will keep you posted
