### ISSUE TITLE
How to write dbup migration with powershell for mysql

### ISSUE THREAD

**Issue by aravindkoniki** [DbUp/DbUp#407]
I want to execute mysql scripts with powershell. I didt find any documentation or code snippet for  mysql with powershell.

Can any one help me ?

**Comment by nvarscar** [comment]
Ch

**Comment by nvarscar** [comment]
Check out [dbops](https://github.com/sqlcollaborative/dbops) module. It uses DbUp libraries to performs cross platform sql deployments, including mysql. At the very least there would be some code examples to re-use.

**Comment by aravindkoniki** [comment]
Thanks, will check !!

**Comment by AdrianJSClark** [comment]
While this example isn't specific to MySQL, you can see the [basics of using DbUp with PowerShell in the documentation](https://dbup.readthedocs.io/en/latest/usage/#from-powershell). You just need to replace `SqlDatabase` function call with a call to `MySqlDatabase`.

**Comment by aravindkoniki** [comment]
Hi Adrian, thanks for helping me, it is specific to SQL server, which is working as expected. Main my problem is i cant able to identity the objects to be used for dbup powershell for mysql

**Comment by droyad** [comment]
@aravindkoniki I think you'll need to show us more information and your script so that we understand where you are stuck.

**Comment by aravindkoniki** [comment]
i cant able to work with  dbup migration for mysql, because i did find any sample in c# or powershell. In one my projects we have worked with MSSQL, so i have opted out to use dbup for MYSQL, but as i said i have not find any samples in powershell or c#
