### ISSUE TITLE
The Read The Docs link is broken

### ISSUE THREAD

**Issue by rdasan** [DbUp/DbUp#408]
I am really interested in making use of this project but documenation help would be nice :)
Can this be fixed https://dbup.readthedocs.io/ or is there a different link?

**Comment by AdrianJSClark** [comment]
That link worked when I clicked it. What error do you see?

--
Adrian Clark

adrian@ayds.com.au | @AdrianJSClark
________________________________

**Comment by jburger** [comment]
Hi @rdasan - What link are you referring to? The documentation page looks good from my machine.
