### ISSUE TITLE
DbUp When run in an already existing Database with CustomScriptsProvider

### ISSUE THREAD

**Issue by divyapai56** [DbUp/DbUp#419]
When I used DbUp for an existing DB, since the schema versions table does not have data, scripts which were run earlier are erroring out saying table already exists. 

Issue 2: When we run a create table script and after that when we run another alter table script, it says the table does not exist.

I am sending the scripts in an array format:

            var upgrader =
            DeployChanges.To
                .SqlDatabase(connectionString)
                .WithVariables(variables)
                .WithScripts(customScriptProvider.GetScripts())
                .WithoutTransaction()
                .LogToConsole()
                .Build();

**Comment by droyad** [comment]
Re the first issue, see https://github.com/DbUp/DbUp/issues/322#issuecomment-375601399

Re Issue 2, I would need to see your scripts. The best way would be to isolate the issue into a small console app and post the source on a GitHub repo.

**Comment by divyapai56** [comment]
Script 1:

CREATE TABLE [dbo].[Eng] (
    [EngId]               UNIQUEIDENTIFIER CONSTRAINT [DF_Eng_EngId] DEFAULT (newid()) NOT NULL,
    [Name]                       NVARCHAR (250)   NULL,
 CONSTRAINT [PK_Eng] PRIMARY KEY CLUSTERED ([EngId] ASC)
)
Script 2:

CREATE TABLE [dbo].[Alovera]
(
[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT newsequentialid(), 
[EngId] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [FK_Alovera_ToEng] FOREIGN KEY([EngId]) REFERENCES [dbo].[Eng] ([EngId]) 
)

The above are my 2 scripts,
And in my Program, I am calling it as :

 var upgrader =
            DeployChanges.To
                .SqlDatabase(connectionString, "dbo")
                .WithVariables(variables)
                .WithScripts(customScriptProvider.GetCreateScript())
                .LogToConsole()
                .Build();

The GetCreateScript is giving them in the Order 1 and 2.
When I do a  var result = upgrader.PerformUpgrade();, I get the following erroR:

Foreign key references invalid table.

**Comment by divyapai56** [comment]
> Re the first issue, see [#322 (comment)](https://github.com/DbUp/DbUp/issues/322#issuecomment-375601399)
> 
> Re Issue 2, I would need to see your scripts. The best way would be to isolate the issue into a small console app and post the source on a GitHub repo.

Thank you for your reply, I have posted the sample code in the comments for issue 2

**Comment by divyapai56** [comment]
> > Re the first issue, see [#322 (comment)](https://github.com/DbUp/DbUp/issues/322#issuecomment-375601399)
> > Re Issue 2, I would need to see your scripts. The best way would be to isolate the issue into a small console app and post the source on a GitHub repo.
> 
> Thank you for your reply, I have posted the sample code in the comments for issue 2

Resolved the issue 2 by adding RunGroupOrder

**Comment by divyapai56** [comment]
But I have another issue, I have 3 file streams and I want to change the default file stream from Primary to Secondary, but modifying asks me to add a file to the secondary filestream ('.mdf/.ndf' file).
Is there a way to automatically add this while creating the file stream?

**Comment by divyapai56** [comment]
var upgraderVnext = DeployChanges.To
                .SqlDatabase(connectionString)
                .WithVariables(variables)
                .WithScripts(customScriptProvider.GetUpgradeScript())
                .WithTransaction()
                .LogToConsole()
                .Build();

When I Use WithTransaction, I get the following error for the very first script or any alter script:

ALTER DATABASE [$TestDatabaseName$] 
SET AUTO_CREATE_STATISTICS ON (incremental  = ON)
GO

ALTER DATABASE [$TestDatabaseName$] 
SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [$TestDatabaseName$] 
SET AUTO_UPDATE_STATISTICS_ASYNC ON
GO

ALTER DATABASE [$TestDatabaseName$] SET CURSOR_DEFAULT LOCAL
GO

ALTER DATABASE [$TestDatabaseName$] SET RECOVERY SIMPLE 
GO


ALTER DATABASE [$TestDatabaseName$] SET PAGE_VERIFY CHECKSUM 
GO

ALTER DATABASE [$TestDatabaseName$]
SET ALLOW_SNAPSHOT_ISOLATION ON;
GO

ALTER DATABASE [$TestDatabaseName$]
SET READ_COMMITTED_SNAPSHOT ON;
GO

ALTER DATABASE [$TestDatabaseName$]
SET CHANGE_TRACKING = ON
(CHANGE_RETENTION = 2 DAYS, AUTO_CLEANUP = ON);

GO

ALTER DATABASE SCOPED CONFIGURATION
SET LEGACY_CARDINALITY_ESTIMATION = OFF;
 GO

 ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY
SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
 GO

  ALTER DATABASE SCOPED CONFIGURATION 
SET PARAMETER_SNIFFING = ON;
 GO

   ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY
SET PARAMETER_SNIFFING = PRIMARY;
 GO

   ALTER DATABASE SCOPED CONFIGURATION 
SET QUERY_OPTIMIZER_HOTFIXES = OFF;
 GO

    ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY
SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
 GO

 ALTER DATABASE SCOPED CONFIGURATION
 SET MAXDOP = 0;
 GO

 ALTER DATABASE [$TestDatabaseName$] SET MULTI_USER GO

**Comment by droyad** [comment]
>  I have 3 file streams and I want to change the default file stream from Primary to Secondary, but modifying asks me to add a file to the secondary filestream

This seems to be a SQL questions, StackOverflow is your best bet

> When I Use WithTransaction, I get the following error for the very first script or any alter script

I would run DB Up twice, the first time without transactions and only running your initial alter DB script. The second everything else.
