### ISSUE TITLE
LogToNowhere still auto-detects NLog

### ISSUE THREAD

**Issue by chambersDon** [DbUp/DbUp#420]
It seems the DbUp has auto-detected NLog event though I told it LogToNowhere().

This is my error:
_An error occurred creating the configuration section handler for nlog: Error loading extensions: Project.Web._

Here is the code:
```
var builder =
                DeployChanges.To
                    .SqlDatabase(connectString)
                    .LogToNowhere()
                    .WithScriptsEmbeddedInAssembly(Assembly.GetExecutingAssembly());

            var upgrader  = builder.Build();
```

The application does use NLog but this piece does not.  How do I get it to ignore Nlog?

I do have a Microsoft.Extensions.Loogging.ILogger I would like it to use, but no logging is fine.

**Comment by joaoportela** [comment]
Can't reproduce this.

I've even tried looking at the log setup code but everything seems fine.

Can you provide further context? Or a small sample application where this happens?
