### ISSUE TITLE
Add GetUnkownExectutedScripts or GetDiscoveredScripts to UpgradeEngine

### ISSUE THREAD

**Issue by joaoportela** [DbUp/DbUp#425]
I was trying to automatically detect a situation where I could have scripts in the SchemaVersions table that were run but aren't part of my scripts list.
(An example of when this might happen is if someone messed up and then deleted the script but the migration was already applied.)

Right now there is no way to directly get the "extra" scripts (hence the GetUnkownExectutedScripts suggestion) or even a bit indirectly by getting a list of the discovered scripts (GetDiscoveredScripts) that I could manually subtract from.

I think that adding one (or both) of these methods would make sense.

For now, I'll try and work around that by instanciating EmbeddedScriptProvider myself but getting it directly from the UpgradeEngine would make more sense (as it would always be in sync even if I change the UpgradeConfiguration).

**Comment by john-cullen** [comment]
This would also be helpful in situations where old code tries to run against new databases.

**Comment by RexTremendae** [comment]
I added a pull request for this, #453
