### ISSUE TITLE
Add a way to get UpgradeConfiguration from UpgradeEngineBuilder

### ISSUE THREAD

**Issue by joaoportela** [DbUp/DbUp#426]
In more complex usage scenarios (that aren't permitted by UpgradeEngine directly) I need to create an UpgradeConfiguration (or some of its parts) manually.

If I could get the UpgradeConfiguration directly from UpgradeEngineBuilder I could still configure everything using the handy fluent interface.

**Comment by droyad** [comment]
Apologies for the delay @joaoportela. The `UpgradeEngineBuilder.Configure` method is what you are looking for. It's what all the other configuration methods use in the end.

**Comment by joaoportela** [comment]
That would be great! 😃

**Comment by joaoportela** [comment]
I'm going to try and do this real quick. PR comming soon. :)
