### ISSUE TITLE
Azure Pipelines

### ISSUE THREAD

**Issue by dgrittma** [DbUp/DbUp#427]
I am attempting to run DbUp in Azure Pipelines like we do on-premise, but I'm receiving an error during execution. Is there a pre-req the Azure workers must have on them to run this package?

```The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.```

**Comment by droyad** [comment]
From the brief information you've given, it looks like your console app is not even starting. I suggest paring it down to the simplest thing (excluding DBUp) and go from there.
