### ISSUE TITLE
Contribute

### ISSUE THREAD

**Issue by Xhanti** [DbUp/DbUp#436]
Hi,

I would like to know if the up-for-grabs label is still the appropriate label to use when looking for issues to tackle?

I really like using this library and want to contribute back. If they are any other ways to find good issues or task for a first-time contributor please let me know.

Regards

**Comment by droyad** [comment]
@Xhanti I've updated the up-for-grabs, so yeh. #177 would be particularly useful. Which DBs are you familiar with?

**Comment by droyad** [comment]
Also another set of eyes and testing on the changes since the last release would be helpful.

**Comment by Xhanti** [comment]
@droyad  primarily sql server. I can take a stab at it and see what I come up with. Thank you for the feedback
