### ISSUE TITLE
Cannot find an overload for "SqlDatabase" and the argument count: "2"

### ISSUE THREAD

**Issue by nitinjain1005** [DbUp/DbUp#441]
Could you please assist me on below error message 

Cannot find an overload for "SqlDatabase" and the argument count: "2".
At line:8 char:1
+ $dbUp = [SqlServerExtensions]::SqlDatabase($dbUp, "server=$databaseServer;databa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest

I am using below code : 

$databaseName='localhost\SQLEXPRESS'
$databaseServer  ='TestDatabase'
$scriptPath ='..\PatchingScripts'

Add-Type -Path 'DbUp-master (2)\DbUp-Master\src\Samples\SampleApplication\bin\Debug\netcoreapp2.0\dbup-core.dll'

$dbUp = [DbUp.DeployChanges]::To
$dbUp = [SqlServerExtensions]::SqlDatabase($dbUp, "server=$databaseServer;database=$databaseName;Trusted_Connection=Yes;Connection Timeout=120;")

$dbUp = [StandardExtensions]::WithScriptsFromFileSystem($dbUp, $scriptPath)
$dbUp = [StandardExtensions]::LogToConsole($dbUp)
$dbUp = [StandardExtensions]::WithTransactionPerScript($dbUp)
$upgradeResult = $dbUp.Build().PerformUpgrade()

**Comment by AdrianJSClark** [comment]
The `SqlDatabase` extension method is located in the `dbup-sqlserver` project, so I suggest that you will need to load that DLL as well. Without that library, the `SqlServerExtensions.SqlDatabase(...)` method doesn't exist.

I strongly recommend that you build a console application which you call from your PowerShell that can build and execute your database upgrade. DbUp is really designed and tested to be used from C# and uses many extension methods to give a "fluent" feel. As evidenced by your sample above, extension methods translate poorly to PowerShell syntax.

**Comment by nvarscar** [comment]
> I strongly recommend that you build a console application which you call from your PowerShell that can build and execute your database upgrade. DbUp is really designed and tested to be used from C# and uses many extension methods to give a "fluent" feel. As evidenced by your sample above, extension methods translate poorly to PowerShell syntax.

This is true, DbUp is much more fitting into a C# application stack. A lot of functionality is locked behind understanding C# code and is not fully documented for Powershell usage. With that said, I've been working on a project which attempts to remediate this. Feel free to check out [DBOps](https://github.com/sqlcollaborative/dbops) Powershell module, which is 100% based on DbUp and introduces a bunch of functions that take care of building the DbUp object internally and only expose parameters needed for deployment.

**Comment by droyad** [comment]
@nvarscar Love it. I'd be happy to plug this project in the docs, or even put a whole page about it up.

**Comment by nitinjain1005** [comment]
Hi Thanks for nice explanation . @AdrianJSClark   .. There is some constraints I can't use exe.  

I updated code its working for on that steps..

In further lines I am getting below error message .

Upgrade failed due to an unexpected exception:
System.BadImageFormatException: Could not load file or assembly 'System.Data.SqlC
lient, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one 
of its dependencies. Reference assemblies should not be loaded for execution.  Th
ey can only be loaded in the Reflection-only loader context. (Exception from HRES
ULT: 0x80131058)
File name: 'System.Data.SqlClient, Version=4.1.0.0, Culture=neutral, PublicKeyTok
en=b03f5f7f11d50a3a' ---> System.BadImageFormatException: Cannot load a reference
 assembly for execution.
   at DbUp.SqlServer.SqlConnectionManager.<>c__DisplayClass0_0.<.ctor>b__0(IUpgra
deLog log, DatabaseConnectionManager dbManager)
   at DbUp.Engine.Transactions.DatabaseConnectionManager.OperationStarting(IUpgra
deLog upgradeLog, List`1 executedScripts)
   at DbUp.Engine.UpgradeEngine.PerformUpgrade()


issue : I tried to give path of dll from my my folder still it gives error message.. unable to understand at which location it is looking for dll.

My code is as below 

$databaseServer  =$args['localhost\SQLEXPRESS']  
$databaseName= $args['TestDatabase']
$scriptPath =  $args['C:\Project\cLAWin\cla\Customers\Seagull\Dev\Joshua\Src\cLA\Database\Deliveries\PatchingScripts']  



[Reflection.Assembly]::LoadFrom('C:\RND\PWSEHLL\DbUp-master\DbUp-master\src\dbup-sqlserver\bin\Release\netstandard1.3\dbup-sqlserver.dll')
[Reflection.Assembly]::LoadFrom('C:\RND\PWSEHLL\DbUp-master\DbUp-master\src\dbup-sqlserver\bin\Release\netstandard1.3\dbup-core.dll')
#[Reflection.Assembly]::LoadFrom('C:\RND\PWSEHLL\DbUp-master\DbUp-master\src\dbup-sqlserver\bin\Release\netstandard1.3\System.Data.SqlClient.dll')

$dbUp = [DbUp.DeployChanges]::To
$dbUp = [SqlServerExtensions]::SqlDatabase($dbUp,"server=$databaseServer;Database=$databaseName;Trusted_Connection=True;")
$dbUp = [StandardExtensions]::WithScriptsFromFileSystem($dbUp, $scriptPath)

$dbUp = [StandardExtensions]::LogToConsole($dbUp)
$upgradeResult = $dbUp.Build().PerformUpgrade()

**Comment by droyad** [comment]
@nvarscar yes
