### ISSUE TITLE
 System.BadImageFormatException: Could not load file or assembly 'System.Data.SqlC lient, Version=4.1.0.0

### ISSUE THREAD

**Issue by nitinjain1005** [DbUp/DbUp#442]
@AdrianJSClark  .. There is some constraints I can't use exe.

I updated code its working for on that steps..

In further lines I am getting below error message .

Upgrade failed due to an unexpected exception:
System.BadImageFormatException: Could not load file or assembly 'System.Data.SqlC
lient, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one
of its dependencies. Reference assemblies should not be loaded for execution. Th
ey can only be loaded in the Reflection-only loader context. (Exception from HRES
ULT: 0x80131058)
File name: 'System.Data.SqlClient, Version=4.1.0.0, Culture=neutral, PublicKeyTok
en=b03f5f7f11d50a3a' ---> System.BadImageFormatException: Cannot load a reference
assembly for execution.
at DbUp.SqlServer.SqlConnectionManager.<>c__DisplayClass0_0.<.ctor>b__0(IUpgra
deLog log, DatabaseConnectionManager dbManager)
at DbUp.Engine.Transactions.DatabaseConnectionManager.OperationStarting(IUpgra
deLog upgradeLog, List`1 executedScripts)
at DbUp.Engine.UpgradeEngine.PerformUpgrade()

**Issue : I tried to give path of dll from my my folder still it gives error message.. unable to understand at which location it is looking for dll.**

My code is as below

$databaseServer =$args['localhost\SQLEXPRESS']
$databaseName= $args['TestDatabase']
$scriptPath = $args['C:\Project\cLAWin\cla\Customers\Seagull\Dev\Joshua\Src\cLA\Database\Deliveries\PatchingScripts']

**#Reflection.Assembly::LoadFrom('C:\RND\PWSEHLL\DbUp-master\DbUp-master\src\dbup-sqlserver\bin\Release\netstandard1.3\System.Data.SqlClient.dll')**

$dbUp = [DbUp.DeployChanges]::To
$dbUp = [SqlServerExtensions]::SqlDatabase($dbUp,"server=$databaseServer;Database=$databaseName;Trusted_Connection=True;")
$dbUp = [StandardExtensions]::WithScriptsFromFileSystem($dbUp, $scriptPath)

$dbUp = [StandardExtensions]::LogToConsole($dbUp)
$upgradeResult = $dbUp.Build().PerformUpgrade()

**Comment by droyad** [comment]
Answered in #441. I suggest going to StackOverflow for HowTo questions.
