### ISSUE TITLE
Rows affected details 

### ISSUE THREAD

**Issue by ashikush** [DbUp/DbUp#450]
Hi Team,

i am new to DBUp. we are trying to implement it for our current deployment process.
i am able to execute scripts using DBUp way. but my client needs a detailed log, like how many rows affected during a successfully script execution.
can you help me to achieve this?

Thanks in advance.

**Comment by AdrianJSClark** [comment]
The best way would probably be to make sure that your script output gives the information you need and enable it to go to the logger by calling `.LogScriptOutput()` when building your upgrade configuration.

See ["Logging" in the DbUp docs](https://dbup.readthedocs.io/en/latest/more-info/logging/) for more information.

**Comment by ashikush** [comment]
hi Adrian, thanks for your reply.
i will try this way.
Let me know if there is any other way to get detailed log, because we have already 100 scripts i doubt DEV team will be updating all those scripts.

**Comment by AdrianJSClark** [comment]
Logging the script output [will include anything we get from the reader object](https://github.com/DbUp/DbUp/blob/master/src/dbup-core/Support/ScriptExecutor.cs#L193) that is returned from [the `ExecuteReader()` call](https://github.com/DbUp/DbUp/blob/master/src/dbup-core/Support/ScriptExecutor.cs#L178).

I can't ensure for you that will include the rows affected during the execution of any particular script. I'm not personally familiar enough with the reader object's edge cases. For example, I am not sure if the `RecordsAffected` property will include a total of all records impacted during the batch or just the most recent statement. That behaviour could also vary based on your database technology. You will have to test that and see if it meets your client's requirements.

I can't see anything additional that can be easily done with DbUp to help with your particular situation, so I'm closing this issue. Thanks for using DbUp and I hope I was able to give you some assistance.
