### ISSUE TITLE
pgsql - Journal table does not exist

### ISSUE THREAD

**Issue by ericbrumfield** [DbUp/DbUp#458]
Using 4.2.0, attempting to upgrade from sql files via dir path, when attempting to do update on a new empty pgsql 10 database I receive the 'Journal table does not exist' error.

My c# code:
```
var upgrader = DeployChanges.To.PostgresqlDatabase(_config.GetConnectionString("DefaultConnection"), "public")
                    .WithScriptsFromFileSystem(martenPatchDir.ParsedValue)
                    .JournalToPostgresqlTable("public", "SchemaVersions")
                    .LogToConsole()
                    .Build();

                var result = upgrader.PerformUpgrade();
```

**Comment by ericbrumfield** [comment]
As a work-around, and this appears to be working for me.  I manually created the schema versions table by running:

```
CREATE TABLE "SchemaVersions"
(
    schemaversionsid serial NOT NULL,
    scriptname character varying(255) NOT NULL,
    applied timestamp without time zone NOT NULL,
    CONSTRAINT "schemaversionsid" PRIMARY KEY (schemaversionsid)
)
```

Then I updated my c# code to the following:
```
var upgrader = DeployChanges.To.PostgresqlDatabase(_config.GetConnectionString("DefaultConnection"), "public")
                    .WithScriptsFromFileSystem(martenPatchDir.ParsedValue)
                    .JournalToPostgresqlTable("public", "SchemaVersions").WithVariablesDisabled()
                    .LogToConsole()
                    .Build();

                var result = upgrader.PerformUpgrade();
```

I've been able to successfully get this to work and execute my scripts in 4.2.0 against pgsql 10.  C# wise it wouldn't work under I added WithVariablesDisabled().

Feels hacky but as long as this works and I'm not sitting on a landmine doing this then I'll roll with it for now, I just need something that works.

**Comment by pswetz** [comment]
Same issue returns 
Checking whether journal table exists..
Journal table does not exist
No new scripts need to be executed - completing.

**Comment by mjauernig** [comment]
Closed due to age. If still needed, please reopen.
