### ISSUE TITLE
Add examples using Dapper

### ISSUE THREAD

**Issue by Odonno** [DbUp/DbUp#462]
Since Dapper is the favorite non-ORM choice for .NET developers to access the database, I would like to see a documentation on how to use DbUp with Dapper.

**Comment by sungam3r** [comment]
Maybe ADO.NET is the favorite non-ORM choice for .NET developers to access the database? :)

**Comment by Odonno** [comment]
The default one yes. The favorite well, without stats, it is pretty hard to tell. Still interesting to add a page in the docs about that. I can do it when I have some time.

**Comment by AdrianJSClark** [comment]
I certainly agree that Dapper is a great project. I'm just a little confused regarding what information you are after regarding DbUp and Dapper?

Personally I'd consider them two unrelated concerns, save for their common purpose of database interaction. DbUp is all about executing scripts once each before your app runs to implement an upgrade. Whereas Dapper is used during your application's execution to assist with data access.

Could you let us know what questions you have that the documentation might answer for you?

**Comment by Odonno** [comment]
That's because I read `Code-based scripts` on the documentation and I believe it was a common use-case. But it seems you can do pretty fine without Dapper. So, indeed, it is not that interesting after all.
