### ISSUE TITLE
Unable to find package dbup-core with version (>= 4.3.1)

### ISSUE THREAD

**Issue by pwelter34** [DbUp/DbUp#471]
When trying to update dbup-sqlserver to version 4.3.1, i get an error `Unable to find package dbup-core with version (>= 4.3.1)`.  If you [look under nuget](https://www.nuget.org/packages/dbup-sqlserver/), you'll see that it lists dbup-core version 4.3.1 as a dependence.  When you [look at dbup-core](https://www.nuget.org/packages/dbup-core/), there is not a version with that number.

**Comment by droyad** [comment]
Apologies, there was just a patch to the SQL server version and nothing in core so I only did a partial publish. I've now published core.
