### ISSUE TITLE
nuget package dbup-sqlserver 4.3.1 depends on unexisting nuget package dbup-core 4.3.1

### ISSUE THREAD

**Issue by emumanu** [DbUp/DbUp#472]
The current nuget package dbup-sqlserver 4.3.1 has the following dependencies:

.NETFramework 3.5
**dbup-core (>= 4.3.1)**

.NETFramework 4.6
**dbup-core (>= 4.3.1)**
Microsoft.Azure.Services.AppAuthentication (>= 1.3.1)

.NETStandard 1.3
**dbup-core (>= 4.3.1)**
NETStandard.Library (>= 1.6.1)
System.Data.SqlClient (>= 4.4.0)

.NETStandard 2.0
**dbup-core (>= 4.3.1)**
Microsoft.Azure.Services.AppAuthentication (>= 1.3.1)
System.Data.SqlClient (>= 4.6.0)

However, there is no dbup-core v4.3.1 published. The latest published one is 4.3.0

**Comment by droyad** [comment]
Done now
