### ISSUE TITLE
Variable substitution conflicts with PostgreSQL dollar-quoted strings

### ISSUE THREAD

**Issue by AnthonyMastrean** [DbUp/DbUp#484]
So, [dollar-quoted strings](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-DOLLAR-QUOTING) are a pretty common PostgreSQL thing. They're even part of the magic that makes [functions](https://www.postgresql.org/docs/current/sql-createfunction.html) work and are often nested, requiring the use of "tagged" quoted strings.

```
$function$
BEGIN
    RETURN ($1 ~ $q$[\t\r\n\v\\]$q$);
END;
$function$
```

If I need variable substitution in a PostgreSQL database project and have nested dollar-quoted strings, I can't just turn it off (see #288).

**Comment by Kharos** [comment]
We hit the same problem. As a workaround, put the following entry in your variable dictionary:
`{ "function", "$function$" }`
This will cause dbup's variable substitution to replace `$function$` with itself.

**Comment by AnthonyMastrean** [comment]
@Kharos hm, good tip, but I hope we can get a more robust fix 😅

**Comment by peterneave** [comment]
Duplicate of https://github.com/DbUp/DbUp/issues/484
