### ISSUE TITLE
EnsureDatabase.For.SqlDatabase(connectionString) Creates DB But Results in Exception

### ISSUE THREAD

**Issue by derek-baker** [DbUp/DbUp#489]
**EnsureDatabase.For.SqlDatabase(connectionString) Creates DB But Results in Exception When The Database Doesn't Exist.**

**DbUp Version:** 4.3.0 
**OS:** Windows 10
**DB:** SQL Server 19 running in Ubuntu Docker container & "bare metal" SQL instance on Windows.

Minimal example that reproduces bug (basically copy/pasted from DbUp docs): https://github.com/derek-baker/DbUp_Bug_Repro

Example error:
`Master ConnectionString => Data Source=localhost,1434;Initial Catalog=master;User ID=sa;Password=************
Database not found on server with connection string in settings: Cannot open database "TestDb" requested by the login. The login failed.
Login failed for user 'sa'.
Created database TestDb
Upgrade failed due to an unexpected exception:
System.Data.SqlClient.SqlException (0x80131904): Cannot open database "TestDb" requested by the login. The login failed.
Login failed for user 'sa'.`

**Same issue is referenced here:** https://stackoverflow.com/questions/60247206/ensuredatabase-fails-the-first-time-with-database-not-found-on-server-with-c

**Comment by enricoribelli** [comment]
@derek-baker thanks for opening this problem! Issue happens with latest (4.3.0 ?) release. Downgrade it to 4.0.0 and problem is solved!

**Comment by derek-baker** [comment]
Looks like the issue was in the dbup-sqlserver NuGet package (v4.3.0) and is resolved in v4.3.1.

**Comment by negatedx** [comment]
Just a point of clarification for anyone else that gets this issue.
I had the old pre 4.0 "dbup" package installed and the fix does not seem to have been applied there yet.
I removed the old package in favour of the separate "db-core" and "db-sqlserver" packages and it's working again.
