### ISSUE TITLE
need to use custom journal table

### ISSUE THREAD

**Issue by sabir-piludiya** [DbUp/DbUp#499]
How exactly JournalToSqlTable() works. I have to use custom journal table instead of schemaversions. Is it possible?

**Comment by AdrianJSClark** [comment]
Hi @sabir-piludiya,

Plugging in a custom journal implementation is not too difficult.

First you must implement a class that has the [`IJournal` interface](https://github.com/DbUp/DbUp/blob/master/src/dbup-core/Engine/IJournal.cs) which provides the custom logic you need to run.

Next you register your custom class using the [`JournalTo` configuration method](https://github.com/DbUp/DbUp/blob/master/src/dbup-core/Builder/StandardExtensions.cs#L120).

So if you create a new class called `MySpecialJournal` you might register it like this:

```csharp

    var upgrader =
        DeployChanges.To
            .SqlDatabase(connectionString)
            .WithScriptsEmbeddedInAssembly(Assembly.GetExecutingAssembly())
            .LogToConsole()
            .Journalto(new MySpecialJournal()) // New line configuring our journal
            .Build();

```

There is also an [advanced version of `JournalTo`](https://github.com/DbUp/DbUp/blob/master/src/dbup-core/Builder/StandardExtensions.cs#L133) which allows you to participate in transactions, if you require that functionality. See 

Let me know if this isn't clear or feel free to close the issue.
