### ISSUE TITLE
Have to execute only selected script

### ISSUE THREAD

**Issue by sabir-piludiya** [DbUp/DbUp#501]
I need to only execute selected scripts from the directory where list of scripts are there. Which Script Provider should I use for that and How?

**Comment by AdrianJSClark** [comment]
Hi @sabir-piludiya!

I was going to point you to the documentation, however our documentation is lacking in this area.

I think that I've fixed it up and you can view my change here until the PR is merged: https://github.com/AdrianJSClark/DbUp/blob/improve-filesystem-documentation-501/docs/more-info/script-providers.md#filesystemscriptprovider

The short answer is that you call `.WithScriptsFromFileSystem(...)` with both the path you your folder and a filter function of type `Func<string, bool>`. Your filter function will be called for each ".sql" file path located by the provider and if you do not wish it to be included simply return `false`.
