### ISSUE TITLE
Preprocessor Implementation

### ISSUE THREAD

**Issue by sabir-piludiya** [DbUp/DbUp#503]
I need to implement **preprocessor**. I know there's one method called Process() having argument as content. 
I'm using sql scripts WithScripts() as below to pass scripts in builder: 

```
WithScripts(new[]
{
  new SqlScript("script1.sql", "content"),
  new SqlScript("script2.sql", "content2")
}
```

I need to preprocess the content in Custom Preprocessor class using IScriptPreprocessor based on requirement.
I have not found any proper documentation or resources. How should I use preprocessor?

**Comment by AdrianJSClark** [comment]
I'm not sure what question you're asking or where you are having trouble here.

A preprocessor can do almost anything to the content that it likes. You just inspect the content given in the parameter and return. You can find examples in the [Preprocessors folder of the source](https://github.com/DbUp/DbUp/tree/master/src/dbup-core/Engine/Preprocessors). The Variable Substitution PreProcessor (which replaces placeholder text with values) and a Strip Schema Processor (which removes a particular default variable placeholder for certain databases).
