### ISSUE TITLE
"Authentication method 'caching_sha2_password' not supported by any of the available plugins."

### ISSUE THREAD

**Issue by garethrbrown** [DbUp/DbUp#510]
I'm attempting to set up dbup in a .netcore 3.1 project running against a MySql database. This is the error message I get in the result from ```PerformUpgrade``` when trying to run the following code against the package versions below:

"Authentication method 'caching_sha2_password' not supported by any of the available plugins."

<PackageReference Include="DbUp" Version="4.2.0" />
<PackageReference Include="dbup-mysql" Version="4.2.0" /

When running against the latest versions

<PackageReference Include="DbUp" Version="4.4.0" />
<PackageReference Include="dbup-mysql" Version="4.4.0" />

I simply get a NullReferenceException

    class Program
    {
        static int Main(string[] args)
        {
            var environmentName = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT");

            var configuration = ConfigurationReader.GetConfiguration(environmentName);

            string connectionString = configuration.GetValue<string>("App:Db:ConnectionStrings:Default");

            var upgrader = DeployChanges.To
                            .MySqlDatabase(connectionString)
                            .WithScriptsEmbeddedInAssembly(Assembly.GetExecutingAssembly())
                            .LogToConsole()
                            .Build();

            var result = upgrader.PerformUpgrade();

            if (!result.Successful)
            {
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine(result.Error);
                Console.ResetColor();
    #if DEBUG
                Console.ReadLine();
    #endif
            }

            Console.ForegroundColor = ConsoleColor.Green;
            Console.WriteLine("Success!");
            Console.ResetColor();

            return 0;
        }
    }

**Comment by garethrbrown** [comment]
Found the issue. I hadn't added the MySql.Data package to the project. I had assumed that this might be bundled with dbup-mysql.

So I now have:

<PackageReference Include="DbUp" Version="4.4.0" />
<PackageReference Include="dbup-mysql" Version="4.4.0" />
<PackageReference Include="MySql.Data" Version="8.0.15" />

**Comment by nightblade9** [comment]
If anyone reads this and is wondering about PostgresQL (I was), the solution is to add the `Npgsql` package to your project - problem solved. (The error message is slightly different: "Authentication method not supported (received 10)"
