### ISSUE TITLE
Shouldn't this be disposed?

### ISSUE THREAD

**Issue by pitermarx** [DbUp/DbUp#524]
https://github.com/DbUp/DbUp/blob/a0a9c6ddbe2c107d13f7e66e319248ede0709ce6/src/dbup-core/Engine/Transactions/DatabaseConnectionManager.cs#L71

**Comment by PeteBoyRocket** [comment]
I agree, I think it should be disposed too. Like this? https://github.com/DbUp/DbUp/pull/529

**Comment by sungam3r** [comment]
Already desposed in `master`.
