### ISSUE TITLE
DB Backup prior to execute any script

### ISSUE THREAD

**Issue by ashikush** [DbUp/DbUp#530]
HI Team,

i wanted to know if there is any functionality which will trigger a backup before executing any script in current db in DBUp.
so my condition is
if there are new scripts to execute, trigger a backup first and then execute new scripts.
if there are no new script to execute, do not trigger any db backup.

thanks,
Ashi

**Comment by TroyWitthoeft** [comment]
There is functionality for always running scripts.  There is functionality for running scripts in an order.  Why not create a SQL Script to backup the database?   Make it first, and set it to always run.

**Comment by sungam3r** [comment]
Closed as answered.
