### ISSUE TITLE
Where is dbup-core 4.5.0?

### ISSUE THREAD

**Issue by sungam3r** [DbUp/DbUp#541]
https://www.nuget.org/packages/dbup-oracle/ - 4.5.0 in dependencies

https://www.nuget.org/packages/dbup-core/ - only 4.4.0

**Comment by sungam3r** [comment]
@droyad , @AdrianJSClark ?

**Comment by avantia-cts** [comment]
I agree with this. Getting the following error:

Install-Package : NU1102: Unable to find package dbup-core with version (>= 4.5.0)
  - Found 13 version(s) in nuget.org [ Nearest version: 4.4.0 ]
  - Found 13 version(s) in nuget.org v2 [ Nearest version: 4.4.0 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
  - Found 0 version(s) in DevExpress
At line:1 char:1
+ Install-Package DbUp
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for 'Avantia.Kalyke.Web'.
At line:1 char:1
+ Install-Package DbUp
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by AdrianJSClark** [comment]
Apologies @sungam3r, @avantia-cts & anyone else hitting this issue. Unfortunately I don't have access to the CI/CD or NuGet publishing pipelines. I'm sure @droyad will work out what went astray shortly and resolve it.

**Comment by sungam3r** [comment]
Done.
