### ISSUE TITLE
Deleting a SqlServer database is slow in .NET Core with connection pooling

### ISSUE THREAD

**Issue by tcihak-fqa** [DbUp/DbUp#553]
Hello,

I have unit tests that create and delete SQL Server databases in .NET Core.
Deleting the database in .NET Core takes up to 30 seconds to complete. (DropDatabase.For.SqlDatabase)
However, if connection pooling is disabled, the database deletion performance is good.
I added a call to SqlConnection.ClearAllPools() before the deleting the database and that didn't improve performance.
Is this a bug in DbUp or .NET Core?
Thanks.

**Comment by pghdeveloper** [comment]
@tcihak-fqa  How big is your database?

**Comment by tcihak-fqa** [comment]
I can repro the issue with no records in the database.
The database schema has 70 tables.

**Comment by MollsAndHersh** [comment]
I'm no expert, but I've found this to be quick and effective in dropping a database: context.Database.EnsureDeleted(); ... might give it a try.

**Comment by tcihak-fqa** [comment]
Thanks. I just tried it and it is still slow.
I'm thinking the issue is in the SQL provider and not DbUp.

**Comment by sungam3r** [comment]
> I'm thinking the issue is in the SQL provider and not DbUp.

I think so. Please reopen if issue is still actual.
