### ISSUE TITLE
Add Azure Gov as option for Azure Sql Integrated Security.  

### ISSUE THREAD

**Issue by chrismcclure** [DbUp/DbUp#555]
We are using Azure gov and I noticed the database token access url is hardcoded in the SqlConnectionManger.  The Azure gov url is https://database.usgovcloudapi.net.  

So either add another parameter for gov, overloaded method for gov, or a way to pass our own token or make the url configurable.  Any options would solve the problem. 

![image](https://user-images.githubusercontent.com/13955327/106625139-01f1d080-653c-11eb-976e-795090c0e4cc.png)

**Comment by AdrianJSClark** [comment]
There's a PR up that I hope will resolve this issue.

I don't have a means of testing these changes properly, @chrismcclure, so it would be great if you could have a look at that PR to see if it looks like what you need.

**Comment by chrismcclure** [comment]
Thanks guys.  Another problem solved.
