### ISSUE TITLE
Scripts prepared by IScriptProvider.GetScripts don't recognize objects created in previous steps

### ISSUE THREAD

**Issue by dibyamani** [DbUp/DbUp#579]
I am getting an issue like object not found if I define table creation script in 1 script and data feed on that table on another script.
The object which is created with earlier steps is not recognized in second script.
For example:
Script1.sql
CREATE TABLE AppUser(UserID INT, UserName NVARCHAR(100));
GO

Script2.sql
INSERT AppUser(UserID, UserName) VALUES(1, 'Dibya');
GO

Here, I get AppUser doesn't exists exception while executing Script2.sql using following way

public class SetupScriptProvider : BaseScriptProvider, IScriptProvider
    {
        public IEnumerable<SqlScript> GetScripts(IConnectionManager connectionManager)
        {
            yield return GetScriptFromResource(this, "Script1.sql"); //this method retrieves scripts stored as embedded resources
            yield return GetScriptFromResource(this, "Script2.sql"); //this method retrieves scripts stored as embedded resources
        }
    }

**Comment by mjauernig** [comment]
Closed due to age of issue creation. If still needed, please reopen.
