### ISSUE TITLE
DbUp compatibility with .Net Core

### ISSUE THREAD

**Issue by shirishtayshete** [DbUp/DbUp#581]
Hi All,

I have DbUp library for Sql up and running in Net framework; however, doesn't look like there is one for .Net core yet?

Regards,
Shirish

**Comment by AdrianJSClark** [comment]
Hi @shirishtayshete,

DbUp works fine on .NET 5, .NET Core, and .NET Framework. You should be able to just install & go.

**Comment by Havunen** [comment]
Is there any possibility to have .Net 6 compilation target targetFramework added to this nuget

**Comment by mjauernig** [comment]
I think we can close this. You can add the package to a .net6 or .net7 project.
