### ISSUE TITLE
DbUp not seeing changes in SQL scripts

### ISSUE THREAD

**Issue by furyd** [DbUp/DbUp#585]
Hi, got an issue where DeployChanges isn't seeing any changes to deploy.

### Details
Project: Console app in .NET Core 3.1, using dbup-mysql
Structure: Scripts folder, broken down by subfolder type (table, sprocs, etc) subfolders and scripts prefixed with a number to control execution order

All scripts have a Build Action of Embedded Resource, and Copy to Output Directory is set Do Not Copy

### Code
Main in Program.cs

`private static int Main()
        {
            _configuration = BuildConfiguration();
            var services = ConfigureDependencies(_configuration);

            var connectionStringSettings = services.GetRequiredService<IOptions<DatabaseSettings>>();

            var connectionString = connectionStringSettings?.Value?.ConnectionString ?? throw new Exception("No database settings found");

            EnsureDatabase.For.MySqlDatabase(connectionString);

            var upgradeEngine = DeployChanges
                .To.MySqlDatabase(connectionString)
                .WithScriptsEmbeddedInAssembly(Assembly.GetExecutingAssembly())
                .LogToConsole()
                .Build();

            var result = upgradeEngine.PerformUpgrade();

            if (!result.Successful)
            {
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine(result.Error);
                Console.ResetColor();
                return -1;
            }

            Console.ForegroundColor = ConsoleColor.Green;
            Console.WriteLine("Success!");
            Console.ResetColor();
            return 0;
        }`

### Scenario

Update test.sql from

`CREATE TABLE professionals (
  Id int NOT NULL AUTO_INCREMENT,
  Name varchar(256) NULL,
  PRIMARY KEY (Id)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;`

To

`CREATE TABLE `professionals` (
  Id int NOT NULL AUTO_INCREMENT,
  Name varchar(256) NOT NULL,
  PRIMARY KEY (Id)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;`

And run program.

### Behaviour

Expected action: changed script ran and field in database changed to being NULLable
Actual action: No script changes detected, therefore no scripts ran, therefore no changes to the database schema.

Is this a bug, or is there something I'm missing?

**Comment by bkuzmacissp** [comment]
I'm observing the same type of issue, except in my case the scripts are executing in my desktop dev environment, but not running in my production environment. I'm still puzzling through the differences between the environments.

**Comment by jafin** [comment]
@furyd ,  I don't think DbUp has an option to detect scripts changes.  If the original execution of the script passed without error it would have written to the journal table, and therefore will not execute the script again (even if changed).

So if you want to rerun an already executed script you'd need to remove the entry from the journaling table, 'SchemaVersions' 
i.e.

```sql
delete from SchemaVersions where ScriptName = 'yourscriptname';
```

**Comment by AdrianJSClark** [comment]
@jafin is correct that this isn't a feature of DbUp and that you'd need to either remove the script from the `SchemaVersions` table or change the script name to have a changed script executed again.

**Comment by sungam3r** [comment]
Maybe add a hashing feature which detect changes and warn user about changes? It can be optional.

**Comment by jafin** [comment]
#277

**Comment by furyd** [comment]
@jafin thanks for the explanation, I'll close this for now and take a look again when the hashing is implemented.

One thing I'd note with the hashing, would be nice to also strip out whitespace so tidying up scripts doesn't trigger a deployment.
