### ISSUE TITLE
[Feature Request]  Bump BuildTools to 2019 (from 2017)

### ISSUE THREAD

**Issue by jafin** [DbUp/DbUp#588]
As a dev, it would be great to avoid having to install 2017 build tools and use something more current like vs2019 tools
so that I can build the project from the build script without having to install 2017 on a dev machine.

Is there anything that would block building on VS2019 tools?
Would consider bumping Cake to 1.2 along with this.

**Comment by sungam3r** [comment]
CI was migrated to GitHub Actions and NET7 SDK.

**Comment by jafin** [comment]
Thanks for renewing the project @sungam3r !
