### ISSUE TITLE
DbUp Delimiter Issue

### ISSUE THREAD

**Issue by rphelps39** [DbUp/DbUp#596]
I'm attempting to use DbUp with procedures in my Oracle database. I have a dbup powershell script that uses the OracleDatabaseWithDefaultDelimiter "/". This is working for most scripts but some of my procedures contain division which uses the same symbol as the delimiter "/". Changing the delimiter to a ";" doesn't work for my application as most of my other scripts contain semi colons regularly. Is there a work around for this? dbupdotnetversion = 45
Thank you in advance!

**Comment by sungam3r** [comment]
Check [this](https://github.com/DbUp/DbUp/search?q=DELIMITER). Something like 
```
...
DELIMITER ~~~
...
```
may help you.

**Comment by sungam3r** [comment]
Closed due to inactivity.
