### ISSUE TITLE
Timeout when creating Stored Procedure containing linked server (SQL Server 2019)

### ISSUE THREAD

**Issue by dbruk9** [DbUp/DbUp#610]
When I have `builder.WithTransactionPerScript()` , executing scripts that create stored procedures time out.  The same scripts run fine in SQL Server Management Studio.
If I set builder to `builder.WithoutTransaction()`, it executes without any issues. 
I've tried debugging with DbUp source but I don't see anything specific stand out that would cause this. Any thoughts?

I am using SQL Server and DbUp v4.5.0.

**Comment by shishankexate** [comment]
Try using `.WithExecutionTimeout(TimeSpan.FromSeconds(300))`

**Comment by sungam3r** [comment]
Closed due inactivity.
