### ISSUE TITLE
4.6.0 release

### ISSUE THREAD

**Issue by sungam3r** [DbUp/DbUp#612]
The last v4.5.0 was published 20.11.2020. 12 commits on `master` since then including bug fixes. @AdrianJSClark @droyad please publish fresh 4.6.0 release.

Also I want to remind you about #404. I'm still ready to help you to maintain this repo - code review/merging/CI stuff/publishing releases/answering questions. Yes, this project will not be the main one, which I help, but nevertheless the situation can move away from the dead point.

**Comment by Ekkeir** [comment]
Are there any plans on release?
Some of the bug fixes would be beneficial for us.

**Comment by AdrianJSClark** [comment]
Sorry, on my part I know the codebase and am able to merge but I don't think I've got access to make a release happen.

**Comment by sungam3r** [comment]
@AdrianJSClark could you please contact @droyad or other maintainer you know directly?

**Comment by droyad** [comment]
Sorry @AdrianJSClark, I've now given you access. I'll have a review of the commits and make a release this week.

**Comment by droyad** [comment]
I had a look, and unfortunately we have some [breaking changes](https://github.com/DbUp/DbUp/pull/559/files#diff-ca3aece64f9430707ed273367a9968bd2cc9d8d50e67d147cfdd92be9c26097bL34-L55) we'll need to revert first

**Comment by droyad** [comment]
![giphy](https://user-images.githubusercontent.com/1687639/166901510-9cd37761-7c72-4229-8a91-75db771bb942.gif)
