### ISSUE TITLE
How do I only rollback transaction in SQL Server if there is an error while deploying the scripts?

### ISSUE THREAD

**Issue by shishank-jain** [DbUp/DbUp#613]
```
var upgrader = DeployChanges.To
                            .SqlDatabase(connectionString)
                            .WithExecutionTimeout(TimeSpan.FromSeconds(300))
                            .WithTransactionAlwaysRollback()    
                            .WithScriptsFromFileSystem(rootPath, new FileSystemScriptOptions { IncludeSubDirectories = true });

var result = upgrader.PerformUpgrade();

if (!result.Successful)
{
//Now I want to do transaction rollback of the complete session
}
```
Using 'TransactionAlwaysRollback()', transactions are rolled back irrespective of the success or failure of the scripts. I only want to roll back when any one of the scripts fail during deployment. Is there any other way to do it?

**Comment by sungam3r** [comment]
Use external transaction on your side?

**Comment by shishankexate** [comment]
What do you mean by external transaction? Can you please share any resource?

**Comment by sungam3r** [comment]
I mean transaction that you create manually - https://docs.microsoft.com/en-us/dotnet/api/system.transactions.transactionscope?view=net-6.0#examples so all DbUp code is executed inside that implicit transaction. After that you may check some conditions you would like and commit or rollback transaction.

**Comment by shishank-jain** [comment]
simply used WithTransaction(). That rolled back the transaction automatically when there is an error. @sungam3r
