### ISSUE TITLE
Plan for v6.0

### ISSUE THREAD

**Issue by droyad** [DbUp/DbUp#632]
This is the high level plan for the next major for DbUp. The list will be updated as it evolves, so please quote the parts you are replying to. 

**We want your input into this plan**, post below

I'll also post updates as this progresses.

# Plan

## Step 1 Lay the groundwork

- Split the providers into different repos #431 
    - Do it for one provider first: https://github.com/DbUp/dbup-redshift/pull/3
    - Create a template
    - Repeat for the rest
    - Create a dbup-core repo?
- Explore widening ownership over specific providers to technology area experts (e.g. someone using Oracle daily)
- Move Issues and PRs to where they belong

## Step 2 Modernise

- #432
- Update dependencies
- Remove deprecated features
- Async support
- Largely aim to keep API compatibility so upgrade isn't a large hurdle

## Step 3
- Triage the Issue list and tag `up for grabs` items
- Get to addressing the Issues/PRs

# v6.0 and later
- Major new features
- Refactor/restructuring of the API

**Comment by droyad** [comment]
## Update 
First provider has been split out (https://github.com/DbUp/dbup-redshift/pull/3). Looking at making this the template, so taking time to make it look right (see open PRs in https://github.com/DbUp/dbup-redshift/pulls)

Completed: #615 (GH Actions) and #621 (Mainline versioning)

**Comment by jburger** [comment]
High-level plan looks good, I am interested to know more about the list of deprecated features we're thinking about shelving too.

**Comment by droyad** [comment]
> deprecated features

Primarily anything with `[Obsolete]` and any overloads we've had to add to keep binary compatibility.
