### ISSUE TITLE
Read the Docs is outdated

### ISSUE THREAD

**Issue by Leosori** [DbUp/DbUp#635]
'Latest' is not showing the current content of the master branch
https://dbup.readthedocs.io/en/latest/

The last update was more than 3 years ago. I guess the triggers/webhooks are broken?
https://readthedocs.org/projects/dbup/builds/

For example, a lot of the 'more info' docs are missing.

**Comment by flatrick** [comment]
(moved this comment from a different ticket, I commented on the wrong thing.. sorry about that!)

Going through the docs on Read The Docs own [readme](https://docs.readthedocs.io/en/stable/intro/getting-started-with-mkdocs.html) , they suggest pinning all requirements to ensure the build will always work

Just tried it and had it working with a requirements.txt that looks like this: (ever so slightly updated from one of ReadTheDocs.org's own samples)

```yaml
#
# This file is autogenerated by pip-compile with python 3.10
# To update, run:
#
#    pip-compile docs/requirements.in
#
click==8.1.3
    # via mkdocs
ghp-import==2.1.0
    # via mkdocs
griffe==0.22.0
    # via mkdocstrings-python
importlib-metadata==4.12.0
    # via mkdocs
jinja2==3.1.2
    # via
    #   mkdocs
    #   mkdocstrings
markdown==3.3.7
    # via
    #   markdown-include
    #   mkdocs
    #   mkdocs-autorefs
    #   mkdocstrings
    #   pymdown-extensions
markdown-include==0.6.0
    # via -r docs/requirements.in
markupsafe==2.1.1
    # via
    #   jinja2
    #   mkdocstrings
mergedeep==1.3.4
    # via mkdocs
mkdocs==1.4.2
    # via
    #   -r docs/requirements.in
    #   mkdocs-autorefs
    #   mkdocstrings
mkdocs-autorefs==0.4.1
    # via mkdocstrings
mkdocstrings[python]==0.19.0
    # via
    #   -r docs/requirements.in
    #   mkdocstrings-python
mkdocstrings-python==0.7.1
    # via mkdocstrings
packaging==21.3
    # via mkdocs
pymdown-extensions==9.5
    # via mkdocstrings
pyparsing==3.0.9
    # via packaging
python-dateutil==2.8.2
    # via ghp-import
pyyaml==6.0
    # via
    #   mkdocs
    #   pyyaml-env-tag
pyyaml-env-tag==0.1
    # via mkdocs
six==1.16.0
    # via python-dateutil
watchdog==2.1.9
    # via mkdocs
zipp==3.8.0
    # via importlib-metadata
```

**Comment by KUTlime** [comment]
I think that @Leosori is right and this is a serious problem.

![image](https://user-images.githubusercontent.com/8374320/213688170-d494516b-b0ae-4316-bd44-4fd220269e4b.png)

**Comment by droyad** [comment]
This has been fixed
