### ISSUE TITLE
Release notes link seems to be outdated

### ISSUE THREAD

**Issue by flcdrg** [DbUp/DbUp#639]
The release notes link in the NuGet packages points to the GitHub Releases page here in the repo, but it looks like you're not using that for releases any more?

Is there somewhere else that this link should be pointing to?

**Comment by flatrick** [comment]
I just tried to setup a RTD.org with MkDocs myself, there seems to be an issue with one of the python packages needed to build.
A quick fix would be to add a `requirements.txt` to the `\docs` folder with this inside:

`jinja2<3.1.0`

It was all I needed to do atleast to get MkDocs building properly through ReadTheDocs.org

**Comment by flatrick** [comment]
@AdrianJSClark I see that you've been quite busy, since this is such a simple fix, perhaps you could try my suggestion above?
I just double-checked and the docs-page is still showing an older version

- https://dbup.readthedocs.io/en/latest/supported-databases/
- https://github.com/DbUp/DbUp/blob/master/docs/supported-databases.md

**Comment by flatrick** [comment]
Going through the docs on Read The Docs own [readme](https://docs.readthedocs.io/en/stable/intro/getting-started-with-mkdocs.html) , they suggest pinning all requirements to ensure the build will always work

Just tried it and had it working with a requirements.txt that looks like this: (ever so slightly updated from one of ReadTheDocs.org's own samples)

```yaml
#
# This file is autogenerated by pip-compile with python 3.10
# To update, run:
#
#    pip-compile docs/requirements.in
#
click==8.1.3
    # via mkdocs
ghp-import==2.1.0
    # via mkdocs
griffe==0.22.0
    # via mkdocstrings-python
importlib-metadata==4.12.0
    # via mkdocs
jinja2==3.1.2
    # via
    #   mkdocs
    #   mkdocstrings
markdown==3.3.7
    # via
    #   markdown-include
    #   mkdocs
    #   mkdocs-autorefs
    #   mkdocstrings
    #   pymdown-extensions
markdown-include==0.6.0
    # via -r docs/requirements.in
markupsafe==2.1.1
    # via
    #   jinja2
    #   mkdocstrings
mergedeep==1.3.4
    # via mkdocs
mkdocs==1.4.2
    # via
    #   -r docs/requirements.in
    #   mkdocs-autorefs
    #   mkdocstrings
mkdocs-autorefs==0.4.1
    # via mkdocstrings
mkdocstrings[python]==0.19.0
    # via
    #   -r docs/requirements.in
    #   mkdocstrings-python
mkdocstrings-python==0.7.1
    # via mkdocstrings
packaging==21.3
    # via mkdocs
pymdown-extensions==9.5
    # via mkdocstrings
pyparsing==3.0.9
    # via packaging
python-dateutil==2.8.2
    # via ghp-import
pyyaml==6.0
    # via
    #   mkdocs
    #   pyyaml-env-tag
pyyaml-env-tag==0.1
    # via mkdocs
six==1.16.0
    # via python-dateutil
watchdog==2.1.9
    # via mkdocs
zipp==3.8.0
    # via importlib-metadata
```

**Comment by sungam3r** [comment]
Current status
![изображение](https://user-images.githubusercontent.com/21261007/208067747-35dbfb6f-95a4-457a-b58a-8ba680599240.png)

**Comment by KUTlime** [comment]
Maybe this is the problem here:
(_the issue author is talking about one package - dbup, your are presenting notes from another package - dbup.core_)

![image](https://user-images.githubusercontent.com/8374320/213683751-1c24d1dd-2810-45f3-9f9a-42c54d852f61.png)

**Comment by droyad** [comment]
I'd like to lean into GitHub Issues/PRs for release notes if possible
