### ISSUE TITLE
Script execution is failed with LogScriptOutput option for output with double quotes

### ISSUE THREAD

**Issue by petr-konopelko** [DbUp/DbUp#646]
Product: dbup-sqlserver
Product version: 4.6.0
Environment: cakebuild with .Net 6
An error occurred during the printing message **_System.FormatException: Input string was not in a correct format._** when **_LogScriptOutput_** option is used and some column contains **double quotes** in value
P.S. on version 4.5.0 version the issue is not occurred

**Comment by mjauernig** [comment]
Closed due to age and to less information. If still needed, please reopen.
