### ISSUE TITLE
An unhandled exception of type 'System.MissingMethodException' occurred in dbup-mysql.dll:

### ISSUE THREAD

**Issue by consysPM** [DbUp/DbUp#679]
Hi,

when executing **DbUp.EnsureDatabase.For.MySqlDatabase** method i get the following exception:

Exception thrown: 'System.MissingMethodException' in dbup-mysql.dll
An unhandled exception of type 'System.MissingMethodException' occurred in dbup-mysql.dll: 'Method not found: 'Void MySql.Data.MySqlClient.MySqlConnectionStringBuilder..ctor(System.String)'.'
Stack trace:
 >   at MySqlExtensions.GetMysqlConnectionStringBuilder(String connectionString, IUpgradeLog logger, String& masterConnectionString, String& databaseName)
 >   at MySqlExtensions.MySqlDatabase(SupportedDatabasesForEnsureDatabase supported, String connectionString, IUpgradeLog logger, Int32 timeout, String collation)
 >   at MySqlExtensions.MySqlDatabase(SupportedDatabasesForEnsureDatabase supported, String connectionString)

Version:
dbup-mysql 5.0.1.0
MySql.Data 8.0.32
.NET Framework 7.0

The web application runs within linux docker but is developed in Windows 10.

**Comment by ADringer** [comment]
I've just encountered the same issue, @consysPM did you find a solution?

**Comment by bomehlsen** [comment]
We've temporarily fixed this issue by downgrading to version 8.0.31 of the MySql.Data package. I've done a PR to force the version of this lib to the newest (8.0.33) as this should permanently fix the issue.
