### ISSUE TITLE
Keep project alive

### ISSUE THREAD

**Issue by sungam3r** [DbUp/DbUp#684]
Please see #404 and linked PRs. I can't reopen issue so I created a new one. It's obvious that project needs a few new maintainers. As I said in #404 I'm glad trying to help to keep it alive. I have experience in supporting OSS projects at GitHub platform, see my profile.

**Comment by jez9999** [comment]
Perhaps you should fork it, or send an email direct to OctopusDeploy.  They don't seem to be paying attention here.

**Comment by sungam3r** [comment]
I'm rather skeptical about forks, 
see https://github.com/DbUp/DbUp/issues/404#issuecomment-1357970446

**Comment by codingbott** [comment]
Keep alive!

**Comment by sungam3r** [comment]
No feedback from maintainers so far.

**Comment by mjauernig** [comment]
Still no feedback? Has anybody an recommendation for an alternative?

**Comment by jez9999** [comment]
The alternative is for a significant-sized company to fork the current DbUp and announce that they're maintaining it.  DbUp as it is is still quote a good solution, it just could do with a few bugfixes and new features.

**Comment by sungam3r** [comment]
@droyad @AdrianJSClark please pay some attention.

**Comment by mjauernig** [comment]
> The alternative is for a significant-sized company to fork the current DbUp and announce that they're maintaining it. DbUp as it is is still quote a good solution, it just could do with a few bugfixes and new features. If I had a decent sized company that's what I'd do. Anyone here with a decent sized company I encourage you to fork DbUp and maintain it. :-)

I'am sorry, i have no significant-sized company in background. But i also would help to keep it alive.

**Comment by eugene-sh** [comment]
+1 I agree with @sungam3r about forks https://github.com/DbUp/DbUp/issues/684#issuecomment-1460074341.

This project is the best solution for us. Keep it alive.

**Comment by sungam3r** [comment]
No feedback yet.

**Comment by sungam3r** [comment]
@JakeGinnivan , @AdrianJSClark, @droyad - please anyone from members of dbup org, pay a bit attention to keep that project alive. If you cannot then please delegate access to someone else. I suggested myself to help.

**Comment by JakeGinnivan** [comment]
Hey @sungam3r. I've added you as a contributor. Also added @mjauernig

There are other access issues I'm sure, ping me an email to jake at ginnivan dot net and I can try sort those things. It doesn't make sense to fork and destroy the ecosystem.

@droyad hopefully this move is ok, if you want to ping me via email as well and we can maybe chat about how to hand this over properly

**Comment by sungam3r** [comment]
@JakeGinnivan Thanks but as I understand now I can only close issues - no write access to be able to edit/merge PR or edit repo settings. This is what I see on every PR - even my ones:
![изображение](https://github.com/DbUp/DbUp/assets/21261007/12e2e901-1190-44e7-b9ab-ae3496bce30f)

**Comment by sungam3r** [comment]
@JakeGinnivan Sorry, just saw invite from you in email 🤦‍♂️ . Thanks! Access granted so closing this one. In the coming days I will look throug pending PRs and issues to move things on.

**Comment by JakeGinnivan** [comment]
Just email me if you need any other access @sungam3r and thanks for stepping up

**Comment by mjauernig** [comment]
Hi, 

sorry for reopen the issue.

I begann with reviewing and approving some pull requests. And requested some reviews from @sungam3r. Is this ok? 

Shoud we have a chat group, where we can coordinate our work? Has someone a suggestion, where the team can discuss things?

**Comment by sungam3r** [comment]
> Is this ok?

Yep.

> Shoud we have a chat group, where we can coordinate our work? Has someone a suggestion, where the team can discuss things?

I think GitHub issues tracker is enough. Just post a new issue. Also GitHub has entire discussions feature (should be explicitly enabled in repo settings).

**Comment by jez9999** [comment]
@sungam3r I submitted an issue with a PR to fix a while back, #682 

Any chance of reviewing it?  :-)

**Comment by mjauernig** [comment]
> > Is this ok?
> 
> Yep.
> 
> > Shoud we have a chat group, where we can coordinate our work? Has someone a suggestion, where the team can discuss things?
> 
> I think GitHub issues tracker is enough. Just post a new issue. Also GitHub has entire discussions feature (should be explicitly enabled in repo settings).

@sungam3r Ok. Thanks for response. 

My plan is to merge in the next 1-2 weeks pull requests and then create a new release.

**Comment by mjauernig** [comment]
> @sungam3r I submitted an issue with a PR to fix a while back, #682
> 
> Any chance of reviewing it? :-)

I will take a look in the next days. But i'm new to the project. So, if the changes to "deep" then it maybee take a while before merging. I try first to understand the code.

**Comment by mjauernig** [comment]
@PaulStovell, @JakeGinnivan @jburger, @hossambarakat, @AdrianJSClark, @omnibs, @DamianMac, @droyad, @flin-8

Who from the team is still on board for:
- Can i ask questions to the code or for design decisions (Triggered through pull requests) 
- make some reviews
- check and close some issues

**Comment by sungam3r** [comment]
> Any chance of reviewing it? :-)

@jez9999 Yep. I think I'll make a tour through all pending issues/PRs next weekend. For now I have no all required permissions to go on quickly. Some settings are needed to be set into repo to speedup this process. I emailed to @JakeGinnivan about it.

@mjauernig I'm familiar with repo codebase and design in some extent. Feel free to ask.

I propose to close this issue since there are 2 maintainers for now who can help each other to move on. @mjauernig close if you agree.

**Comment by sungam3r** [comment]
@jez9999 Also feel free to ping me in issues you are interested in so that I don't forget.

**Comment by mjauernig** [comment]
@sungam3r
I agreee. But would be nice, if one of the old team members jump also in, too get all the work done.

**Comment by omnibs** [comment]
Hey friends, it's been some 6 years since I last touched C#! I think I'm unfit as a contributor at this point. Free free to remove me, and best of luck with DbUp! This project helped me a bunch back then, and y'all were very kind in taking me in!

**Comment by sungam3r** [comment]
> But would be nice, if one of the old team members jump also in

Reality is that only @JakeGinnivan contacted me (ather promptly) after I asked help explicitly by email. Other maintainers did not give feedback for a very long time. So I would not expect and wait for any activity from them. We just should do what we can and move things on.

**Comment by mjauernig** [comment]
I agree. But from time to time i will ask all team members about their status. It would be nice, if we got some statement from the members, like from @omnibs. Or something like "I'm sorry, i'm busy for the next year".

**Comment by sungam3r** [comment]
> Free free to remove me

Only project owner can do it.

**Comment by sungam3r** [comment]
> I submitted an issue with a PR to fix a while back, https://github.com/DbUp/DbUp/pull/682
> Any chance of reviewing it? :-)

Reviewed.

>  I think I'll make a tour through all pending issues/PRs next weekend.

Almost done.

**Comment by mjauernig** [comment]
@sungam3r Thank you for make a deep dive into the issues and pull requests, today!!

**Comment by mjauernig** [comment]
Hello everyone, 

I need to reopen this topic because this project is still stale.

After @sungam3r and I merged a lot of pull requests, I wanted to take the next step and create a release. 
So I opened issue #727 on the 29th of August. So far I got no feedback and today I decided to release the latest draft release [5.0.37](https://github.com/DbUp/DbUp/releases/tag/5.0.37).

After that, the github workflow was triggered and failed. See job [publish package](https://github.com/DbUp/DbUp/actions/runs/6430816826/job/17462497403). The specified API key is invalid, has expired or does not have permission to access the specified package.

Now we have moved the problem one step further from merging pull requests to publishing to nuget. We need an active project owner.

Another problem is that there is really no strategy for the project, and therefore no guidelines as to what changes I can and cannot add. See discussion on #735. 
Also, @sungam3r makes some best practice suggestions on how to organise the project. Which I really appreciate. But same problem here, we need someone to develop, implement and maintain these structures.

Summary. I think without someone who feels responsible for the hole project, controls the whole pipeline and finally makes project decisions, the project will die. 

So question to @JakeGinnivan, @AdrianJSClark, @droyad, @DamianMac, @jburger, @PaulStovell: can you become active again? If not, please hand the whole project (github, nuget, readthedocs) over to me or someone else.

**Comment by JakeGinnivan** [comment]
I cannot become active again, I don't really use dotnet anymore. 

@mjauernig if you can email me with the link of the resource you want access to, and your username on whatever that platform is then I will invite you.

jake at ginnivan dot net

**Comment by DamianMac** [comment]
Hi @mjauernig !
I've pinged @droyad about it, I know he had some plans a while back. 
Otherwise I can be more active too.

**Comment by mjauernig** [comment]
@JakeGinnivan I send you an mail.

@DamianMac 
> Otherwise I can be more active too.
That would be great. What tasks can you take on? Issues? Reviews?

**Comment by droyad** [comment]
Thanks for the ping @DamianMac, my plan for the project is up in #632 

I realise that I have been absent and not paying attention. Handing leadership over to another maintainer, or finding new maintainers is probably in the best interests of the project.

I'll confer with the other maintainers this week to see what we want to do.

**Comment by JakeGinnivan** [comment]
In the meantime I've added @mjauernig to readthedocs, nuget and he was already a maintainer on the GitHub org.

**Comment by mjauernig** [comment]
@JakeGinnivan. Thanks for the permissions. Today I released successfully on nuget (Version 5.0.37). 

> I'll confer with the other maintainers this week to see what we want to do.

@droyad 
Any result? 

If not, I will step in and restructure the future plan and development process.

**Comment by droyad** [comment]
@mjauernig Thanks for doing that release.

I'm aiming to get the project officially adopted by a company so that we can have someone use their work time to maintain this project. I think that is the most sustainable long term.

In the short term, my employer is willing to give me some work time to do some work on this project.

@mjauernig I've dropped you an email on your company's info address so you have my contact details and we can co-ordinate.

One of the first things I'd like to do is finish the split described in #632 if it doesn't interfere with other things going on (still need to catchup).

**Comment by jez9999** [comment]
Companies can get bored of maintaining something and consider it financially not worthwhile.  I think you'd be better off trying to get it maintained by several dedicated volunteers who use the project and find it valuable.  Most of what it needs now are minor changes and bug fixes, anyway.  Maybe the odd .NET platform upgrade.

**Comment by droyad** [comment]
@mjauernig and I just had a productive discussion on the plan for the project. 

I've created 3 boards @mjauernig, hopefully they are what you were thinking:
- v6.0 - Breaking changes in the next release, 🤞by Nov
- v6.Next - Enhancements after 6.0
- v7+ Breaking changes - Any breaking changes we want to put off till next year sometime

I've also done some fine tuning of permissions, let me know if anything is missing.

Stay tuned!

**Comment by mjauernig** [comment]
Can you please give me permission to bypass the protected master branch? I want to fix bugs in the build pipeline.

For example:
<img width="580" alt="image" src="https://github.com/DbUp/DbUp/assets/7187699/418f4882-ed61-435d-8b62-a11b53c2e89f">

Readthedocs also has bugs. 

I will only use the bypass for CI and some documentation fixes.

**Comment by droyad** [comment]
@mjauernig Done

**Comment by mjauernig** [comment]
> @mjauernig Done

@droyad 
Thanks. But not working. Can't merge my own pr [https://github.com/DbUp/DbUp/pull/753](https://github.com/DbUp/DbUp/pull/753).

<img width="620" alt="image" src="https://github.com/DbUp/DbUp/assets/7187699/00dd5b76-c8b4-433f-9274-445b88f743d3">

**Comment by droyad** [comment]
I've approved it. PRs need to be reviewed by someone other than the author.

**Comment by mjauernig** [comment]
Thank you. But with owner rights I could overcome the rule and merge my own pull requests without approval. At the moment i can't. Maybe you can add me to the bypass list or give me owner rights again. 

For documentation and build pipeline updates I would like to create pull requests and then merge them.
