### ISSUE TITLE
Unable to keep track of changes in script

### ISSUE THREAD

**Issue by NiranjanGodboleMaersk** [DbUp/DbUp#687]
Hi I have table created below 

create table dbo.test(Id SERIAL PRIMARY KEY,
ProductName VARCHAR(24) NOT NULL,
Description Text,
Amount INT)
 
I ran my console application and table got created. 

Next time I want to add one extra column so i will modify the same script
create table dbo.test(Id SERIAL PRIMARY KEY,
ProductName VARCHAR(24) NOT NULL,
Description Text,
Amount INT,
Quantity INT)

Now when I run my application it wont track the changes and add the column Quantity. Can someone pls help on this?

**Comment by sungam3r** [comment]
DbUp just does not work so, it does not track changes into scripts. DbUp tracks executed scripts so instead of modifying script1 just add script2 with new column.

**Comment by irahsu** [comment]
I found DbUpX to be a solution: `https://github.com/fiscaltec/DbUpX`. Instead of a SchemaVersions table, it uses a SchemaVersionHash table, which hashes the contents of each script, so that when a script's content changes, it get re-run.
