### ISSUE TITLE
Question: Is it possible to log executing script text?

### ISSUE THREAD

**Issue by ygavrishov** [DbUp/DbUp#689]
Hi, guys! We use dbup-sqlserver for migrations. Sometimes on investigations it's quite helpful to see what scripts were particularly executed without reviewing commits and file contents. So the question is

Is it possible to log executing script text?

It can be implemented by adding WriteTrace in IUpgradeLog interface

**Comment by sungam3r** [comment]
> Is it possible to log executing script text?

Of course, PR is welcome.

**Comment by mjauernig** [comment]
Closed due to inactivity. If still needed, please reopen.
