### ISSUE TITLE
MySQL database no support "-"

### ISSUE THREAD

**Issue by tanshanli** [DbUp/DbUp#690]
``` json
// appsettings.json
{
  "ConnectionStrings": {
    "DbConnect": "Data Source=localhost;port=3306;User ID=root;Password=123456;Database=db-demo3;CharSet=utf8;sslmode=none;allowuservariables=True;AllowLoadLocalInfile=true"
  }
}
```
``` C#
IConfiguration config = new ConfigurationBuilder()
                .SetBasePath(AppContext.BaseDirectory)
                .AddJsonFile("appsettings.json")
                .Build();

            string connectionString = config.GetConnectionString("DbConnect");
EnsureDatabase.For.MySqlDatabase(connectionString); // error
```

error message:
`MySql.Data.MySqlClient.MySqlException:“You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-demo3' at line 1”`

When the value of Database is db_demo or dbdemo is normal

**Comment by mjauernig** [comment]
Can you please try to quote your database with ```'``` or ```\"```. Example: ```;...Database='db-demo3';...```

**Comment by mjauernig** [comment]
@tanshanli The thumb up 👍 means the solution works? 

I interpret it as an yes and close the issue. If not please reopen the issue.

**Comment by tanshanli** [comment]
> @tanshanli The thumb up 👍 means the solution works?
> 
> I interpret it as an yes and close the issue. If not please reopen the issue.

Yes, solved this problem effectively
