### ISSUE TITLE
Firebird integration has degraded

### ISSUE THREAD

**Issue by Jeern** [DbUp/DbUp#691]
Hi,

I am the original creator of the firebird integration for dbUp 9 years ago. It has unfortunately degraded over time.

1. The JournalTable SchemaVersions table was originaly created using an unquoted tableName. Someone has changed this so it is created as "schemaversion" i.e. quoted. This does not work when a Trigger is later created that references the table unqouted. It is easily fixed and I will provide a PR. Since this was a general change for all databases it indicates to me that Firebird was not tested after the change.

2. WithTransactionPerScript deployments fails when the SchemaVersions table is not created yet. The reason is that the Trigger operates outside the Transaction and tries to upgrade the Id of the SchemaVersions table. Which does not exist. Giving the error: "FirebirdSql.Data.FirebirdClient.FbException (0x80004005): Dynamic SQL Error
SQL error code = -204
Table unknown
schemaversions"

I will also look into fixing nr. 2. Until then the workaround is to do an intial run without WithTransactionPerScript when SchemaVersions has been created it will work afterwards.

**Comment by Jeern** [comment]
It was quite easy to fix the first problem as expected. I would like to fix the second as well before sending the PR. It is however difficult to find the best solution. I would believe the Journal table should not be in the transaction for any provider however it would be a bit much for me to change the behaviour of all providers i.e would mean that the Journal table would be created even if the first script fails. To me that sounds better than the current situation - why should the first script and the journal table have a special "connection". On the other hand if I change the code for firebird only there would be some copy/pasted code which I don't like.

**Comment by sungam3r** [comment]
This repo looks abandoned, see #684

**Comment by Jeern** [comment]
Thank you @sungam3r  I will still try to fix the problem and create a PR and then consider what to do. Since I created the dbup-firebird integration original 9 years ago where I am still employeed and since my company still uses it extensively in at least 5 projects and there probably are not many companies using the Firebird integration it would be logical for me to maintain that particular component (we also use the postgres integration but only in one project)

**Comment by Jeern** [comment]
I have made the PR: https://github.com/DbUp/DbUp/pull/692

**Comment by sungam3r** [comment]
You may be interested in #431.

**Comment by Jeern** [comment]
The plan in https://github.com/DbUp/DbUp/issues/431 sounds sensible. I don't know if becoming a maintainer is a good idea or how to become one, if they no longer have the stomach for maintaining it. I am going on 3 weeks holiday now and hope someone has looked at my PR when I come back (because I will need it by then). If nothing has happened I have no idea how to proceed

**Comment by Jeern** [comment]
@mjauernig Thank you for merging - it seems there is a problem with a unittest that tests "No public API change" - https://github.com/DbUp/DbUp/actions/runs/5836228445 - I took care in not changing the API - I have added two properties to ScriptExecutor and DatabaseConnectionManager but made sure there are default values and the behavior is the same for old classes. So perhaps the test is wrong ? Do you know if Nuget packages are released automatically from master when there is a push to master and this change blocks it ? I will look at it monday and see if there is an obvious problem.

**Comment by mjauernig** [comment]
@Jeern

I saw the wrong test and wrote a fix. See https://github.com/DbUp/DbUp/pull/695

No, their is no automatically release to nuget packages. At the moment the ci creates a draft release at github. My plan is to close a few another pull requestes and then release a new version. But i have to check, if i have the rights to push to nuget.

**Comment by Jeern** [comment]
@mjauernig Ok. Thank you. Looking forward to a new version 

I also got some permissions from Jake Ginnivan (not sure what I can do). 

I have asked my boss if I can use a little time to help out if there is Firebird related issues. He said ok. 

Its not that I am a Firebird expert, more into PostgreSQL, but there is a lot of opportunity at my workplace to test Firebird related DbUp stuff because we use Firebird with DbUp in several products and have been since I made the provider in 2014 :)

**Comment by mjauernig** [comment]
@Jeern 
Greetings to you and your boss. Thank you for help! 

It would be nice if you can look at the firebird issues ([Open Firebird issues](https://github.com/DbUp/DbUp/issues?q=is%3Aissue+is%3Aopen+firebird)) and pull requests ([Open Firebird pull requests](https://github.com/DbUp/DbUp/pulls?q=is%3Apr+is%3Aopen+firebird)). 
The issues are partially linked with pull requests, maybee you can check if the suggested code is ok or if we should close the pull request.

I think you don't need special permissions. Just create an pull request for code updates. @sungam3r or i will then review the code. 


P.S.
If you have boredom just grab and fix an non firebird issue. 😉

**Comment by JakeGinnivan** [comment]
Sorry @Jeern this dropped off my radar, have added you
