### ISSUE TITLE
Remove DbUp.Tests.Common from packages?

### ISSUE THREAD

**Issue by sungam3r** [DbUp/DbUp#709]
What is it?
![изображение](https://github.com/DbUp/DbUp/assets/21261007/68399b59-6d68-47c1-b1a0-e37c959f95aa)

**Comment by Havagan** [comment]
Is this as simple as adding `<GeneratePackageOnBuild>true</GeneratePackageOnBuild>` to the DbUp.Tests.Common.csproj?

**Comment by Havagan** [comment]
PR https://github.com/DbUp/DbUp/pull/731

You can assign this issue to me if you like.

**Comment by mjauernig** [comment]
I will gladly assign it to you. Thank you very much.

**Comment by droyad** [comment]
This package is the shared testing components used by the provider libraries, we only publish it to the GitHub package repository.
