### ISSUE TITLE
Add note about DbUpX into readme

### ISSUE THREAD

**Issue by sungam3r** [DbUp/DbUp#710]
I found DbUpX to be a solution: [https://github.com/fiscaltec/DbUpX](https://github.com/fiscaltec/DbUpX). Instead of a SchemaVersions table, it uses a SchemaVersionHash table, which hashes the contents of each script, so that when a script's content changes, it get re-run.

Edit: figured out how to make a link using Markdown...

_Originally posted by @irahsu in https://github.com/DbUp/DbUp/issues/687#issuecomment-1569118192_

**Comment by mjauernig** [comment]
See PR #736
