### ISSUE TITLE
Replace LibLog with Microsoft's logging abstractions

### ISSUE THREAD

**Issue by Havagan** [DbUp/DbUp#720]
With [LibLog deprecated](https://github.com/damianh/LibLog/issues/270), is there a desire to replace it with [Microsoft.Extensions.Logging.Abstractions](https://www.nuget.org/packages/Microsoft.Extensions.Logging.Abstractions)?

**Comment by mjauernig** [comment]
Yes, we should replace it.

**Comment by Havagan** [comment]
@mjauernig I can try and take this.

**Comment by Havagan** [comment]
@mjauernig Logging abstractions only supports netstandard2.0 and up. Does this mean we remove support in dbup for netstandard1.3?

**Comment by mjauernig** [comment]
@Havagan Sure you can grab this. Thank you.

I would say we should drop netstandard1.3. Microsoft also recommend this:
> We recommend you target .NET Standard 2.0, unless you need to support an earlier version. Most general-purpose libraries should not need APIs outside of .NET Standard 2.0. .NET Standard 2.0 is supported by all modern platforms and is the recommended way to support multiple platforms with one target.

Source: [.net Standard Microsoft](https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0)

Another reason for me is: As a community project with limited ressources we can not support any old framework/standard.

@sungam3r Do you agree?

Because this is breaking we would merge the change to release 6 or 7.

**Comment by Havagan** [comment]
Updated tests to match new logging signatures. All tests pass locally.

![image](https://github.com/DbUp/DbUp/assets/2288850/d62a19bc-6a07-4daf-9a07-17e7300ff02c)

**Comment by twenzel** [comment]
@Havagan any progress on this issue?

**Comment by Havagan** [comment]
@twenzel LibLog has been replaced with logging abstractions and PR #720 created. Since that PR, the tests have been refactored under PR #721 which has caused some merge conflicts that need to be resolved.

Since this issue is a `breaking` change, I didn't prioritize fixing the merge conflicts (because I started a new job three weeks ago). I should have some time this weekend to resolve the merge conflicts and update the PR.

**Comment by Havagan** [comment]
I merged `master` into `feature/ilogger-support` and resolved the merge conflicts. All tests pass after updating the verified snapshot test files to match the new logger signatures.

**Comment by mjauernig** [comment]
Thanks @Havagan for the contribution. I will merge it into the v6 release in the next few weeks.

**Comment by droyad** [comment]
Superceeded by #788
