### ISSUE TITLE
What do you think about a Deployment Manifest

### ISSUE THREAD

**Issue by dazinator** [DbUp/DbUp#76]
I recently implemented the following in a dev branch of CrmUp: https://github.com/dazinator/CrmUp/wiki/Deployment-using-a-Deployment-Manifest

but not sure if its a feature that you might be interested in? It wouldn't be very difficult for me to adapt it if you were.

**Comment by JakeGinnivan** [comment]
Would it just be a script provider of some sort?

**Comment by dazinator** [comment]
Yeah. Here is the script provider: https://github.com/dazinator/CrmUp/blob/master/src/CrmUp/DeploymentManifestScriptProvider.cs

The main use case behind this was for a companion "releaser" tool that let you create a deployment package (windows forms).. it would export a nuget package containing crmup, and the appropriate "deployment manifest" which lists which scripts / migrations are to be run and in what order. The script files / code migration assemblies were included in the nuget package along side the exe (not embedded).

**Comment by hyphen81** [comment]
Did this ever get added by any chance? I'm very interested in implementing this into our dbup workflow.

**Comment by sungam3r** [comment]
@dazinator Is this issue still actual?

**Comment by dazinator** [comment]
I opened this for feedback a long time ago when I was prepared to contribute something. However as not enough demand at that time I think this can be closed.
