### ISSUE TITLE
Composite formatting error when script output contains { or } characters

### ISSUE THREAD

**Issue by Extant-1** [DbUp/DbUp#779]
If an executing database script outputs a line that contains a composite formatting item, for example {0}, an exception is thrown since the call to Console.WriteLine() is parsing the item as argument to be formatted.

Example:
`SELECT "Hello this is a string that contains composite formatting such as {0}"`

Runtime exception:

> Error occured when executing scripts, transaction will be rolled back
> Upgrade failed due to an unexpected exception:
> System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
>    at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
>    at System.IO.StreamWriter.WriteFormatHelper(String format, ParamsArray args, Boolean appendNewLine)
>    at System.IO.StreamWriter.WriteLine(String format, Object[] arg)
>    at System.IO.TextWriter.SyncTextWriter.WriteLine(String format, Object[] arg)
>    at System.Console.WriteLine(String format, Object[] arg)
>    at DbUp.Engine.Output.ConsoleUpgradeLog.Write(ConsoleColor color, String format, Object[] args) in C:\code\DbUp\src\dbup-core\Engine\Output\ConsoleUpgradeLog.cs:line 46
>    at DbUp.Engine.Output.ConsoleUpgradeLog.WriteInformation(String format, Object[] args) in C:\code\DbUp\src\dbup-core\Engine\Output\ConsoleUpgradeLog.cs:line 17
>    at DbUp.Support.ScriptExecutor.WriteReaderToLog(IDataReader reader) in C:\code\DbUp\src\dbup-core\Support\ScriptExecutor.cs:line 261
>    at DbUp.Support.ScriptExecutor.ExecuteAndLogOutput(IDbCommand command) in C:\code\DbUp\src\dbup-core\Support\ScriptExecutor.cs:line 198
>    at DbUp.Support.ScriptExecutor.<>c__DisplayClass20_2.<Execute>b__2() in C:\code\DbUp\src\dbup-core\Support\ScriptExecutor.cs:line 153
>    at DbUp.SqlServer.SqlScriptExecutor.ExecuteCommandsWithinExceptionHandler(Int32 index, SqlScript script, Action executeCommand) in C:\code\dbup-sqlserver\src\dbup-sqlserver\SqlScriptExecutor.cs:line 44
>    at DbUp.Support.ScriptExecutor.<>c__DisplayClass20_0.<Execute>b__0(Func`1 dbCommandFactory) in C:\code\DbUp\src\dbup-core\Support\ScriptExecutor.cs:line 151
>    at DbUp.Engine.Transactions.SingleTransactionStrategy.Execute(Action`1 action) in C:\code\DbUp\src\dbup-core\Engine\Transactions\SingleTransactionStrategy.cs:line 24
>    at DbUp.Engine.Transactions.DatabaseConnectionManager.ExecuteCommandsWithManagedConnection(Action`1 action) in C:\code\DbUp\src\dbup-core\Engine\Transactions\DatabaseConnectionManager.cs:line 117
>    at DbUp.Support.ScriptExecutor.Execute(SqlScript script, IDictionary`2 variables) in C:\code\DbUp\src\dbup-core\Support\ScriptExecutor.cs:line 126
>    at DbUp.Engine.UpgradeEngine.PerformUpgrade() in C:\code\DbUp\src\dbup-core\Engine\UpgradeEngine.cs:line 84

The fix is to replace any { or } characters in the output line with {{ or }}. which will then be escaped when calling Console.WriteLine.

I can't seen to create a pull request due to permissions but fix could be:

Line: https://github.com/DbUp/DbUp/blob/da8191b1b485f67703ab0502e4cf0e35a8e280d6/src/dbup-core/Support/ScriptExecutor.cs#L235

Replace 
`                    value = value == DBNull.Value ? null : value.ToString();`
With
`                    value = value == DBNull.Value ? null : value.ToString().Replace("{","{{").Replace("}","}}");`

**Comment by droyad** [comment]
> The fix is to replace any { or } characters in the output line with {{ or }}. 

I think we'd need to match up braces and replace them, i.e use a RegEx
