### ISSUE TITLE
Should the RunAlways Script Type not write to the log?

### ISSUE THREAD

**Issue by DamianMac** [DbUp/DbUp#789]
So I just stumbled across the ScriptType.RunAlways option when a dev on of my teams used it.

It gives a really nice fluent API for setting up a migration where you want some things to be a true migration, and some things run each time. My use case for this has always been older databases with lots of stored procedures.

It's why we put the NullJournal in there which lets you run a bunch of scripts and not log them.

Using the Script type option allows for much nicer syntax, but if you have a DB with hundreds of stored procedures (in this case I do) you will end up with many thousands of rows in the SchemaVersions table over time.

So I propose, and I'm happy to write the code, if you select the ScriptType.RunAlways version it doesn't write to the journal.

Any objections to this?

**Comment by DamianMac** [comment]
BTW kudos @BobJWalker for that change, it's a much nicer syntax. Traditionally I've run multiple migrations, one tracked, and another one not tracked.

**Comment by BobJWalker** [comment]
To be honest, when I added that I thought people would want to see it written to the journal so they could get a history of all the scripts that have been run on the instance.  But I could see an argument for excluding it, as I suspect the majority of the run always scripts are stuff like "assign role"

**Comment by DamianMac** [comment]
I do see your point for that one, as an audit trail. 
But for my usecase that table is going to become a slow and largely useless thing in a hurry.
Maybe a new enum option, RunAlwaysNonLogged? (open to naming suggestions)

**Comment by BobJWalker** [comment]
I like that as an option as it won't change existing functionality for anyone else who is using the feature.

**Comment by droyad** [comment]
I think that makes sense, meets what I would expect. 

Since we are cutting 6.0 I think it'd be ok to add this as a breaking change.

If we ever overhall the API, I image DbUp working in two modes: Update (for Sprocs/Views/Etc) and ChangeSchema (for tables/etc)

**Comment by DamianMac** [comment]
@droyad You think my original proposal? Or the additional enum? 
If you're in release mode at the moment I'll send a PR today

**Comment by droyad** [comment]
Original proposal. I expect v6 to go out late March.

**Comment by champin4** [comment]
I know this is merged and closed now, so if I should move this discussion elsewhere I can. But we are just implementing for our project and we absolutely need the audit-ability of any kind of script running. Are there any suggestions for how to get a runalways script to log anyways?

**Comment by droyad** [comment]
@champin4 The upgrader returns a `DatabaseUpgradeResult` which has a collection of `SqlScript` (`.Scripts`) that were run. I suggest logging or recording these. For auditability this may be a better solution anyway as you can include other data as well (e.g. deployment it was part of, who ran it, and other log output).
