### ISSUE TITLE
DbUpX seems to be an abandoned project

### ISSUE THREAD

**Issue by max-lancaster** [DbUp/DbUp#793]
The last commit for the `DbUpX` library mentioned on the home page of this repository was 5 years ago and there are [only 4 commits in the commit history](https://github.com/fiscaltec/DbUpX/commits/master/) .  It seems like a great library with some nice features but once I started using it I discovered two significant bugs within a week:

https://github.com/fiscaltec/DbUpX/pull/1
https://github.com/fiscaltec/DbUpX/pull/2

**Comment by jez9999** [comment]
@mjauernig @droyad @sungam3r @JumpingJezza Are any of you guys around?  This project does seem to have lapsed into being unmaintained again.  *sigh*  If any of you have admin privileges, maybe you could make me an admin?  I use the DbUp in my project actively and would be prepared to put some time in on maintaining it / reviewing PRs / etc.

**Comment by droyad** [comment]
I didn't respond to this sooner because this issue seems to be with that extension library that we do not maintain. 

The referenced PRs are no longer open.

Are you proposing we remove the reference? Do those bugs stop that library being useful?

**Comment by max-lancaster** [comment]
> I didn't respond to this sooner because this issue seems to be with that extension library that we do not maintain.
> 
> The referenced PRs are no longer open.
> 
> Are you proposing we remove the reference? Do those bugs stop that library being useful?

They are pretty significant bugs, I'm going to look into forking that repo and publishing a new package with the bug fixes, once I do that I will probably submit a PR to change the documentation references in this repository.
