### ISSUE TITLE
Dry Run feature

### ISSUE THREAD

**Issue by markoueis** [DbUp/DbUp#797]
Similar to other tools like flyway and liquibase, the ability to do a dryrun would be very useful. First would be to get a list of scripts it would run. Second would be a dump of those scripts somewhere for inspection. The first would be good enough to start.

Does this feature already exists but maybe its called something else?

Thanks

**Comment by droyad** [comment]
@markoueis Instead of calling `PerformUpgrade()` on the `UpgradeEngine`, you can call `GetScriptsToExecute()` which will return what SqlScripts will be executed (which includes names and contents) see https://github.com/DbUp/DbUp/blob/main/src/dbup-core/Engine/SqlScript.cs
