### ISSUE TITLE
Filters require Path and Filename

### ISSUE THREAD

**Issue by dalej** [DbUp/DbUp#80]
The logic in any of the filters in filters.cs fails if the original source of script files is located in a Directory (and, of course, the Directory name is passed in as a parameter). The "scriptNames.Contains(s)" fails because a filter script name does not contain a path, but the script file listings do include paths. 

The logic is actually backwards where the longer path+file name string is being checked for a contain within the shorter file name string.

All works well only if a) scripts are in the root of the Project and no Scripts Directory is utilized or b) if the Directory path is prepended onto the filter script file name.

**Comment by droyad** [comment]
You can now specify your own filter. I'm not 100% sure what the problem is, but I would considering adding support if more details are provided.
