### ISSUE TITLE
TransactionPerScriptStrategy: DbCommand with committed transaction

### ISSUE THREAD

**Issue by liborweigl** [DbUp/DbUp#801]
For reproduce this issue we can use script from samples

https://github.com/DbUp/DbUp/blob/master/src/Samples/SampleApplication/Scripts/Script0005%20-%20ComplexUpdate.cs#L17

if we use `commandFactory` for create dbCommand  :

```
public string ProvideScript(Func<IDbCommand> commandFactory)
{
    var dbcommand = commandFactory();  // DbCommand is creat with committed transaction
         dbcommand .CommandText = "select 1"; 
         dbcommand .ExecuteScalar();
}
```

It creates `DbCommand `  with committed transaction because it does call back to result after  `transaction.Commit();`  has been already invoked :

https://github.com/DbUp/DbUp/blob/e874234e8d320dc37c272e5137092da0b89d72f3/src/dbup-core/Engine/Transactions/TransactionPerScriptStrategy.cs#L30-L37

I couldn't find in documentation if we should use `commandFactory` to created `dbcommand` inside `ProvideScript` method from `IScript`.

Created `DbCommand ` this way in `SQLite` flavour cause exception during DbCommand execution because assigned transaction is committed.

**Comment by droyad** [comment]
Fixed in #440, ProvideScript now runs under a transaction when using TransactionPerScript. However not the same transaction as the script the method returns.
