### ISSUE TITLE
System.MissingMethodException: Method not found: 'DbUp.Engine.Output.IUpgradeLog DbUp.Builder.UpgradeConfiguration.get_Log()'. After upgrading to v6

### ISSUE THREAD

**Issue by Edddy** [DbUp/DbUp#802]
I notice that dbup-sqlserver is still in 5.0.41, is that the problem? should I wait?

My code it's pretty straithforward:

                var ConnString = System.Configuration.ConfigurationManager.ConnectionStrings[CodigoSiteTenant + "ConnectionString"].ConnectionString;
                var upgrader = DeployChanges.To
                    .SqlDatabase(ConnString)
                    .WithScriptsFromFileSystem(Server.MapPath("~/app_data/dbup"))
                    .LogToNowhere()
                    .Build();

                var result = upgrader.PerformUpgrade();
                if (!result.Successful) {
                    throw result.Error;
                }

**Comment by droyad** [comment]
Alternatively you could reference the prerelease version of dbup-sqlserver.
