### ISSUE TITLE
SQL Server dispose lag (probably)

### ISSUE THREAD

**Issue by kfkawalec** [DbUp/DbUp#82]
My console App have about 2 sec lag after all script to database has been published and application end.
I try to find where this is but with no luck.
How can i change this behavior?

**Comment by JakeGinnivan** [comment]
What transaction mode is set? If using transactions this could be committing the transaction. Best bet is to open up sql profiler and see what is happening.

Sent from my Windows Phone
________________________________

**Comment by karbon001** [comment]
I tried with and without transaction.
SQL Profiler looks ok with very small times.
But this does happen when connection has been initialized to SQL Server.
When i replace functions that store data in table SchemaVersions to memory everything works much faster.
[Link to video](https://www.dropbox.com/s/f7mak2nb0wdraic/Recording2.mp4)

**Comment by droyad** [comment]
Could not reproduce
