### ISSUE TITLE
SqlScriptExecutor should be pulled into core

### ISSUE THREAD

**Issue by sandcastle** [DbUp/DbUp#83]
Several database providers (Postgres, MySQL and Sqlite) use the SqlScriptExecutor which is currently under the SQL Server namespace. This results in log messages being generated with the words **SQL Server** in them:

```
Executing SQL Server script 'App.Data.Up.Scripts.Script-0001.sql'
```

If there is appetite for the change I'll send a PR.

Thoughts?

**Comment by JakeGinnivan** [comment]
Sounds like a simple fix which improves logging. Happy to get a PR

**Comment by dazinator** [comment]
I have a PR which will fix this, submitting shortly

**Comment by droyad** [comment]
Looks like this is done
