### ISSUE TITLE
Ordering of (embedded) files is a bit... meh

### ISSUE THREAD

**Issue by worldspawn** [DbUp/DbUp#84]
If i have sql files spread across folders the naming of the folder influences (breaks) the execution ordering of the files. The list of files should be ordered by their filename only imo. 

Manifest resource names make this somewhat difficult as folder separators are replaced with periods however assuming we can say _dont include periods in your filenames other than the extension_ you could write something like this:

``` csharp
    public class FlatSortedEmbeddedScriptProvider : IScriptProvider
    {
        private readonly Assembly _assembly;
        private readonly Func<string, bool> _filter;

        public FlatSortedEmbeddedScriptProvider(Assembly assembly, Func<string, bool> filter)
        {
            _assembly = assembly;
            _filter = filter;
        }

        public IEnumerable<SqlScript> GetScripts(IConnectionManager connectionManager)
        {
            return _assembly
                .GetManifestResourceNames()
                .Where(_filter)
                .OrderBy(x => Path.GetFileNameWithoutExtension(x).Substring(Path.GetFileNameWithoutExtension(x).LastIndexOf('.') + 1))
                .Select(s => SqlScript.FromStream(s, _assembly.GetManifestResourceStream(s)))
                .ToList();
        }
    }
```

**Comment by rickculpepper** [comment]
What is the real-world use case this issue?

Clearly, there are other schemes for using folders to organize scripts. However, DbUp is a deployment tool with a simple approach to organizing scripts. If the scheme used for organizing scripts in folders does not represent deployment order, managing script sequence becomes a cumbersome task that grows in complexity over the life of the database.

It seems to me that including the folder name in the logic to determine execution sequence is a useful feature. I can, for instance, put all of my scripts for a given release of the database into a single folder. 

Furthermore, limiting file names to a single dot ('.') character to denote the extension seems somewhat arbitrary. It also seems that this constraint would result in frustration for developers trying to use DbUp, especially at the beginning.

**Comment by worldspawn** [comment]
Been a while but I believe I had a _base_ set of files and then some other files in other folders that matched specific environments eg _dev_, _uat_. What I wanted to happen was that list of files to be merged/flattened and ordered by the filename only. This was a legit real world need as scripts targeting any one env still have to assume a current state of the target db when written. In this case the folders had nothing to do with the deployment order (and frankly, that seems a far less likely use for folders than using them for target environments, what would the folders be called? 01-2015, 02-2015? why would anyone arrange it like that?).

Limiting the file names to a single dot is done simply because theres no other option. Manifest resource naming shoots any other option in face. I fully concede its stupid and not something u'd want in a general-for-everybody, release. This issue is more of a share than a suggestion to modify the default codebase.

**Comment by JakeGinnivan** [comment]
@worldspawn would you submit a pull request to the docs to make this more discoverable?

I am going to close this issue as I am not sure how to action it :)
