### ISSUE TITLE
UpgradeEngine.TryConnect throw null reference exception

### ISSUE THREAD

**Issue by youngcm2** [DbUp/DbUp#86]
The transaction strategy is throwing the null reference exception

**Comment by JakeGinnivan** [comment]
Could you include the code used to produce this. Pull requests with the fix and a test also welcome.

Sent from my Windows Phone
________________________________

**Comment by youngcm2** [comment]
Created a pull request.
https://github.com/DbUp/DbUp/pull/87

**Comment by dazinator** [comment]
@youngcm2 - apologies for the delay with this one, would it be possible to include some code / unit test that produces the exception you are fixing with these changes? Quite hesitant to pull in changes to the core unless a problem is clearly demonstrated first (not saying there isn't a problem just would like to see it reproduced first). I am using DbUp current version without any exceptions at present you see - but we are most likely using it differently and you have managed to expose an issue. Thanks for your work on this - hopefully we can get this merged soon :)

**Comment by youngcm2** [comment]
I fixed the issue in https://github.com/DbUp/DbUp/pull/87. We have already been working off my fork. I was able to reproduce this by just running tryconnect. I also was not able to compile test b/c of missing mono dll.

**Comment by michaeldotknox** [comment]
Not to be the "me too" guy, but we are getting this error as well, with pretty basic configuration:

```
            var upgrader =
                DeployChanges.To.SqlDatabase(connectionString)
                    .WithScriptsEmbeddedInAssembly(Assembly.GetExecutingAssembly()).Build();

            var connectMessage = string.Empty;
            var connectResult = upgrader.TryConnect(out connectMessage);
```

Anything that you could do to adopt the fix from @youngcm2 would be greatly appreciated.
