### ISSUE TITLE
When error in script occurred DbUp method Perform Upgrade don't provide in exception the name of failed script.

### ISSUE THREAD

**Issue by MaksymDrach** [DbUp/DbUp#96]
When i invoke method PerformUpgrade (DbUp.Engine.UpgradeEngine), and i have script with error, DbUp fails and method PerformUpgrade returned DatabaseUpgradeResult which contain Exception, but info about exception does not provide the name of the failed script.
I'm added some fix, please check it.
![image](https://cloud.githubusercontent.com/assets/12810211/8053178/65dd59bc-0e8e-11e5-95af-7f64a67f0769.png)

**Comment by JakeGinnivan** [comment]
Could you submit a pull request for this?

**Comment by MaksymDrach** [comment]
Hi I’m trying to push new branch to the repo but I don’t have permission to do it.

**Comment by JakeGinnivan** [comment]
@MaksymDrach you need to create a fork, then submit a pull request from your fork. See https://help.github.com/articles/using-pull-requests/

**Comment by MaksymDrach** [comment]
Thank’s a lot!

**Comment by MaksymDrach** [comment]
Pull request created.

**Comment by MaksymDrach** [comment]
Here’s the link: https://github.com/DbUp/DbUp/pull/97

**Comment by MaksymDrach** [comment]
Hi, Jake what about the status of my pull request?

**Comment by omnibs** [comment]
Merged, closing!
